bug/PATRO23-331 - Change to ISO8601 date format
intive/patronage2023-dotnet pull request #100
Opened 2023-05-15 20:37 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-331

2023-05-15 21:35 UTC, mateuszgiedzinski requested changes

2023-05-15 21:35 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/BudgetAmount.cs
> +	public string DatePoint { get; init; } = null!;
We shouldn't change DateTime to string to specify date time format returned to the api. Instead of this we should do following thing
Implement JsonDateTimeConverter deriving from JsonConverter class. We should have both implementation for DateTime? and DateTime. 
Converter class you can find in  System.Text.Json.Serialization. 
After implementation you should add your converters into options.JsonSerializerOptions.Converters in program.cs

2023-05-15 21:37 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/BudgetAmount.cs
> +	public string DatePoint { get; init; } = null!;
Also if you could please specify date time format in some const.

2023-05-17 04:14 UTC, mateuszgiedzinski approved these changes

2023-05-17 05:55 UTC, DawidBski approved these changes

2023-05-17 06:11 UTC, merged