tests/PATRO23-337 - add tests for user budget
intive/patronage2023-dotnet pull request #103
Opened 2023-05-17 12:31 UTC by DawidBski

2023-05-18 20:56 UTC, mateuszgiedzinski requested changes

2023-05-18 20:56 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/UserBudget/UserBudgetRoleInfoTests.cs
> +	public void Property_WhenTryToGetUserRole_ShouldReturnCorrectUserRole()
Do not test Property if it doesn't contain any logic behind them.

2023-05-18 20:56 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Domain.Tests/UserBudgetAggregateTests.cs
> +		var instance = UserBudgetAggregate.Create(id, userId, budgetId, userRole);
change name to userBudget. instance is only for system under test.

2023-05-18 20:56 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Domain.Tests/UserBudgetAggregateTests.cs
> +	public void Property_WhenTryToGetUserIdProperty_ShouldReturnCorrectUserId()
do not test getter

2023-05-20 10:14 UTC, mateuszgiedzinski approved these changes

2023-05-20 23:06 UTC, Kepeczsz approved these changes

2023-05-20 23:37 UTC, merged