feature/patro23-43 - import and export budgets
intive/patronage2023-dotnet pull request #107
Opened 2023-05-18 11:55 UTC by LukaszWinowicz

https://tracker.intive.com/jira/browse/PATRO23-43

2023-05-18 14:48 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> +builder.Services.AddScoped<BudgetExportService>();
Use interfaces

2023-05-18 14:48 UTC, mateuszmuszynski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> ExportBudgets()
Use query

2023-05-18 14:48 UTC, mateuszmuszynski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> Import(IFormFile file)
Use command

2023-05-18 14:51 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/ExportingBudgets/GetBudgetsToExport.cs
> +		if (!isAdmin)
Please ask client whether it should be possible to export all budgets as admin.

2023-05-18 14:52 UTC, mateuszmuszynski commented on src/modules/budget/application/Data/BudgetExportService.cs
> +		BlobContainerClient containerClient = await this.dateHelperService.CreateBlobContainerIfNotExists(containerName);
We should move all blob code to some wrapper

2023-05-18 14:52 UTC, mateuszmuszynski commented on src/modules/budget/application/Data/BudgetImportService.cs
> +		BlobContainerClient containerClient = await this.dateHelperService.CreateBlobContainerIfNotExists(containerName);
Move blob code to wrapper class

2023-05-18 14:53 UTC, mateuszmuszynski commented on src/modules/budget/application/Data/BudgetImportService.cs
> +	public async Task<(List<string>? ErrorsList, string? Uri)> Import(IFormFile file)
use class/record instead of tuple

2023-05-18 17:55 UTC, DawidBski commented on src/shared/infrastructure/Commands/CommandBus.cs
> +using Intive.Patronage2023.Shared.Abstractions.Attributes;
We mentioned it during the stand-up. There were some unexpected changes in those two files that we didn't make. The only way to switch to another branch was to commit those changes.

2023-05-18 17:55 UTC, DawidBski commented on src/shared/infrastructure/Domain/Currency.cs
> +﻿namespace Intive.Patronage2023.Shared.Infrastructure.Domain;
We mentioned it during the stand-up. There were some unexpected changes in those two files that we didn't make. The only way to switch to another branch was to commit those changes.

2023-05-20 18:49 UTC, LukaszWinowicz commented on src/modules/budget/application/Data/BudgetExportService.cs
> +		BlobContainerClient containerClient = await this.dateHelperService.CreateBlobContainerIfNotExists(containerName);
We moved to BlobStorageService.

2023-05-20 18:52 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/ExportingBudgets/GetBudgetsToExport.cs
> +		if (!isAdmin)
We asked the client and he said it should be possible to export all budgets as admin.

2023-05-21 09:27 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateGetBudgetsToExportInfoMapper.cs
> +			Description = string.IsNullOrEmpty(entity.Description) ? string.Empty : entity.Description,
It can be simplified: `entity.Description ?? string.Empty`

2023-05-21 09:31 UTC, IzabelaPalubicka commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		////var data = new DataService();
Comment to be removed?

2023-05-21 09:36 UTC, IzabelaPalubicka commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		var query = new GetBudgetsToExport() { };
you can just write `new GetBudgetsToExport();`

2023-05-21 09:37 UTC, IzabelaPalubicka commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		////return new ImportResult { ErrorsList = errors, Uri = uri };
Comment to be deleted

2023-05-21 09:46 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateGetBudgetsToExportInfoMapper.cs
> +	public static GetBudgetTransferInfo Map(BudgetAggregate entity) =>
I prefer to use it as a BudgetAggregate extension method

2023-05-21 09:49 UTC, IzabelaPalubicka commented on src/modules/budget/application/Data/Service/DataService.cs
> +					string description = string.IsNullOrEmpty(budget.Description) ? string.Empty : budget.Description;
simplify to `budget.Description ?? string.Empty`

2023-05-22 07:33 UTC, mateuszmuszynski requested changes

2023-05-22 07:33 UTC, mateuszmuszynski commented on src/modules/budget/application/Data/Service/BlobStorageService.cs
> +		// Utworzenie polityki dostępu na podstawie których wygenerujemy SAS
Polish -> English

2023-05-22 07:33 UTC, mateuszmuszynski commented on src/modules/budget/application/Data/Service/CsvService.cs
> +		string localPath = "data"; ////src\api\app\data
Why you write files to local directory? Azure Web app storage is limited and we can easily exceed it.

2023-05-22 07:33 UTC, mateuszmuszynski commented on src/api/app/Program.cs
>  using Intive.Patronage2023.Api.Errors;
Please add unit/integration tests

2023-05-22 08:43 UTC, mateuszgiedzinski requested changes

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +/// Class DataService.
better summary

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +	// TODO: zrob z tego extension method
polish => english

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +	// TODO: zrob z tego extension method
or resolve TODO

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +		if (string.IsNullOrEmpty(budget.Name))
why you didn't used FluendValidation here?

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +		using (var csv = new CsvReader(new StreamReader(stream), csvConfig))
use method scoped using as you did with stream.

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +						errors.Add($"row: {rowNumber}| error: {result}");
use Select here and AddRange  instead of foreach loop.

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BlobStorageService.cs
> +		await blobClient.UploadAsync(filePath, true);
you can store data in stream and pass it to UploadAsync.

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +		using (var reader = new StreamReader(download.Content))
method scoped using to avoid indentation

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +						errors.Add($"row: {rowNumber}| error: {result}");
Or even better if you will use validation from fluent validation you can write extension to have errors.Add(validationResult.Errors, rowNumber);   But this is just suggestion.

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/BudgetImportService.cs
> +/// Class BudgetImportService.
better summary

2023-05-22 08:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Data/Service/CsvService.cs
> +/// CsvService.
better summary.

2023-05-22 19:12 UTC, LukaszWinowicz commented on src/shared/infrastructure/BaseRepository.cs
> +	public async Task Persist(List<T> aggregates)
We decided to remove this.

2023-05-23 21:20 UTC, DawidBski commented on src/modules/budget/application/Data/Service/CsvService.cs
> +		string localPath = "data"; ////src\api\app\data
Because we did not know about the consequences of saving files to a local directory. I changed the code, as suggested by Mateusz G, and we store the data in Memory Stream now.

2023-05-23 21:20 UTC, DawidBski commented on src/modules/budget/application/Data/Service/BlobStorageService.cs
> +		await blobClient.UploadAsync(filePath, true);
I've changed it as you suggest.

2023-05-23 22:00 UTC, DawidBski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +		if (string.IsNullOrEmpty(budget.Name))
It was prototype now it's changed for fluent validation.

2023-05-23 22:01 UTC, DawidBski commented on src/modules/budget/application/Data/Service/BudgetDataService.cs
> +						errors.Add($"row: {rowNumber}| error: {result}");
I hope my changes meets expectations of your suggestions.

2023-05-23 22:05 UTC, DawidBski commented on src/api/app/Program.cs
>  using Intive.Patronage2023.Api.Errors;
Łukasz promised me that he will do the tests in meantime of review.

2023-05-27 15:47 UTC, mateuszgiedzinski requested changes

2023-05-27 15:47 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBlobStorageService.cs
> +	Task<string> UploadToBlobStorage(GetBudgetTransferList budgetInfos, BlobContainerClient containerClient);
Do not mix budgets with blob storage implementation. Most probably you want pass here stream. Also passing BlobContainerClient is not ok. Service (component) should contain container client and taking care of creating or disposing client.

2023-05-27 15:47 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBlobStorageService.cs
> +	Task<BlobDownloadInfo> DownloadFromBlobStorage(string filename, BlobContainerClient containerClient);
Same here interface should be independent from BlobStorage external library.

2023-05-27 15:47 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/BlobStorageService.cs
> +	public async Task<string> UploadToBlobStorage(GetBudgetTransferList budgetInfos, BlobContainerClient containerClient)
Class break single responsibility principle. It manages blob and manages saving budgets to blob. In my opinion we should split those responsibilities and have service that manages blob.

2023-05-27 15:47 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/ICsvBudgetService.cs
> +	public void WriteBudgetsToMemoryStream(GetBudgetTransferList budgets, CsvWriter csv);
Csv service should be generic. and placed in infastructure layer.

2023-05-28 12:19 UTC, pzajaczkowski requested changes

2023-05-28 12:19 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/ImportingBudgets/GetBudgetsName.cs
> +		return entity is null ? BudgetAggregateGetBudgetsNameInfoMapper.Map(null) : BudgetAggregateGetBudgetsNameInfoMapper.Map(entity);
You are checking if entity is null and then proceed to pass null anyway.
In this scenario u could simply
`return BudgetAggregateGetBudgetsNameInfoMapper.Map(entity);`
But is this mapper really needed? It only calls ctor. Imo it can be removed entirely.

2023-05-28 12:19 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateGetBudgetsNameInfoMapper.cs
Mapper not needed imo

2023-05-28 12:19 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Shared/Services/CsvBudgetService.cs
Could be also made with generic type (ienumrable?), so it can be used in transactions import. Correct me if i am wrong

2023-05-28 20:28 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/ImportingBudgets/GetBudgetsName.cs
> +		return entity is null ? BudgetAggregateGetBudgetsNameInfoMapper.Map(null) : BudgetAggregateGetBudgetsNameInfoMapper.Map(entity);
You are right, the mapper is not needed, it has been removed.

2023-05-28 20:31 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/Shared/Services/BlobStorageService.cs
> +public class BlobStorageService : IBlobStorageService
Moved BlobStorageService to Share.Infrastructure and IBlobStorageService to Shared.Abstractions

2023-05-28 20:33 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/Shared/Services/CsvBudgetService.cs
Moved CsvService to Share.Infrastructure and ICsvService to Shared.Abstractions and made to generic type.

2023-05-28 20:33 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/Shared/Services/ICsvBudgetService.cs
> +	public void WriteBudgetsToMemoryStream(GetBudgetTransferList budgets, CsvWriter csv);
Moved CsvService to Share.Infrastructure and ICsvService to Shared.Abstractions and made to generic type.

2023-05-28 20:34 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/Shared/Services/IBlobStorageService.cs
> +	Task<string> UploadToBlobStorage(GetBudgetTransferList budgetInfos, BlobContainerClient containerClient);
fix to UploadToBlobStorage(Stream stream, string filename).

2023-05-28 20:35 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/Shared/Services/IBlobStorageService.cs
> +	Task<BlobDownloadInfo> DownloadFromBlobStorage(string filename, BlobContainerClient containerClient);
fix to Task<BlobDownloadInfo> DownloadFromBlobStorage(string filename)

2023-05-29 09:20 UTC, pzajaczkowski approved these changes

2023-05-29 09:20 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Shared/GetBudgetTransferList.cs
> +/// Create Budget command.
summary not changed

2023-05-29 09:20 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Shared/GetBudgetTransferInfo.cs
> +/// Create Budget command.
summary not changed

2023-05-29 18:21 UTC, LukaszWinowicz commented on src/api/app/Program.cs
> +builder.Services.AddScoped<IBlobStorageService, BlobStorageService>();
created ImportExportModule.

2023-05-30 07:13 UTC, mateuszmuszynski approved these changes

2023-05-30 10:55 UTC, mateuszgiedzinski requested changes

2023-05-30 10:55 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[HttpGet("export")]
Swagger documentation is missing.

2023-05-30 10:55 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> ExportBudgets()
Inconsistent method names for export and import. One is ExportBudgets and second one is Import.

2023-05-30 21:41 UTC, mateuszgiedzinski approved these changes

2023-05-31 05:13 UTC, merged