feature/PATRO23-340 - add hangfire background job
intive/patronage2023-dotnet pull request #112
Opened 2023-05-19 15:36 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-340

2023-05-20 10:02 UTC, mateuszgiedzinski requested changes

2023-05-20 10:02 UTC, mateuszgiedzinski commented on src/api/app/Filters/DashboardAuthorizationFilter.cs
> +			Console.WriteLine(e);
use logger instead.

2023-05-20 10:02 UTC, mateuszgiedzinski commented on src/api/app/Configuration/HangfireConfiguration.cs
> +			Authorization = new[] { new DashboardAuthorizationFilter() },
inject dashboard authorization filter

2023-05-20 23:05 UTC, Kepeczsz approved these changes

2023-05-21 10:17 UTC, KlaudiaGajocha approved these changes

2023-05-22 09:04 UTC, mateuszgiedzinski requested changes

2023-05-22 09:04 UTC, mateuszgiedzinski commented on src/api/app/appsettings.Development.json
> +		"HangfireConnection": "Server=db;Database=Hangfire;User=SA; Password=S3cur3P@ssW0rd!; TrustServerCertificate=true; Integrated Security=false"
why not localhost,1433?

2023-05-22 09:04 UTC, mateuszgiedzinski commented on src/modules/example/api/Controllers/ExampleController.cs
> +			BackgroundJob.Enqueue(() => Console.WriteLine("Sent From The Background Task"));
I suggest not to use Console directly.

2023-05-22 09:04 UTC, mateuszgiedzinski commented on src/api/app/Configuration/HangfireConfiguration.cs
> +		BackgroundJob.Schedule(() => Console.WriteLine("Schedule Job"), TimeSpan.FromDays(1));
I suggest not use Console directly.

2023-05-22 17:43 UTC, DawidBski commented on src/api/app/appsettings.Development.json
> +		"HangfireConnection": "Server=db;Database=Hangfire;User=SA; Password=S3cur3P@ssW0rd!; TrustServerCertificate=true; Integrated Security=false"
Because I Created Database in DockerDb. I tested it and it only working that way.

2023-05-23 14:57 UTC, mateuszmuszynski approved these changes

2023-05-24 11:20 UTC, mateuszgiedzinski approved these changes

2023-05-24 11:23 UTC, merged