feature/PATRO23-35 - add isFavourite flag
intive/patronage2023-dotnet pull request #113
Opened 2023-05-20 21:32 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-35

2023-05-20 22:39 UTC, Kepeczsz commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateBudgetInfoMapper.cs
typo "fourite"

2023-05-20 22:39 UTC, Kepeczsz commented on src/modules/budget/contracts/Events/UserBudgetFavouriteUpdatedDomainEvent.cs
NewIsFavourite doesn't feel right for me, maybe something like IsNewBudgetFavourite, also summary could be more detailed.

2023-05-20 23:28 UTC, DawidBski approved these changes

2023-05-21 10:13 UTC, KlaudiaGajocha approved these changes

2023-05-21 10:32 UTC, Kepeczsz approved these changes

2023-05-21 13:41 UTC, LukaszWinowicz approved these changes

2023-05-22 07:14 UTC, mateuszmuszynski requested changes

2023-05-22 07:14 UTC, mateuszmuszynski commented on src/modules/budget/application/EventHandlers/UserBudgetFavouriteUpdatedDomianEventHandler.cs
> +public class UserBudgetFavouriteUpdatedDomianEventHandler : IDomainEventHandler<UserBudgetFavouriteUpdatedDomainEvent>
typo, **Domian**EventHandler

2023-05-22 07:14 UTC, mateuszmuszynski commented on src/modules/budget/contracts/Events/UserBudgetFavouriteUpdatedDomainEvent.cs
> +	public bool IsNewBudgetFavourite { get; set; }
Imo "New" part is unnecessary.

2023-05-22 07:14 UTC, mateuszmuszynski commented on src/modules/budget/api/BudgetModule.cs
>  using Intive.Patronage2023.Modules.Budget.Application.Budget.EditingBudget;
Add tests (applies to all changes, not this file)

2023-05-22 08:14 UTC, IzabelaPalubicka commented on src/modules/budget/api/BudgetModule.cs
>  using Intive.Patronage2023.Modules.Budget.Application.Budget.EditingBudget;
We discussed that tests will be added in another task https://tracker.intive.com/jira/browse/PATRO23-346

2023-05-22 08:55 UTC, mateuszgiedzinski approved these changes

2023-05-22 08:56 UTC, mateuszmuszynski approved these changes

2023-05-22 08:57 UTC, merged