feature/PATRO23-339 add email service to send emails
intive/patronage2023-dotnet pull request #114
Opened 2023-05-21 18:29 UTC by a-lipert

WIP - integration tests to be added.

2023-05-22 07:21 UTC, mateuszmuszynski requested changes

2023-05-22 07:21 UTC, mateuszmuszynski commented on src/shared/infrastructure/Email/EmailService.cs
> +			throw new ArgumentNullException();
Include property name in the exception.
You can also try new syntax for such checks: ArgumentNullException.ThrowIfNull();

2023-05-22 07:21 UTC, mateuszmuszynski commented on src/shared/infrastructure/SharedModule.cs
>  		return services;
Implementation looks okay, waiting for tests ;)

2023-05-22 08:59 UTC, mateuszgiedzinski requested changes

2023-05-22 08:59 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Email/EmailService.cs
> +		if (emailMessage is null || emailMessage.SendFromAddress is null || emailMessage.SendToAddresses is null)
I think you can split this and validate each object separately

2023-05-22 08:59 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Email/EmailService.cs
> +			throw new ArgumentNullException();
Please think how you can pass name of the null argument without using raw string value.

2023-05-29 06:35 UTC, mateuszmuszynski requested changes

2023-05-29 06:35 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/EmailSendingTests.cs
> +		Assert.Null(exception);
Use fluent assertions

2023-05-29 06:35 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/EmailSendingTests.cs
> +		Assert.Null(exception);
Can we check whether email has been delivered on smtp server side?

2023-05-31 14:40 UTC, a-lipert commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/EmailSendingTests.cs
> +		Assert.Null(exception);
I didn't find any way to do it since this service has only a method to send emails. I tested it manually though and it worked.

2023-05-31 23:32 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/EmailSendingTests.cs
> +		Assert.Null(exception);
It could be possible with adding an event handler to smtp client but it will break our interface so I will leave it as it is. We can't receive any mails from smtp4dev.  It could be done by normal email box but we've chosen smtp4dev so I will resolve that issue.

2023-06-01 00:47 UTC, mateuszgiedzinski requested changes

2023-06-01 00:47 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/AbstractIntegrationTests.cs
> +	public class DatabaseDefinitionTestFixtureCollection : ICollectionFixture<MsSqlTests>
Because of some not known by me rule you need to specify this also in Budget integration tests project. ( I have no idea why) It's look like each assembly is tested separately

2023-06-01 00:47 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/SmtpServerFixture.cs
> +		.WithPortBinding(Port, 25)
You have const Port maybe use it twice?

2023-06-01 00:48 UTC, mateuszgiedzinski requested changes

2023-06-01 00:48 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/EmailSendingTests.cs
> +/// TESTS!
Maybe something more meaningful like Class that contains integration tests of <see cref="IEmailService">

2023-06-01 23:24 UTC, mateuszgiedzinski approved these changes

2023-06-02 06:50 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/Email/EmailSendingTests.cs
> +		Assert.Null(exception);
I think you should still be able to retrieve list of delivered messages by calling smtp4dev API.

2023-06-02 08:27 UTC, Kepeczsz approved these changes

2023-06-02 09:07 UTC, merged