[PATRO23-299] Hotfix asked by fe
intive/patronage2023-dotnet pull request #115
Opened 2023-05-22 15:04 UTC by Kepeczsz

I had conversation today with Bartek Kędziora, that if they make " one day budget", it doesn't work, so i have changed that, also in patro23-299 i forget the case where  list of transaction is empty, so i added if statment, which checks that.
![image](https://github.com/intive/patronage2023-dotnet/assets/52294433/68c03312-4b64-46d0-b020-323c34c6801c)
![image](https://github.com/intive/patronage2023-dotnet/assets/52294433/814108f4-0738-4348-bdac-d6ab3d1d7e13)

2023-05-22 15:11 UTC, IzabelaPalubicka approved these changes

2023-05-22 15:13 UTC, pzajaczkowski approved these changes

2023-05-22 15:41 UTC, mateuszgiedzinski requested changes

2023-05-22 15:44 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +			startDate = command.Period.StartDate;
If statement isn't needed.

2023-05-22 23:22 UTC, mateuszgiedzinski requested changes

2023-05-22 23:22 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		for (int i = 0; i < budgetTransactionValues.Count; i++)
In my opinion this is invalid. Your first Item at index 0  - your last item should gave you periodValue which is sum of transaction within this period. but you override first value after adding transaction. So first Item will be incorrect.

2023-05-24 11:18 UTC, mateuszgiedzinski requested changes

2023-05-24 11:18 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		decimal trendValue = budgetTransactionValues[0].Value > 0 ? (budgetTransactionValues.Last().Value - budgetTransactionValues[0].Value) / budgetTransactionValues[0].Value * 100 : 0;
budgetValueAtStartDate instead first element of collection in my opinion.

2023-05-24 11:41 UTC, Kepeczsz commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		decimal trendValue = budgetTransactionValues[0].Value > 0 ? (budgetTransactionValues.Last().Value - budgetTransactionValues[0].Value) / budgetTransactionValues[0].Value * 100 : 0;
Not really, because  there are a cases, where budget value at start date isn't added, ( it is added only if first element of the collection has different date than query.startDate), maybe i should change a name variable instead

2023-05-25 20:11 UTC, mateuszgiedzinski requested changes

2023-05-25 20:11 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		decimal trendValue = budgetTransactionValues[0].Value > 0 ? (budgetTransactionValues.Last().Value - budgetValueAtStartDate) / budgetValueAtStartDate * 100 : 0;
It shouldn't be 0. Is should be  null or sth like that. 0 means that value didn't change.

2023-05-25 20:52 UTC, mateuszgiedzinski approved these changes

2023-05-25 21:12 UTC, merged