Feature/patro23 230 add transaction attachment
intive/patronage2023-dotnet pull request #121
Opened 2023-05-27 21:15 UTC by AlanP22

https://tracker.intive.com/jira/browse/PATRO23-230

2023-05-28 12:41 UTC, pzajaczkowski requested changes

2023-05-28 12:41 UTC, pzajaczkowski commented on src/api/app/Program.cs
> +builder.Services.AddScoped<BudgetTransactionRepository>();
Registration covered by line 73.

2023-05-28 12:41 UTC, pzajaczkowski commented on src/modules/budget/api/BudgetModule.cs
> +		services.AddScoped<IBlobStorageService, BlobStorageService>();
Łukasz and Dawid are registering this service in program.cs maybe you should update your branch again.

2023-05-28 12:41 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		if (transactionId == Guid.Empty)
You can validate it inside validator. See edit budget or other endpoints with id from route.

2023-05-28 12:41 UTC, pzajaczkowski commented on src/modules/budget/domain/BudgetTransactionAggregate.cs
> +	public void AddAttachment(string attachmentUrl)
Some logic that prevents adding attachment if there is already one? Or we replace attachment?

2023-05-30 04:55 UTC, LukaszWinowicz commented on src/modules/budget/application/Data/BlobStorageService.cs
> +public class BlobStorageService : IBlobStorageService
You should move BlobStorageService to Shared.Infrastructure.

2023-05-30 04:55 UTC, LukaszWinowicz commented on src/modules/budget/application/Data/IBlobStorageService.cs
> +public interface IBlobStorageService
You should move IBlobStorageService to Shared.Abstractions.

2023-05-30 18:42 UTC, AlanP22 commented on src/api/app/Program.cs
> +builder.Services.AddScoped<BudgetTransactionRepository>();
I know, but without this I get following error:

> 
2023-05-25 23:25:00 Unhandled exception. System.AggregateException: Some services are Unable to resolve service for type 'Intive.Patronage2023.Modules.Budget.Infrastructure.Domain.BudgetTransactionRepository' while attempting to activate 'Intive.Patronage2023.Modules.Budget.Application.Budget.AddingBudgetTransactionAttachment.HandleAddingBudgetTransactionAttachment'.)

2023-05-30 18:43 UTC, AlanP22 commented on src/modules/budget/api/BudgetModule.cs
> +		services.AddScoped<IBlobStorageService, BlobStorageService>();
For now I'm using my own service for blob storage, it was easier than merging. I will merge with their changes when everything is finished

2023-06-02 12:20 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// Throws an AppException if there are validation errors.</returns>
You can add here produces response type with status code.

2023-06-02 12:20 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +
I think you should add authorization here.
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/360581fb-b824-4051-bd22-3feed72e1d85)

2023-06-02 12:20 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[HttpPost("{transactionId:guid}/transaction/attachment")]
Its not valid path for this endpoint. It should stat with budgetId:guid.

2023-06-02 12:20 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[HttpGet("{transactionId}/transaction/getAttachment)")]
path with budgetId and authorization should be added here

2023-06-02 12:20 UTC, DawidBski commented on src/modules/budget/application/Budget/AddingBudgetTransactionAttachment/AddBudgetTransactionAttachment.cs
> +	/// Constructor.
Standard text is enough.

2023-06-05 22:58 UTC, mateuszgiedzinski requested changes

2023-06-08 19:49 UTC, pzajaczkowski requested changes

2023-06-08 19:49 UTC, pzajaczkowski commented on src/modules/budget/application/Intive.Patronage2023.Modules.Budget.Application.csproj
> +    <ProjectReference Include="..\..\user\application\Intive.Patronage2023.Modules.User.Application.csproj" />
same reference twice:

- modules.user.application
- modules.user.infrastructure

2023-06-09 06:20 UTC, mateuszmuszynski requested changes

2023-06-09 06:20 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/AddingBudgetTransactionAttachment/AddBudgetTransactionAttachment.cs
> +		if (transaction.AttachmentUrl != null)
Move validation to validator

2023-06-09 06:20 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/AddingBudgetTransactionAttachment/AddBudgetTransactionAttachment.cs
> +		string fileUrlString = await this.blobStorageService.GenerateLinkToDownload(attachmentFile.FileName);
You should store reference to blob in database, not link with Shared Access Signature. It will expire after an hour.

2023-06-09 06:20 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/AddingBudgetTransactionAttachment/AddBudgetTransactionAttachmentValidator.cs
> +		this.RuleFor(command => command.File)
Add error codes

2023-06-09 13:43 UTC, Kepeczsz approved these changes

2023-06-09 13:53 UTC, mateuszmuszynski approved these changes

2023-06-09 13:54 UTC, mateuszgiedzinski approved these changes

2023-06-09 13:56 UTC, merged