feature/PATRO23-346 - add favourite budget tests
intive/patronage2023-dotnet pull request #123
Opened 2023-05-29 16:03 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-346

2023-05-30 07:17 UTC, mateuszmuszynski requested changes

2023-05-30 07:17 UTC, mateuszmuszynski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/UserBudget/UpdateUserBudgetFavouriteCommandHandlerTests.cs
> +		var contextOptions = new DbContextOptionsBuilder<BudgetDbContext>()
Unit tests shouldn't use external resources like database.

2023-06-01 23:26 UTC, mateuszgiedzinski approved these changes

2023-06-02 06:51 UTC, mateuszmuszynski approved these changes

2023-06-02 08:29 UTC, Kepeczsz approved these changes

2023-06-02 09:01 UTC, merged