Feature/PATRO23-372 Report
intive/patronage2023-dotnet pull request #125
Opened 2023-05-30 22:00 UTC by Kepeczsz

https://tracker.intive.com/jira/browse/PATRO23-372

2023-05-31 12:40 UTC, mateuszmuszynski requested changes

2023-05-31 12:40 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetsReport/GetBudgetsReport.cs
> +		foreach (var budgetId in budgetsList)
Imo there's no need to iterate over all budgets. We can just build a list with all budgets' transactions

2023-05-31 17:48 UTC, pzajaczkowski approved these changes

2023-05-31 23:40 UTC, mateuszgiedzinski approved these changes

2023-06-01 06:32 UTC, mateuszmuszynski approved these changes

2023-06-01 06:46 UTC, merged