Feature/patro23 313 budget details sorting in columns
intive/patronage2023-dotnet pull request #126
Opened 2023-05-31 12:32 UTC by PiotrekkP

https://tracker.intive.com/jira/browse/PATRO23-313

2023-05-31 16:56 UTC, AlanP22 commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			.ToList();
Shouldn't ToList() be done asynchronously as it was before?

2023-05-31 17:35 UTC, pzajaczkowski requested changes

2023-05-31 17:35 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +			SortDescriptors = request.SortDescriptors,
Update endpoint remarks (swagger example)

2023-05-31 17:35 UTC, pzajaczkowski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtensions.cs
> +			{ (int)TransactionsSortingEnum.Name, t => t.Name },
Since you are using enums, u can probably validate descriptors in validators

2023-05-31 17:35 UTC, pzajaczkowski commented on src/modules/user/application/GettingUsers/UserInfoBase.cs
> +	public string UserName { get; set; } = null!;
You don't need username field. We are using email as username, so you can use email
![image](https://github.com/intive/patronage2023-dotnet/assets/82521883/76456da1-803d-4f54-b23e-e2bce21f7d5a)

2023-05-31 17:35 UTC, pzajaczkowski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtensions.cs
> +		budgetTransactionsOrdered = sortDescriptors[0].SortAscending ? budgetTransactionsOrdered.OrderBy(mapping[sortDescriptors[0].Column]) : budgetTransactionsOrdered.OrderByDescending(mapping[sortDescri
It's better to check if there are any elements in case of passing empty list. If there aren't you can do default ordering and return. When you pass empty sort descriptorss there is 500 code because of non existing [0] element.

2023-06-01 00:38 UTC, mateuszgiedzinski requested changes

2023-06-01 00:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtensions.cs
> +		var mapping = new Dictionary<int, Func<BudgetTransactionAggregate, object>>()
If we will find a way to do this using property name then method could be more less generic. Even without that we can move such dictionary to some place where it will be static readonly.

2023-06-05 22:57 UTC, mateuszgiedzinski requested changes

2023-06-05 22:57 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +			SortDescriptors = request.SortDescriptors,
Enum could be fine but it must be parsed from string not int.  But if we already use string I wouldn't want change. 
We could use dictonary like { nameof(Property), x=>x.Property }

2023-06-05 22:57 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			.ToList();
I have no problems to do that. Maybe you need await ToListAsync()

2023-06-05 22:57 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtensions.cs
> +		if (sortDescriptors.IsNullOrEmpty())
I mean order by is used before you check sortDescriptors.IsNullOrEmpty

2023-06-05 22:57 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtensions.cs
> +		var budgetTransactionsOrdered = budgetTransactions.AsEnumerable().OrderBy(t => 1);
You materialize data here which is wrong.

2023-06-08 15:02 UTC, mateuszgiedzinski approved these changes

2023-06-08 15:13 UTC, DawidBski approved these changes

2023-06-08 15:31 UTC, pzajaczkowski approved these changes
I'll approve so it's not blocked when you finish making changes if you decide to

2023-06-08 15:31 UTC, pzajaczkowski commented on src/shared/abstractions/Extensions/OrderedQueryableExtension.cs
> +			return source;
Is there any default sorting? Low on time so im fast reviewing xD

2023-06-08 15:31 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Shared/Services/BudgetTransactionDataService.cs
> +			var newBudgetTransaction = BudgetTransactionAggregate.Create(transactionId, transaction.BudgetId, transactionType, transaction.Name, transaction.Email, value, categoryType, budgetTransactionDate,
Here add current user email

2023-06-08 16:03 UTC, mateuszgiedzinski approved these changes

2023-06-08 16:03 UTC, mateuszgiedzinski commented on src/shared/abstractions/Extensions/OrderedQueryableExtension.cs
> +			return source;
By default it sorting in the same order as db saved rows.

2023-06-08 16:03 UTC, mateuszgiedzinski approved these changes

2023-06-08 16:08 UTC, merged