bug/PATRO23-380 invalid userId validation
intive/patronage2023-dotnet pull request #127
Opened 2023-05-31 18:43 UTC by Kepeczsz

https://tracker.intive.com/jira/browse/PATRO23-380

2023-05-31 18:49 UTC, pzajaczkowski approved these changes

2023-05-31 21:59 UTC, IzabelaPalubicka approved these changes

2023-06-01 00:43 UTC, mateuszgiedzinski requested changes

2023-06-01 00:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudgetValidator.cs
> +			throw new AppException();
Maybe enhance excetpion with some message.

2023-06-01 00:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetDetails/GetBudgetDetailsValidator.cs
> +			throw new AppException();
Maybe enhance excetpion with some message.

2023-06-01 23:32 UTC, mateuszgiedzinski approved these changes

2023-06-02 08:18 UTC, merged