featrue/PATRO23-350 - add new transaction categories to budget
intive/patronage2023-dotnet pull request #128
Opened 2023-06-01 19:21 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-350

2023-06-02 11:50 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/AddingTransactionCategory/AddCategoryValidator.cs
> +	}
Should I add validation if category name exsists?

2023-06-03 17:03 UTC, IzabelaPalubicka commented on src/modules/budget/application/TransactionCategories/AddingTransactionCategory/AddCategoryValidator.cs
> +	}
If we do not support names that do not exist, then yes. We should predict that the user may accidentally or intentionally enter an incorrect value

2023-06-03 20:42 UTC, IzabelaPalubicka commented on src/modules/budget/application/TransactionCategories/DeletingTransactionCategory/DeleteTransactionCategory.cs
> +		await this.dbContext.SaveChangesAsync(cancellationToken);
You have to use the persist method to trigger handle this event

2023-06-04 16:04 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/DeletingTransactionCategory/DeleteTransactionCategory.cs
> +		await this.dbContext.SaveChangesAsync(cancellationToken);
Good point. Thanks ! <3

2023-06-04 22:28 UTC, mateuszgiedzinski requested changes

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetCategoryController.cs
> +	[ProducesResponseType(typeof(ErrorExample), StatusCodes.Status400BadRequest)]
Is it really ErrorExample response?

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetCategoryController.cs
> +			return this.Forbid();
403 ProducesResponseType attribute is missing.

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetCategoryController.cs
> +		return this.Ok(categoryId.Value);
shouldn't be created?

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetCategoryController.cs
> +		return this.Ok(budgetCategoryId);
I don't think we need to return any response here so NoContent could be returned.

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +	public string[]? CategoryTypes { get; init; }
I'm not sure about changing stronly typed value to string,

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtensions.cs
> +	public static IQueryable<BudgetTransactionAggregate> WithCategoryTypes(this IQueryable<BudgetTransactionAggregate> query, string[]? categoryTypes)
same I'm not sure about changing strongly typed value to string.

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/TransactionCategories/GettingTransactionCategories/GetTransactionCategories.cs
> +		var providers = new List<ICategoryProvider>
providers must be injected here.

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/TransactionCategories/GettingTransactionCategories/GetTransactionCategories.cs
> +		var providers = new List<ICategoryProvider>
There are two options to inject composite type. First is to create extension to add that functionality and override our injection. Second is to create factory method during registration. The first one is better. Let me share article with you. 
https://greatrexpectations.com/2018/11/07/composite-pattern-in-net-core-with-dependency-injection

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/contracts/Events/BudgetTransactionCreatedDomainEvent.cs
> +	public BudgetTransactionCreatedDomainEvent(TransactionId transactionId, BudgetId budgetId, TransactionType transactionType, string name, decimal value, string categoryType, DateTime transactionDate)
Wrap category type in value type.

2023-06-04 22:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/TransactionCategories/CategoryProviders/DatabaseCategoryProvider.cs
> +	public List<TransactionCategory> GetAll()
Categories are per budget so I suggest BudgetId as parameter and have GetForBudget(BudgetId budgetId) method.

2023-06-04 22:29 UTC, mateuszgiedzinski requested changes

2023-06-04 22:29 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Migrations/20230602175337_AddBudgetTransactionCategoryTable.cs
> +				IconName = table.Column<string>(type: "nvarchar(max)", nullable: false),
specify length of the columns.

2023-06-06 22:10 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/GettingTransactionCategories/GetTransactionCategories.cs
> +		var providers = new List<ICategoryProvider>
Thanks article was really helpful.

2023-06-07 00:41 UTC, pzajaczkowski requested changes
I have checked what i could check. Really complicated pull request. Probably missed manyy things

2023-06-07 00:41 UTC, pzajaczkowski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/BudgetTransactions/CreateBudgetTransactionValidatorTests.cs
Why did you move these validator tests from unit to integration? Those are still unit with mocks.

2023-06-07 00:41 UTC, pzajaczkowski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/BudgetTransactions/GetBudgetTransactionsValidatorTests.cs
Same here. Why moved?

2023-06-07 00:41 UTC, pzajaczkowski commented on src/modules/budget/application/TransactionCategories/DeletingTransactionCategory/DeleteTransactionCategoryValidator.cs
> +		var transactions = await this.dbContext.Transaction.Where(x => x.BudgetId == categoryData.BudgetId).ToListAsync(cancellationToken: cancellationToken);
unused variable transactions? line not needed

2023-06-07 00:41 UTC, pzajaczkowski commented on src/modules/budget/application/TransactionCategories/DeletingTransactionCategory/DeleteTransactionCategoryValidator.cs
> +		var categories = transactions.Where(x => x.CategoryType == category!.CategoryType);
same here for categories which are transactions, delete

2023-06-07 00:41 UTC, pzajaczkowski commented on src/modules/budget/application/TransactionCategories/AddingTransactionCategory/AddCategoryValidator.cs
> +		this.RuleFor(command => command.BudgetId).NotNull().NotEmpty().WithMessage("Budget ID is required.");
In validators `.NotEmpty()` checks for null, so there is no point in doing additional `.NotNull()`.

2023-06-07 00:41 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +		return Task.FromResult(categoryTypes.All(categoryType => categories.Any(category => category.Name == categoryType.CategoryName)));
You have to use `.FromResult()` because of forced `Task<>` return type by this categoryProvider? Or is it by choice xD?

2023-06-07 06:44 UTC, mateuszmuszynski requested changes

2023-06-08 05:48 UTC, DawidBski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +		return Task.FromResult(categoryTypes.All(categoryType => categories.Any(category => category.Name == categoryType.CategoryName)));
According to Mateusz G's suggestion and the article sent by him, it was possible to change the way categories are retrieved from all ICategoryProvider implementations. Previously, it was an asynchronous method that used the DbContext, hence the remaining remnants like MustAsync, etc.

2023-06-08 05:53 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/AddingTransactionCategory/AddCategoryValidator.cs
> +			.MustAsync(async (x, cancellation) => !await this.CategoryNameExists(x.BudgetId, x.CategoryType.CategoryName, cancellation))
It was already late, so it wasn't fixed immediately. I probably should have changed that pull request to a draft. The plan was to review everything from the beginning and correct such obvious errors.

2023-06-08 05:53 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/AddingTransactionCategory/AddCategoryValidator.cs
> +		this.RuleFor(command => command.BudgetId).NotNull().NotEmpty().WithMessage("Budget ID is required.");
Good to know thanks.

2023-06-08 05:59 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/DeletingTransactionCategory/DeleteTransactionCategoryValidator.cs
> +		var transactions = await this.dbContext.Transaction.Where(x => x.BudgetId == categoryData.BudgetId).ToListAsync(cancellationToken: cancellationToken);
I have no idea how this ended up here xD

2023-06-08 05:59 UTC, DawidBski commented on src/modules/budget/application/TransactionCategories/DeletingTransactionCategory/DeleteTransactionCategoryValidator.cs
> +		var categories = transactions.Where(x => x.CategoryType == category!.CategoryType);
I have no idea how this ended up here xD

2023-06-08 06:15 UTC, DawidBski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/BudgetTransactions/CreateBudgetTransactionValidatorTests.cs
Since categories are now also being retrieved from the database, the validator tests went crazy :). I can't remember my thought process when I made that change. I need to think about how to modify them to work correctly. However, my priority now is to submit the task so that the frontend has time to make their changes as well.

2023-06-08 21:06 UTC, mateuszgiedzinski approved these changes
Looks good. It's kind of big PR so maybe @mateuszgiedzinski  please check it additionally.

2023-06-08 21:11 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +		return Task.FromResult(categoryTypes.All(categoryType => categories.Any(category => category.Name == categoryType.CategoryName)));
Actually @mateuszmuszynski  have right. This method could return bool because it's not calling async method. If we use Must then instead MustAsync everything will work

2023-06-08 21:13 UTC, mateuszgiedzinski approved these changes

2023-06-09 06:13 UTC, mateuszmuszynski approved these changes

2023-06-09 07:23 UTC, merged