Bugfix/patro23 43 fix validation in import/export budgets
intive/patronage2023-dotnet pull request #129
Opened 2023-06-01 20:37 UTC by LukaszWinowicz

https://tracker.intive.com/jira/browse/PATRO23-390

2023-06-03 17:50 UTC, IzabelaPalubicka approved these changes

2023-06-04 13:48 UTC, pzajaczkowski approved these changes

2023-06-04 20:14 UTC, pzajaczkowski approved these changes

2023-06-04 20:14 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/ExportingBudgets/ExportResult.cs
Move to shared in budgets please, will be used in exporting transactions aswell

2023-06-04 20:57 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/Shared/Services/BudgetImportService.cs
> +		if (budgetInfos.Result.BudgetsErrorsList.Count == 0)
if(!budgetInfos.Result.BudgetsErrorsList.Any())
```suggestion
		if (budgetInfos.Result.BudgetsErrorsList.Count == 0)
```

2023-06-04 21:01 UTC, IzabelaPalubicka approved these changes

2023-06-04 21:44 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		if (getImportResult.ImportResult.Uri == "All budgets were saved.")
Under Shared.Infrastructure we could have Exporting and Importing namespaces to share that across whole solution.

2023-06-04 21:56 UTC, mateuszgiedzinski requested changes

2023-06-04 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
>  	/// <returns>A string containing the URI to Azure Blob Storage of the exported file.</returns>
First of all it should be fixed under new bug not closed story.

2023-06-04 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/BudgetDataService.cs
> +	/// <param name="csvService">ICsvService.</param>
Never write that param documentation.  You can always find something better than string with parameter type.

2023-06-04 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/BudgetDataService.cs
> +	/// <param name="budgetsNames">The existing budgets' names used for checking whether the new budget's name already exists in the database.</param>
typo budgets' => budget's

2023-06-04 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetDataService.cs
> +	/// <param name="budgetsNames">The existing budgets' names used for checking whether the new budget's name already exists in the database.</param>
typo

2023-06-04 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetDataService.cs
> +	Task<BudgetAggregateList> ConvertBudgetsToBudgetAggregate(IEnumerable<GetBudgetTransferInfo> budgetsToImport);
MapFrom

2023-06-04 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/ExportingBudgets/ExportResult.cs
Under Shared.Infrastructure we could have Exporting and Importing namespaces to share that across whole solution.

2023-06-05 17:45 UTC, LukaszWinowicz commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		if (getImportResult.ImportResult.Uri == "All budgets were saved.")
You have right, I removed this.

2023-06-05 22:34 UTC, mateuszgiedzinski approved these changes

2023-06-06 07:23 UTC, merged