Feature/PATRO23-351 - export expenses and incomes from csv file
intive/patronage2023-dotnet pull request #133
Opened 2023-06-02 14:55 UTC by pzajaczkowski

https://tracker.intive.com/jira/browse/PATRO23-351
not tested yet

2023-06-04 21:09 UTC, mateuszgiedzinski commented on stylecop.json
> -
Nice catch

2023-06-04 21:38 UTC, mateuszgiedzinski requested changes

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/ValidationResultExtensions.cs
> -namespace Intive.Patronage2023.Modules.Budget.Application.Budget.ImportingBudgets;
this is something that could be moved to shared project.

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetTransactionImportService.cs
> +/// IBudgetTransactionImportService interface defines a contract for services that handle the import of budget Transaction data.
Transaction => transaction

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetTransactionImportService.cs
> +	/// Imports budget Transaction data from the provided file.
Transaction => transaction

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetTransactionImportService.cs
> +	Task<GetImportBudgetTransactionsResult> Import(BudgetId budgetId, IFormFile file);
For now it's ok but ideally we should have stream here to avoid reference to AspNet

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetTransactionExportService.cs
> +	/// <param name="transactions">GetBudgetTransactionListToExport.</param>
You can describe what you have in this object. For example collection of transaction to export.

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetTransactionExportService.cs
> +	/// Exports the budget transactions to a CSV file and uploads it to Azure Blob Storage.
To be honest your contract doesn't specify where you upload your data. I suggest change this description a little bit.

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Shared/Services/IBudgetTransactionDataService.cs
> +	Task<BudgetTransactionAggregateList> ConvertBudgetTransactionsFromCsvToBudgetTransactionAggregate(IEnumerable<GetBudgetTransactionImportInfo> budgetTransactionsToImport, CsvConfiguration csvConfig);
MapFrom maybe ?

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/ImportingBudgets/GetImportBudgetsResult.cs
> +public record GetImportBudgetsResult(BudgetAggregateList BudgetAggregateList, ImportResult ImportResult);
Could be generic class. GetImportResult<T>(T itemsList, ImportResult importResult);

2023-06-04 21:38 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/ImportingBudgetTransactions/GetBudgetTransactionImportInfoValidator.cs
> +		return await this.budgetDbContext.Budget.FindAsync(budgetId) != null;
I've always suggest Any. In some cases this will be faster but only in case when entity will be cached.

2023-06-05 13:53 UTC, pzajaczkowski commented on stylecop.json
> -
Yeah, my maids are great XD

2023-06-06 18:53 UTC, mateuszgiedzinski approved these changes

2023-06-06 19:05 UTC, mateuszmuszynski approved these changes

2023-06-06 21:28 UTC, Slashu approved these changes
Everything seems fine

2023-06-06 22:25 UTC, DawidBski requested changes

2023-06-06 22:25 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[ProducesResponseType(typeof(ErrorExample), StatusCodes.Status401Unauthorized)]
I think this is not ErrorExample Response Type try void instead.

2023-06-06 22:25 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[ProducesResponseType(typeof(ErrorExample), StatusCodes.Status401Unauthorized)]
same

2023-06-06 23:11 UTC, DawidBski approved these changes

2023-06-06 23:27 UTC, merged