Feature/PATRO23-373 Share budget improvment
intive/patronage2023-dotnet pull request #134
Opened 2023-06-03 11:28 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-373

2023-06-03 15:06 UTC, Kepeczsz approved these changes

2023-06-04 21:07 UTC, mateuszgiedzinski requested changes

2023-06-04 21:07 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/DeleteUserBudget/DeleteUserBudgetList.cs
> +			await this.userBudgetRepository.RemovePersist(userBudget);
Remove should be enough.

2023-06-04 21:07 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/DeleteUserBudget/DeleteUserBudgetList.cs
> +		var userBudgetIds = await this.budgetDbContext.UserBudget
I'm not sure about using DbContext in commands We should use queries and repositories only.

2023-06-04 21:07 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/ShareBudget/ShareBudget.cs
> +		this.budgetDbContext = budgetDbContext;
I'm not sure about using DbContext in commands We should use queries and repositories only.

2023-06-05 22:30 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/DeleteUserBudget/DeleteUserBudgetList.cs
> +		var userBudgetIds = await this.budgetDbContext.UserBudget
I confirmed with @mateuszmuszynski  that this should come from query handler

2023-06-08 10:04 UTC, mateuszgiedzinski requested changes

2023-06-08 10:04 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/AddingUserBudget/AddUserBudgetListValidator.cs
> +			.Custom(this.IsUserIdDupliacted)
please assign some error code for your validation rule.

2023-06-08 10:40 UTC, pzajaczkowski approved these changes

2023-06-08 10:40 UTC, pzajaczkowski commented on src/modules/budget/application/UserBudgets/GettingUserBudget/GetUserBudgetListValidator.cs
> +			.NotNull()
`.NotEmpty()` covers null case, not null not needed

2023-06-08 13:18 UTC, mateuszgiedzinski approved these changes

2023-06-08 13:19 UTC, merged