feature/PATRO23-370-refresh-token
intive/patronage2023-dotnet pull request #135
Opened 2023-06-03 12:34 UTC by Kepeczsz

https://tracker.intive.com/jira/browse/PATRO23-370

2023-06-03 13:16 UTC, IzabelaPalubicka commented on src/modules/user/application/RefreshingUserToken/RefreshUserToken.cs
> +public record AccesToken(string AccessToken);
typo  `AccessToken`

2023-06-03 13:50 UTC, IzabelaPalubicka approved these changes

2023-06-04 14:13 UTC, AlanP22 approved these changes

2023-06-04 20:50 UTC, mateuszgiedzinski requested changes

2023-06-04 20:50 UTC, mateuszgiedzinski commented on src/modules/user/application/RefreshingUserToken/RefreshUserToken.cs
> +		if (accessToken.ValidTo.AddMinutes(-1) <= DateTime.UtcNow)
Don't use DateTime.UtcNow directly. Use time service instead. Also you can move that logic to extension and change this to accessToken.IsExpired() extension method.

2023-06-04 20:50 UTC, mateuszgiedzinski commented on src/modules/user/application/RefreshingUserToken/RefreshUserToken.cs
> +		if (refreshToken.ValidTo < DateTime.UtcNow)
You can move that logic to extension and change this to refreshToken.IsExpired() using  extension method.

2023-06-04 20:50 UTC, mateuszgiedzinski commented on src/modules/user/application/RefreshingUserToken/RefreshUserToken.cs
> +		if (accessToken.ValidTo.AddMinutes(-1) <= DateTime.UtcNow)
IsExpired can have some TimeSpan parameter by default set to 0 minutes but in this case can be -1.minutes. 
you can use that parameter as margin to check when token is treated as expired.

2023-06-04 20:52 UTC, mateuszgiedzinski requested changes

2023-06-04 20:52 UTC, mateuszgiedzinski commented on src/modules/user/api/Controllers/UserController.cs
> +		var reponse = await this.queryBus.Query<RefreshUserToken, AccessUserToken>(query);
I don't see any validation for input parrameters.

2023-06-05 22:28 UTC, mateuszgiedzinski approved these changes

2023-06-06 06:07 UTC, mateuszmuszynski approved these changes

2023-06-06 17:12 UTC, merged