[PATRO23-367] add validation codes to validators, add CustomValidatio…
intive/patronage2023-dotnet pull request #136
Opened 2023-06-05 06:32 UTC by Slashu

(https://tracker.intive.com/jira/browse/PATRO23-367)

2023-06-05 09:16 UTC, mateuszgiedzinski requested changes

2023-06-05 09:16 UTC, mateuszgiedzinski commented on src/modules/user/api/Controllers/UserController.cs
> +	[SwaggerResponse(400, "errorcode")]
Should be ProducesResponseType.

2023-06-05 21:43 UTC, Slashu commented on src/modules/user/api/Controllers/UserController.cs
> +	[SwaggerResponse(400, "errorcode")]
done

2023-06-05 22:25 UTC, mateuszgiedzinski approved these changes

2023-06-06 06:46 UTC, pzajaczkowski approved these changes
I assume we are going to use CustomValidationResponse from now on in case of any errors, so maybe it's good idea to replace all return types in endpoints from ErrorExample to the CustomValidation one?

2023-06-06 09:47 UTC, merged