Feature/PATRO23-349 Export budget via mail
intive/patronage2023-dotnet pull request #141
Opened 2023-06-06 19:57 UTC by KlaudiaGajocha

User may export budget via mail

2023-06-07 12:36 UTC, mateuszgiedzinski requested changes

2023-06-08 17:25 UTC, Kepeczsz commented on src/modules/budget/infrastructure/Domain/BudgetController.cs
we have budgetController in .Modules.Budget.Api dont create new one.

2023-06-08 17:25 UTC, Kepeczsz commented on src/modules/budget/infrastructure/Domain/BudgetController.cs
also it is not valid, to pass List<budgets>, and app user, when  both can be taken from id

2023-06-08 17:25 UTC, Kepeczsz commented on src/modules/budget/infrastructure/Domain/BudgetSenderEmail.cs
we dont need blobStorageService;

2023-06-08 17:25 UTC, Kepeczsz commented on src/modules/budget/infrastructure/Domain/BudgetSenderEmail.cs
you dont have handler

2023-06-08 19:25 UTC, pzajaczkowski requested changes

2023-06-08 19:25 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Domain/BudgetController.cs
Move endpoints to budget controller in modules/budget/api, add produce response type attributes and response comments like in this endpoint

![image](https://github.com/intive/patronage2023-dotnet/assets/82521883/f75d29c4-5fb9-444a-8a1e-29c9608921c4)

Additionaly i suggest url to be [HttpGet("export-email")] or sth similar.

2023-06-08 19:25 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Domain/BudgetController.cs
> +		this.budgetSenderEmail.ExportAndSendBudgets(budgets, user);
Imo you should use GetBudgetsToExport query here to retrive budgets to export and then call your service.
Checkout ExportBudget endpoint for reference

2023-06-08 19:25 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Domain/BudgetSenderEmail.cs
> +		this.blobStorageService = blobStorageService;
Remove blobStorageService, not used.

2023-06-08 19:25 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Domain/BudgetSenderEmail.cs
> +		this.csvService = csvService;
If you will use GetBudgetsToExport query you will recieve type GetBudgetTransferInfo which is better to export than Aggregate since it does not include id and other not needed attributes and all members are string type

2023-06-08 19:25 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Intive.Patronage2023.Modules.Budget.Infrastructure.csproj
> +      <ProjectReference Include="..\..\user\domain\Intive.Patronage2023.Modules.User.Domain.csproj" />
Budget.Infrastructure shouldn't have reference to user module. Instead you should use IKeycloakService to retrieve user information and maybe create your own user class, similar to what Iza has done in get budget details.
 `var tasks = await Task.WhenAll(budgetUsers.Select(x => this.keycloakService.GetUserById(x.ToString(), cancellationToken)
			.ContinueWith(x => this.DeserializeResponse(x.Result, cancellationToken))).ToArray());`

2023-06-08 19:33 UTC, pzajaczkowski commented
Almost all of above changes are outdates because i left laptop when reviewing and when came back didn't refresh page xD.

2023-06-09 08:18 UTC, pzajaczkowski requested changes

2023-06-09 08:18 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// .
Add proper summary

2023-06-09 08:18 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// <returns>Returns Ok if email was sent.</returns>
Add <response code=""> comment for each possible code returned

2023-06-09 08:18 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// .
Same here, proper summary and response code comments

2023-06-09 08:18 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Intive.Patronage2023.Modules.Budget.Infrastructure.csproj
> +      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
Adding this reference is the only change in Budget.Infrastructure project. I think it can be safely removed.

2023-06-09 09:17 UTC, pzajaczkowski approved these changes

2023-06-09 12:36 UTC, mateuszgiedzinski approved these changes

2023-06-09 12:36 UTC, merged