Feature/patro23 48 mediat r as command query bus
intive/patronage2023-dotnet pull request #16
Opened 2023-03-19 21:30 UTC by AlanP22

PATRO23-48: Added command and query bus implementation.

2023-03-20 11:55 UTC, mateuszmuszynski requested changes

2023-03-20 11:55 UTC, mateuszmuszynski commented on src/shared/abstractions/Commands/CommandBus.cs
> +using System;
Abstractions project shouldn't contain actual implementation of command bus. Move `CommandBus` implementation to Infrastructure project

2023-03-20 11:55 UTC, mateuszmuszynski commented on src/shared/abstractions/Commands/ICommandBus.cs
> +	Task<object> Send<TCommand>(TCommand command)
Send method shouldn't return any data

2023-03-20 21:59 UTC, AlanP22 commented on src/shared/abstractions/Commands/ICommandBus.cs
> +	Task<object> Send<TCommand>(TCommand command)
@mateuszmuszynski Can it be asynchronous if it doesn't return any data? Is it even necessary?

2023-03-21 07:25 UTC, mateuszmuszynski commented on src/shared/abstractions/Commands/ICommandBus.cs
> +	Task<object> Send<TCommand>(TCommand command)
Let's leave it as asynchronous.

2023-03-21 07:45 UTC, mateuszmuszynski commented on src/shared/abstractions/Commands/ICommandBus.cs
> +	Task<object> Send<TCommand>(TCommand command)
Please also add an registration of Command/Query bus

2023-03-22 23:15 UTC, AlanP22 commented on src/shared/abstractions/Commands/ICommandBus.cs
> +	Task<object> Send<TCommand>(TCommand command)
Resolved in latest commits.

2023-03-23 08:41 UTC, mateuszmuszynski approved these changes

2023-03-23 10:19 UTC, IzabelaPalubicka requested changes

2023-03-23 10:19 UTC, IzabelaPalubicka commented on src/api/app/Program.cs
> +builder.Services.AddSingleton<QueryBus>();
This should be added with abstraction <ICommandBus, CommandBus>, but automatic registration is on dev,  so you don't need to add it at all. Automatic registration is set by default as scoped, so maybe you have to change life time atribute like here [https://github.com/intive/patronage2023-dotnet/blob/dev/src/modules/example/infrastructure/Domain/EventHandlers/ExampleCreatedDomainEventHandler.cs](url)

2023-03-23 22:23 UTC, AlanP22 commented on src/api/app/Program.cs
> +builder.Services.AddSingleton<QueryBus>();
Added Lifetime scoped attributes in latest commit.

2023-03-24 13:52 UTC, Kepeczsz approved these changes

2023-03-24 14:16 UTC, mateuszgiedzinski requested changes

2023-03-24 14:16 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Query/QueryBus.cs
> +				throw new ArgumentNullException();
Which argument is null? Argument Exceptions are dedicated for method parameters only.  Better to use InvalidOperationException or InvalidDataException

2023-03-24 14:17 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Query/QueryBus.cs
> +				throw new ArgumentNullException();
Also you can change var to object?.

2023-03-25 10:54 UTC, mateuszgiedzinski approved these changes
Can be merged. There is a problem with namespaces because we should use file scoped namespaces  to have one less indentiation.  (namespace Intive.Patronage2023.Shared.Infrastructure.Commands;)
But because this is blocker for some task I can approve it conditionally

2023-03-25 14:04 UTC, AlanP22 commented on src/shared/infrastructure/Query/QueryBus.cs
> +				throw new ArgumentNullException();
Done

2023-03-25 14:14 UTC, IzabelaPalubicka approved these changes

2023-03-25 14:24 UTC, merged