[PATRO23-54] Local docker development environment
intive/patronage2023-dotnet pull request #20
Opened 2023-03-20 17:59 UTC by DawidBski

2023-03-22 05:47 UTC, mateuszmuszynski requested changes

2023-03-22 05:47 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> +using (var scope = app.Services.CreateScope())
Automatic migrations were out of scope of this ticket. Please revert changes in this file.

2023-03-22 22:37 UTC, AlanP22 approved these changes

2023-03-23 11:30 UTC, PiotrekkP commented on src/api/app/Dockerfile
> +WORKDIR "/src/src/api/app"
Moze glupie pytanie ale czy tutaj "src" musi byc dwa razy? Jesli tak to dlaczego?

2023-03-23 12:10 UTC, DawidBski commented on src/api/app/Dockerfile
> +WORKDIR "/src/src/api/app"
I believe there is no need to use src twice. I have no idea why but it works properly. Before merging i’ll remove one of them.

2023-03-23 12:18 UTC, DawidBski commented on src/api/app/Dockerfile
> +WORKDIR "/src/src/api/app"
The WORKDIR command simply sets the current working directory inside our image.

2023-03-23 13:43 UTC, mateuszmuszynski commented on src/api/app/Dockerfile
> +WORKDIR "/src/src/api/app"
I think the difference is that the solution without / at the beginning use relative path, where the one with / at the beginning use absolute path.

WORKDIR /src call from line 9 creates this directory and sets it as current directory.
So we can either use src/api/app or /src/src/api/app. I prefer first one tbh.

2023-03-23 14:47 UTC, merged