Feature/patro23 105 configure api cors policy
intive/patronage2023-dotnet pull request #23
Opened 2023-03-21 16:44 UTC by LukaszWinowicz

https://tracker.intive.com/jira/browse/PATRO23-105

2023-03-21 18:44 UTC, DawidBski requested changes

2023-03-21 18:44 UTC, DawidBski commented on src/api/app/Program.cs
> +}
I would add this method to static class something like "/Extensions/ServiceExtensions.cs" to make our program.cs file more clean.

2023-03-24 12:47 UTC, mateuszgiedzinski requested changes

2023-03-24 12:47 UTC, mateuszgiedzinski commented on src/api/app/Configuration/CorsPolicyConfiguration.cs
> +				string? allowedOrigins = configuration.GetValue<string>("CorsAllowedOrigins");
I suggest to create array instead of string. You can do it like
ApiSecuritySettings
{
    public string[] CorsAllowedOrigins { get; set; } 
}

2023-03-24 12:47 UTC, mateuszgiedzinski commented on src/api/app/appsettings.json
> +	"CorsAllowedOrigins": "https://localhost:7106;http://localhost:5106"
Adjust to suggestion to have settings model.

2023-03-24 19:51 UTC, DawidBski commented on src/api/app/Configuration/CorsPolicyConfiguration.cs
> +		public static IServiceCollection AddCors(
Why do you return IServiceCollection here?

2023-03-25 06:50 UTC, LukaszWinowicz commented on src/api/app/Configuration/CorsPolicyConfiguration.cs
> +		public static IServiceCollection AddCors(
You can call other configuration methods on the same IServiceCollection object after calling AddCors, without having to create a new instance of IServiceCollection.

![image](https://user-images.githubusercontent.com/42235058/227701399-e305b7ae-a876-405a-b209-37fcd275be0c.png)

2023-03-25 13:00 UTC, LukaszWinowicz commented on src/api/app/appsettings.json
> +	"CorsAllowedOrigins": "https://localhost:7106;http://localhost:5106"
Done like:
```
"ApiSecuritySettings": {
		"CorsAllowedOrigins": [
			"https://localhost:7106",
			"http://localhost:5106"
		]
	}
```

2023-03-26 11:41 UTC, DawidBski approved these changes

2023-03-26 12:05 UTC, mateuszgiedzinski requested changes

2023-03-26 12:05 UTC, mateuszgiedzinski commented on src/api/app/Configuration/CorsPolicyConfigurationExtensions.cs
> +				{
try to avoid nested if statements. If you revert this if condition then code can look like 
`if (apiSecuritySettings != null)
{
    return;
}

var allowedOrigins = apiSecuritySettings.CorsAllowedOrigins;
if (allowedOrigins is null || allowedOrigin.Length == 0)
{
    return;
}

options.AddPolicy(corsPolicyName, builder =>
{
			builder.AllowAnyMethod()
			.AllowAnyHeader()
			.WithOrigins(allowedOrigins);
    		        });`

2023-03-26 12:05 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +using static Intive.Patronage2023.Api.Configuration.CorsPolicyConfigurationExtensions;
using Intive.Patronage2023.Api.Configuration; should be enough.

2023-03-26 12:05 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +// Extension method for configuring CORS
remove this comment Code is enough descriptive.

2023-03-28 17:16 UTC, mateuszgiedzinski approved these changes

2023-03-28 17:38 UTC, merged