[PATRO23-56] Local keycloak environment
intive/patronage2023-dotnet pull request #24
Opened 2023-03-21 21:56 UTC by DawidBski

2023-03-21 22:25 UTC, AlanP22 approved these changes

2023-03-23 16:15 UTC, mateuszmuszynski requested changes

2023-03-23 16:15 UTC, mateuszmuszynski commented on docker-compose.override.yml
> +      - "5080:80"
Any reason why it has been changed?

2023-03-23 16:15 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> +using Microsoft.EntityFrameworkCore;
It's not related to keycloak

2023-03-23 16:15 UTC, mateuszmuszynski commented on src/modules/example/api/ExampleModule.cs
> +		services.AddDbContext<ExampleDbContext>(options => options.UseSqlServer(configurationManager.GetConnectionString("DockerDb")));
Not related to KC, create another PR

2023-03-23 16:36 UTC, DawidBski commented on docker-compose.override.yml
> +      - "5080:80"
Meybe my reason is weak and stupid a little but i think ports 8080 and 8081 are more related to  [running keycloak in a container instruction](https://www.keycloak.org/server/containers#_building_the_docker_image).

2023-03-23 16:39 UTC, DawidBski commented on src/api/app/Program.cs
> +using Microsoft.EntityFrameworkCore;
I've already corrected it.

2023-03-23 16:40 UTC, mateuszmuszynski commented on docker-compose.override.yml
> +      - "5080:80"
Good point. Let's leave it as it is.

2023-03-23 16:47 UTC, DawidBski commented on src/modules/example/api/ExampleModule.cs
> +		services.AddDbContext<ExampleDbContext>(options => options.UseSqlServer(configurationManager.GetConnectionString("DockerDb")));
I've changed it back.

2023-03-24 07:39 UTC, mateuszmuszynski approved these changes

2023-03-24 07:45 UTC, merged