[PATRO23-37] Budget module added
intive/patronage2023-dotnet pull request #26
Opened 2023-03-22 23:29 UTC by PiotrekkP

2023-03-23 00:36 UTC, PiotrekkP commented
Now I am wondering if branch should be named based on story or subtask from this story which in this case is "Create budget module". My bet is that I hurried up and named it wrong, because there are more people working on this story so branches names need to be different. But I'll wait for your comments.

2023-03-23 08:49 UTC, mateuszmuszynski commented
> Now I am wondering if branch should be named based on story or subtask from this story which in this case is "Create budget module". My bet is that I hurried up and named it wrong, because there are more people working on this story so branches names need to be different. But I'll wait for your comments.

Yes, let's use subtask id for branch names. But let's leave this case as it is.

2023-03-23 16:24 UTC, mateuszmuszynski requested changes

2023-03-23 16:24 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Migrations/20230313153024_InitialMigration.cs
> +namespace Intive.Patronage2023.Modules.Budget.Infrastructure.Migrations
Not sure whether we should copy migrations and entity builder. Maybe we can just remove this and DbSet from context.
@mateuszgiedzinski What do you think?

2023-03-23 16:30 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Migrations/20230313153024_InitialMigration.cs
> +namespace Intive.Patronage2023.Modules.Budget.Infrastructure.Migrations
I agree. We need to exclude Migrations directory from copy.

2023-03-25 14:48 UTC, AlanP22 approved these changes

2023-03-27 15:57 UTC, a-lipert approved these changes

2023-03-28 15:22 UTC, mateuszgiedzinski requested changes
Add init migration and adjust readme with module migration script.

2023-03-28 15:23 UTC, mateuszgiedzinski commented on src/modules/budget/api/Properties/launchSettings.json
> +  "$schema": "https://json.schemastore.org/launchsettings.json",
still not removed

2023-03-29 05:39 UTC, mateuszgiedzinski commented on src/modules/budget/api/Properties/launchSettings.json
> +  "$schema": "https://json.schemastore.org/launchsettings.json",
Please remove whole file. We don't want to run module independently so launch settings is not  necessery.

2023-03-29 09:47 UTC, mateuszgiedzinski requested changes

2023-03-29 09:47 UTC, mateuszgiedzinski commented on src/modules/budget/api/Intive.Patronage2023.Modules.Budget.Api.csproj
> +  <ItemGroup>
Properties directory is not needed. Do not leave empty directories.

2023-03-29 21:49 UTC, mateuszgiedzinski approved these changes

2023-03-29 21:53 UTC, mateuszgiedzinski requested changes

2023-03-29 21:53 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/BudgetDbContext.cs
> +	public BudgetDbContext(DbContextOptions<BudgetDbContext> options)
Add initial migration. 
Every change in db context or entities should have relevant migration.

2023-04-05 14:08 UTC, closed without merging