[PATRO23-154] add design time dbcontex creation
intive/patronage2023-dotnet pull request #27
Opened 2023-03-23 18:34 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-154

2023-03-23 21:32 UTC, pzajaczkowski requested changes

2023-03-23 21:32 UTC, pzajaczkowski commented on src/api/app/ExampleDbContextFactory.cs
In docs i found sentence: "If a class implementing this interface is found in either the same project as the derived DbContext or in the application's startup project, the tools bypass the other ways of creating the DbContext and use the design-time factory instead.". So i think we should move dbcontext factory to its module infrastructure project (same project as ExampleDbContext) to keep things organized. Correct me if i'm wrong.

2023-03-23 21:32 UTC, pzajaczkowski commented on src/api/app/appsettings.Development.json
> +}
no new line at the end of file

2023-03-23 21:32 UTC, pzajaczkowski commented on src/api/app/appsettings.json
> +}
same thing

2023-03-23 21:41 UTC, DawidBski commented on src/api/app/ExampleDbContextFactory.cs
You're right i just forgot about that. It's cool that you read docs. Nice that you noticed it!

2023-03-23 22:41 UTC, DawidBski commented on src/api/app/appsettings.json
> +}
![end_line](https://user-images.githubusercontent.com/127483473/227380580-d0a9b5e2-5723-4f58-8f3d-7430119ce0b0.png)

2023-03-23 22:44 UTC, DawidBski commented on src/api/app/appsettings.Development.json
> +}
![end_line_light](https://user-images.githubusercontent.com/127483473/227380984-d2eb7eb9-df72-44cb-9667-878aa0edd67e.png)

2023-03-23 22:49 UTC, DawidBski commented on src/api/app/ExampleDbContextFactory.cs
Done :)

2023-03-24 07:36 UTC, pzajaczkowski approved these changes

2023-03-24 07:36 UTC, pzajaczkowski commented on src/api/app/appsettings.json
> +}
ok XD haven't seen that before.

2023-03-24 07:43 UTC, DawidBski commented on src/api/app/appsettings.json
> +}
I was looking for that about 10-15 min :)

2023-03-25 10:34 UTC, mateuszgiedzinski requested changes

2023-03-25 10:34 UTC, mateuszgiedzinski commented on src/api/app/appsettings.Development.json
> +		"MigrationsDb": "Server=localhost,1433; Database=IntivePatronage-2023-DB; User=SA; Password=S3cur3P@ssW0rd!; TrustServerCertificate=true"
Is it good idea to have password here?

2023-03-25 11:32 UTC, DawidBski commented on src/api/app/appsettings.Development.json
> +		"MigrationsDb": "Server=localhost,1433; Database=IntivePatronage-2023-DB; User=SA; Password=S3cur3P@ssW0rd!; TrustServerCertificate=true"
For production purpose isn't but for development I believe it's fine.

2023-03-25 11:56 UTC, DawidBski commented on src/api/app/appsettings.Development.json
> +		"MigrationsDb": "Server=localhost,1433; Database=IntivePatronage-2023-DB; User=SA; Password=S3cur3P@ssW0rd!; TrustServerCertificate=true"
For a production purpose I would use Environment Variables.

2023-03-26 12:11 UTC, mateuszgiedzinski requested changes

2023-03-26 12:11 UTC, mateuszgiedzinski commented on src/api/app/appsettings.json
> +		"MigrationsDb": "Server=localhost,1433; Database=IntivePatronage-2023-DB; User=SA; Password=S3cur3P@ssW0rd!; TrustServerCertificate=true"
Still secret for db context is present. .

2023-04-01 23:58 UTC, mateuszgiedzinski approved these changes

2023-04-02 00:03 UTC, mateuszgiedzinski commented
When you will merge commit please sellect option to Merge and squash commits.  There are to many commits for such small change. Don't forget to add to your commits [Task number] - commit description. 
I saw that you forgot about that.

2023-04-02 23:25 UTC, merged