feature/[PATRO23-145] - add registration to keycloak
intive/patronage2023-dotnet pull request #33
Opened 2023-03-31 15:12 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-145

2023-03-31 21:25 UTC, pzajaczkowski approved these changes
Looks fine. I will try to run and test it later.

2023-04-01 11:40 UTC, DawidBski approved these changes
Everything works as it should work. Big + for adding automatic realm import.

2023-04-01 22:21 UTC, mateuszgiedzinski requested changes

2023-04-01 22:21 UTC, mateuszgiedzinski commented on realm-config.json
> +  "realm": "Example-Realm",
I'm not sure about realm name. Maybe we can use something more app specific like InBudget-Realm?

2023-04-02 10:33 UTC, pzajaczkowski commented on realm-config.json
> +	"realm": "budget-realm",
Some people might associate this name with budget module (which they shouldn't). So i would change it to inbudget-realm, as Mateusz adviced,  where "inbudget" is the name of app we are developing. But i don't think the change is that necessary right now. In the future i would like to add configured client to this imported realm config, so we don't have to create it manually every time (maybe idea for new task).

2023-04-02 12:43 UTC, pzajaczkowski commented on realm-config.json
> +	"realm": "budget-realm",
I've changed my mind, let's make it inbudget-realm now. I've changed keycloak settings in appsettings.Development.json to match it.

`
"Keycloak": {
		"realm": "inbudget-realm",
		"auth-server-url": "http://keycloak:8080/",
		"verify-token-audience": false,
		"ssl-required": "none",
		"resource": "inbudget-client",
		"public-client": true,
		"confidential-port": 0
                   }
`

2023-04-02 12:49 UTC, pzajaczkowski requested changes

2023-04-02 12:49 UTC, pzajaczkowski commented on realm-config.json
> +	"realm": "budget-realm",
Change to "inbudget-realm". Hope nobody is offended by lowercase (already made wiki 🙏)

2023-04-02 14:04 UTC, IzabelaPalubicka commented on realm-config.json
> +	"realm": "budget-realm",
I think to rename it to "inbudget-realm-dev", because separate realm will be for prod and this can be called as "inbudget-realm"

2023-04-02 15:41 UTC, pzajaczkowski commented on realm-config.json
> +	"realm": "budget-realm",
Okay. Do what you think is the best approach and i will adapt to your changes

2023-04-02 16:39 UTC, mateuszgiedzinski commented on realm-config.json
> +	"realm": "budget-realm",
Good point. We can have two realms one for dev and one for prod and select exact one by calling exact one by api. 
We need configuration for keycloak integration.

2023-04-02 16:41 UTC, mateuszgiedzinski approved these changes
LGTM

2023-04-03 16:05 UTC, pzajaczkowski approved these changes

2023-04-03 16:34 UTC, merged