feature/[PATRO23-64] - keycloak user authentication
intive/patronage2023-dotnet pull request #34
Opened 2023-03-31 21:18 UTC by pzajaczkowski

https://tracker.intive.com/jira/browse/PATRO23-64

2023-04-01 14:49 UTC, mateuszgiedzinski requested changes

2023-04-01 14:49 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +builder.Services.AddKeycloakAuthentication(builder.Configuration, configureOptions =>
Try to not put blocks of code between block that is for one funciton. here you separate commands and queries registration from bus registration.

2023-04-01 14:49 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +if (app.Environment.IsDevelopment())
Please remove this IsDevelopemet check.. It's nothing wrong to have swagger on production for now.

2023-04-01 14:49 UTC, mateuszgiedzinski commented on src/modules/example/api/Controllers/ExampleController.cs
> +using Microsoft.AspNetCore.Authorization;
I'm wondering why the code check doesn't work for grouping namespaces. Namespaces should be grouped and sorted.

2023-04-01 14:49 UTC, mateuszgiedzinski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +/// Static class SwaggerConfigurationExtensions.
I think better summary for that will be  Class that contains extension methods for swagger configuration.

2023-04-01 23:55 UTC, mateuszgiedzinski requested changes

2023-04-01 23:55 UTC, mateuszgiedzinski commented on src/modules/example/api/Controllers/ExampleController.cs
> +[Authorize]
Instead using Authorize everywhere we can specify filter for that. Read this article https://neelbhatt.com/2018/03/23/global-authorization-filter-in-net-core-net-core-security-part-v/
For now create simple policy that allow only authenticated users to use our api without any other requirements.

2023-04-02 16:51 UTC, mateuszgiedzinski requested changes

2023-04-02 16:51 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +builder.Services.AddMvc(options =>
We don't need MVC here. We need only Controllers. You can add this lamda inside AddControllers

2023-04-03 16:56 UTC, IzabelaPalubicka approved these changes

2023-04-03 21:01 UTC, mateuszgiedzinski approved these changes

2023-04-03 21:02 UTC, mateuszgiedzinski commented
Please resolve conflicts.

2023-04-03 21:46 UTC, merged