feature/PATRO23-102-Add-migrations-run-on-startup
intive/patronage2023-dotnet pull request #35
Opened 2023-04-01 16:57 UTC by pzajaczkowski

https://tracker.intive.com/jira/browse/PATRO23-102

I'm considering doing it asynchronously. Let me know what you think.

2023-04-01 23:02 UTC, mateuszgiedzinski requested changes

2023-04-01 23:02 UTC, mateuszgiedzinski commented on src/modules/example/api/ExampleModule.cs
> +		using var scope = app.ApplicationServices.GetService<IServiceScopeFactory>()!.CreateScope();
Do it more generic way. I mean extract code for runing migration for DbContext as some kind of extension for IApplicationBuilder. Generic parametr should be type fo DbContext to Migrate. 
app.InitDatabase<ExampleDbContext>();

2023-04-01 23:02 UTC, mateuszgiedzinski commented on src/modules/example/api/ExampleModule.cs
> +		using var scope = app.ApplicationServices.GetService<IServiceScopeFactory>()!.CreateScope();
Here is fine to use method scoped using  but sometimes when you create scope from DIContainer it's better to specify how long scope must live. In this case you should close scope after 43 line.

2023-04-02 16:47 UTC, mateuszgiedzinski approved these changes
LGTM. Regarding your question I think migration should be executed synchronously. Same as app is configuring on startup.

2023-04-03 06:54 UTC, a-lipert approved these changes

2023-04-03 12:14 UTC, merged