feature/PATRO23-146 - add password policy
intive/patronage2023-dotnet pull request #36
Opened 2023-04-01 19:23 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-146

Must be merged with: [https://github.com/intive/patronage2023-dotnet/pull/33](url)

2023-04-01 22:56 UTC, mateuszgiedzinski requested changes

2023-04-01 22:56 UTC, mateuszgiedzinski commented on realm-config.json
> +	"realm": "Example-Realm",
Same problem with realm name as in Sign up config.

2023-04-02 16:33 UTC, mateuszgiedzinski approved these changes
LGTM

2023-04-02 17:11 UTC, mateuszmuszynski requested changes

2023-04-02 17:11 UTC, mateuszmuszynski commented on docker-compose.override.yml
> +     - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
Can't we just use realm import during startup? https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup
What's the advantage of your approach?

2023-04-02 17:11 UTC, mateuszmuszynski commented on src/api/app/Keycloak/Dockerfile
> -ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
Why has it been removed?

2023-04-02 19:17 UTC, mateuszmuszynski commented on docker-compose.override.yml
> +     - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
It's possible to import realm in keyclock user interface. Maybe we can just leave configuration files as it is and import it manually for both dev and prod. What do you think?

2023-04-02 23:26 UTC, pzajaczkowski commented on docker-compose.override.yml
> +     - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
Imo not having to import realm every time we create Keycloak container would be nice. At least for dev. Don't really care what import approach is used.

2023-04-03 08:22 UTC, IzabelaPalubicka commented on docker-compose.override.yml
> +     - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
I tried this approach from link and it didn't work. Line 31 if file exist ignore.

2023-04-03 08:27 UTC, IzabelaPalubicka commented on src/api/app/Keycloak/Dockerfile
> -ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
Because it doesn't work. In docker-compose.override.yml in keycloak commands we have start dev.

2023-04-03 22:11 UTC, mateuszgiedzinski commented
Conflict should be resolved.

2023-04-04 09:46 UTC, pzajaczkowski approved these changes
👍

2023-04-04 19:24 UTC, IzabelaPalubicka commented
The story has changed, so I corrected the password requirements and I also changed that there is no username field on registration (only email)

2023-04-05 12:48 UTC, merged