Feature/patro23-192 - create sign up api endpoint
intive/patronage2023-dotnet pull request #38
Opened 2023-04-03 21:44 UTC by Kepeczsz

https://tracker.intive.com/jira/browse/PATRO23-192

2023-04-03 22:19 UTC, pzajaczkowski requested changes

2023-04-03 22:19 UTC, pzajaczkowski commented on src/modules/example/api/Controllers/SignUpController.cs
> +	public async Task<IActionResult> SignUp([FromBody] CreateUser command)
I think we should allow anonymous users to access this endpoint. Currently there is global authentication.

2023-04-03 22:19 UTC, pzajaczkowski commented on src/modules/example/application/User/CreatingUser/CreateUser.cs
> +public record CreateUser(Guid Id, string Username, string Password, string Email) : ICommand;
"The user is required to enter their email address, password, name (first and last) on the registration page"
Based on the story, we don't need username, but we need firstname and lastname fields.

2023-04-03 23:04 UTC, mateuszgiedzinski requested changes

2023-04-03 23:04 UTC, mateuszgiedzinski commented on src/modules/example/api/Controllers/SignUpController.cs
> +namespace Intive.Patronage2023.Modules.Example.Api.Controllers;
Place all the stuff directly in api. Maybe in future we will have SecurityModule but for now security should be connected to api.

2023-04-03 23:04 UTC, mateuszgiedzinski commented on src/modules/example/application/User/CreatingUser/CreateUser.cs
> +namespace Intive.Patronage2023.Modules.Example.Application.User.CreatingUser;
Move this to Api project.

2023-04-03 23:04 UTC, mateuszgiedzinski commented on src/modules/example/api/ExampleModule.cs
> +		services.AddScoped<IValidator<CreateUser>, CreateUserValidator>();
Do not mess example module with user creation.

2023-04-05 11:05 UTC, pzajaczkowski commented
I think you forgot to delete create user from example module

2023-04-07 20:34 UTC, mateuszgiedzinski requested changes

2023-04-07 20:34 UTC, mateuszgiedzinski commented on src/api/app/Controllers/SignUpController.cs
> +	///        "Password": "testPasword123!@",
we need to use camel case as it is  standard for json.

2023-04-07 20:34 UTC, mateuszgiedzinski commented on src/api/app/Keycloak/Token/GetToken.cs
> +/// .
dot is not valid summary

2023-04-07 20:34 UTC, mateuszgiedzinski commented on src/api/app/Keycloak/Token/GetToken.cs
> +public class GetTokenHandler : ICommandHandler<GetToken>
Command handler and Get seems weird. Commands won't return any results. Maybe this should be query. But why this is added for sign up ?

2023-04-07 20:39 UTC, mateuszgiedzinski requested changes

2023-04-07 20:39 UTC, mateuszgiedzinski commented on src/api/app/User/UserModule.cs
> +		services.AddDbContext<ExampleDbContext>(options => options.UseSqlServer(configurationManager.GetConnectionString("AppDb")));
User module don't need any  db context for now so please remove this registration.

2023-04-07 20:39 UTC, mateuszgiedzinski commented on src/modules/example/application/User/CreatingUser/CreateUser.cs
> +/// <param name="FirstName">FirstName which user provides.</param>
"First name which user provides".

2023-04-09 20:48 UTC, pzajaczkowski requested changes

2023-04-09 20:48 UTC, pzajaczkowski commented on src/api/app/Controllers/SignUpController.cs
> +	[ProducesResponseType(typeof(string), StatusCodes.Status201Created)]
Wrong response type. Maybe we need some kind of UserInfo record?

2023-04-10 23:40 UTC, DawidBski commented on src/api/app/Controllers/SignUpController.cs
> +namespace Intive.Patronage2023.Modules.Example.Api.Controllers;
Wrong namespace

2023-04-10 23:40 UTC, DawidBski commented on src/api/app/Program.cs
> +using Intive.Patronage2023.Modules.Example.Api.User;
wrong using

2023-04-10 23:40 UTC, DawidBski commented on src/api/app/User/CreatingUser/CreateUser.cs
> +namespace Intive.Patronage2023.Modules.Example.Api.User.CreatingUser;
namespace

2023-04-10 23:40 UTC, DawidBski commented on src/api/app/User/CreatingUser/CreateUserValidator.cs
> +namespace Intive.Patronage2023.Modules.Example.Api.User.CreatingUser;
change namespace

2023-04-11 11:55 UTC, Kepeczsz commented on src/api/app/Controllers/SignUpController.cs
> +	[ProducesResponseType(typeof(string), StatusCodes.Status201Created)]
I have asked leaders if, there should be another response type,  and for now it should be like this.

2023-04-11 12:26 UTC, mateuszgiedzinski requested changes

2023-04-11 12:26 UTC, mateuszgiedzinski commented on src/api/app/Controllers/SignUpController.cs
> +	[ProducesResponseType(typeof(string), StatusCodes.Status201Created)]
For 201 of course but for 400 no.

2023-04-12 21:41 UTC, pzajaczkowski approved these changes

2023-04-14 14:14 UTC, mateuszmuszynski requested changes

2023-04-14 14:14 UTC, mateuszmuszynski commented on src/api/app/Controllers/SignUpController.cs
> +			return this.Created($"user/{command.FirstName}", command.FirstName);
Why you return firstName here? This is an url to resource that doesn't exist. I think we can just return `this.Created()`

2023-04-14 15:25 UTC, mateuszmuszynski approved these changes

2023-04-14 17:18 UTC, merged