feature/[PATRO23-51] swagger support
intive/patronage2023-dotnet pull request #4
Opened 2023-03-08 19:44 UTC by pzajaczkowski

2023-03-10 13:35 UTC, mateuszmuszynski requested changes

2023-03-10 13:35 UTC, mateuszmuszynski commented on src/modules/example/api/Intive.Patronage2023.Modules.Example.Api.csproj
> +	<ItemGroup>
Incorrect indentation

2023-03-10 13:35 UTC, mateuszmuszynski commented on src/modules/example/api/Controllers/ExampleController.cs
> +	///        "Name": "Example",
Remove trailing comma

2023-03-10 13:35 UTC, mateuszmuszynski commented on src/api/app/Program.cs
>  app.Run();
Put newline as a last character

2023-03-10 13:35 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> +using System.Reflection;
Unused using directive

2023-03-11 15:58 UTC, mateuszmuszynski approved these changes

2023-03-13 14:21 UTC, mateuszgiedzinski approved these changes
LGTM

2023-03-13 14:36 UTC, merged