Feature/patro23 50 add console application insights loggingg
intive/patronage2023-dotnet pull request #40
Opened 2023-04-05 17:15 UTC by KlaudiaGajocha

2023-04-07 11:44 UTC, mateuszgiedzinski requested changes

2023-04-07 11:44 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +var app = builder.Build();
This line should be where it was before.

2023-04-07 11:44 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +app.MapGet("/Test", async context =>
I think this /Test endpoint is not needed.

2023-04-07 11:44 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +var logger = loggerFactory.CreateLogger<Program>();
I think logger is not necessary here .

2023-04-07 11:44 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +var logger = loggerFactory.CreateLogger<Program>();
It is created only for Test endpoint and can be removed.

2023-04-14 14:11 UTC, mateuszmuszynski requested changes

2023-04-14 14:11 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> -string corsPolicyName = "CorsPolicy";
Why has it been removed?

2023-04-16 18:07 UTC, KlaudiaGajocha commented on src/api/app/Program.cs
> -string corsPolicyName = "CorsPolicy";
The variable 'corsPolicyName' was assigned but its value was never used

2023-04-16 18:08 UTC, KlaudiaGajocha commented on src/api/app/Program.cs
> +var logger = loggerFactory.CreateLogger<Program>();
it's removed

2023-04-16 19:17 UTC, mateuszgiedzinski requested changes

2023-04-16 19:17 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> -string corsPolicyName = "CorsPolicy";
Because you removed this line builder.Services.AddCors(builder.Configuration, corsPolicyName);

2023-04-17 15:53 UTC, KlaudiaGajocha commented on src/api/app/Program.cs
> -string corsPolicyName = "CorsPolicy";
Ok, I will correct it

2023-04-19 16:25 UTC, LukaszWinowicz approved these changes

2023-04-21 07:40 UTC, mateuszmuszynski approved these changes

2023-04-21 15:52 UTC, mateuszgiedzinski approved these changes

2023-04-21 16:29 UTC, merged