Create budget aggregate
intive/patronage2023-dotnet pull request #41
Opened 2023-04-06 18:02 UTC by AlanP22

Add budget aggregate, budget limit and period value objects.

2023-04-07 08:12 UTC, a-lipert requested changes
I've added some review comments - please see them.
Also this feature is missing a db migration - please add it.

2023-04-07 08:12 UTC, a-lipert commented on src/modules/budget/domain/BudgetAggregate.cs
> +public partial class BudgetAggregate : Aggregate
You are missing Description and Icon properties which were added to the task.

2023-04-07 08:12 UTC, a-lipert commented on src/modules/budget/domain/BudgetAggregate.cs
> +	public Guid UserId { get; private set; } = default!;
I think it would be good to add an unique index for userId, and name:
`builder.HasIndex(x => new { x.UserId, x.Name }, "UserIdBudgetNameIndex").IsUnique();`

This should be a part of BudgetAggregateEntityConfiguration (see ExampleAggregateEntityConfiguration).

2023-04-07 08:15 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetLimit.cs
> +public record class BudgetLimit(float Value, string Currency);
Agree. We can specify enum based on ISO 4217.

2023-04-07 08:18 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetAggregate.cs
> +	public Guid UserId { get; private set; } = default!;
We didn't discuss but i think IX_Budget_Column1_Column2 convention of naming indexes is better.

2023-04-07 08:19 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetAggregate.cs
> +	public Guid UserId { get; private set; } = default!;
Nevertheless this index is fine.

2023-04-11 17:08 UTC, mateuszgiedzinski requested changes

2023-04-11 17:08 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.Property(x => x.Limit).HasColumnName("Limit");
I think limit and period should have additional configuration that will convert it to value object. Learn about HasConversion method.

2023-04-11 19:40 UTC, mateuszmuszynski requested changes

2023-04-11 19:40 UTC, mateuszmuszynski commented on src/modules/budget/domain/BudgetLimit.cs
> +public record class BudgetLimit(float Value, Currency Currency);
Use decimal type as value

2023-04-12 00:54 UTC, AlanP22 commented on src/modules/budget/domain/BudgetAggregate.cs
> +public partial class BudgetAggregate : Aggregate
This will be fine? 
`x.Limit).HasColumnName("Limit").HasConversion(
 			v => JsonConvert.SerializeObject(v, Formatting.None),
 			v => JsonConvert.DeserializeObject<BudgetLimit>(v));
 		builder.Property(x => x.Period).HasColumnName("Period").HasConversion(
 			v => JsonConvert.SerializeObject(v, Formatting.None),
 			v => JsonConvert.DeserializeObject<BudgetPeriod>(v));`

2023-04-13 08:45 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.Property(x => x.Limit).HasColumnName("Limit");
Imo we should use Owned entity types here. https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities

2023-04-17 15:55 UTC, AlanP22 commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.Property(x => x.Limit).HasColumnName("Limit");
I changed like this:
`builder.Property(x => x.Limit).HasColumnName("Limit");
		builder.OwnsOne(x => x.Limit);
		builder.Property(x => x.Period).HasColumnName("Period");
		builder.OwnsOne(x => x.Period);
		builder.Property(x => x.CreatedOn).HasColumnName("CreatedOn");`

2023-04-19 15:35 UTC, pzajaczkowski approved these changes
After you make changes ask reviewers for rereview to send notification. Have you even check if it works before PR?

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/api/Properties/launchSettings.json
Don't change indentation

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +/// <param name="Description">Description.</param>
Typo

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/contracts/Events/BudgetCreatedDomainEvent.cs
> +	public string? Describtion { get; private set; }
typo

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/domain/BudgetAggregate.cs
> +	private BudgetAggregate(Guid id, string name, Guid userId, BudgetLimit budgetLimit, BudgetPeriod budgetDuration, string description, string iconName)
Code cannot be build due to ef exception about not being able to match parameter names and some problems with owned entity.

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/domain/BudgetAggregate.cs
> +	/// Budget describtion.
typo

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/domain/BudgetAggregate.cs
> +	/// <param name="describtion">Budget Describtion.</param>
typo

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/domain/BudgetAggregate.cs
> +		return new BudgetAggregate(id, name, userId, limit, period, icon, describtion);
typo

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/domain/BudgetAggregate.cs
> +		this.Describtion = @event.Describtion;
typo

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.Property(x => x.Limit).HasColumnName("Limit");
Property and OwnsOne both exclude eachother. Only
`builder.OwnsOne(x=>x.Limit)`
and
`builder.OwnsOne(x=>x.Period)`
Should stay. Additionaly there are some errors with mapping owned entities so fix those pls.

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/example/api/Intive.Patronage2023.Modules.Example.Api.csproj
Same as earlier above

2023-04-19 15:35 UTC, pzajaczkowski commented on src/modules/example/api/Properties/launchSettings.json
same again,
advice -> use docker if u are not using it yet

2023-04-19 15:35 UTC, pzajaczkowski commented on src/shared/infrastructure/Domain/BudgetLimit.cs
> +public record class BudgetLimit(decimal Value, Currency Currency);
record and class exclude each other, use record alone

2023-04-19 15:35 UTC, pzajaczkowski commented on src/shared/infrastructure/Domain/BudgetPeriod.cs
> +public record class BudgetPeriod(DateOnly StartDate, DateOnly EndDate);
same as above

2023-04-19 15:35 UTC, pzajaczkowski commented on src/shared/infrastructure/Domain/BudgetLimit.cs
I think you should create some folder maybe to keep shared things associated with budget
`/shared/infrastructure/Domain/(BudgetFolderOrSth)/BudgetLimit.cs`

2023-04-19 15:37 UTC, pzajaczkowski requested changes
Missclick approve xD

2023-04-19 20:45 UTC, mateuszgiedzinski requested changes

2023-04-19 20:45 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.OwnsOne(x => x.Limit);
Please ask on the chat about naming of Owns Properties. Now if you've seen in our migration we  have Limit_Value and Limit_Currency values. Ideally they can be named Limit and Currency. 
Same for Period.

2023-04-19 20:45 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Intive.Patronage2023.Modules.Budget.Infrastructure.csproj
> +      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
Do we need newtonsoft?

2023-04-19 20:45 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.OwnsOne(x => x.Limit);
https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities

2023-04-19 20:53 UTC, mateuszgiedzinski requested changes

2023-04-19 20:53 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Domain/OwnedEntities/BudgetLimit.cs
> +namespace Intive.Patronage2023.Shared.Infrastructure.Domain.OwnedEntities;
In domain driven design it is called ValueObject so i suggest that directory.

2023-04-19 20:53 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Domain/OwnedEntities/BudgetLimit.cs
> +public record BudgetLimit
I suggest some more generic name if this must be placed in shared. For example ideal name for value object like this is Money.

2023-04-19 20:53 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Domain/OwnedEntities/BudgetPeriod.cs
> +public record BudgetPeriod
I suggest some more generic name if this must be placed in shared. ( in my opinion should be in module/budget/domain) For example ideal name for value object like this is Period.

2023-04-19 20:53 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Domain/OwnedEntities/BudgetPeriod.cs
> +namespace Intive.Patronage2023.Shared.Infrastructure.Domain.OwnedEntities;
same as above. ValueObject.

2023-04-21 13:08 UTC, mateuszmuszynski requested changes

2023-04-22 21:48 UTC, pzajaczkowski approved these changes
Please let's close this poor Pull Request xD

2023-04-22 21:51 UTC, pzajaczkowski commented on src/modules/budget/api/Properties/launchSettings.json
> +  "$schema": "https://json.schemastore.org/launchsettings.json",
Tried but sth is still changing the indentation. It's going to be removed soon anyway so maybe we can leave it as it is.

2023-04-22 21:56 UTC, pzajaczkowski commented
> Please let's close this poor Pull Request xD

2023-04-22 23:09 UTC, mateuszgiedzinski approved these changes

2023-04-22 23:26 UTC, mateuszgiedzinski requested changes

2023-04-22 23:26 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Domain/BudgetRepository.cs
> +	bool IBudgetRepository.ExistsByName(string name)
I discussed with @mateuszmuszynski  and he suggest to not add this in repository. Our idea is to use query bus and have query which selects all budgets by name.

All this logic should be part of new IBussinessRule instead of validator. 
So to summarize what should be done here:
- remove ExistsByName method. 
- create new BussinessRule - BudgetNameUniquenessBussinessRule- with query bus and name as ctor parameters.
- add query bus as create aggregate parameter
- inside rule check if executed query won't return any results for given name.

2023-04-23 11:52 UTC, pzajaczkowski commented on src/modules/budget/infrastructure/Domain/BudgetRepository.cs
> +	bool IBudgetRepository.ExistsByName(string name)
Due to dependency problems with business rules, queries and dbcontext, i will just replace repository with db context. To be refactored in the future.

2023-04-23 18:27 UTC, a-lipert commented on src/modules/budget/infrastructure/Domain/BudgetRepository.cs
> +	bool IBudgetRepository.ExistsByName(string name)
I can try to modify that within the PR with validator that I've opened recently.

2023-04-23 18:33 UTC, a-lipert approved these changes
I am responsible for the validator, there is an open PR for that. I can add requested changes once this one is merged.

2023-04-23 19:07 UTC, mateuszgiedzinski approved these changes
I hope you checked if it works :)

2023-04-24 11:07 UTC, mateuszmuszynski approved these changes

2023-04-24 11:37 UTC, merged