feature/PATRO23-202 enhance swagger documentation
intive/patronage2023-dotnet pull request #42
Opened 2023-04-09 13:02 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-202

2023-04-09 20:34 UTC, pzajaczkowski requested changes
Two big things missing. First one is Fluent Validation swagger support. We need it to get info about schemas rules (Is nullable, regex etc -> https://cezarywalenciuk.pl/blog/programing/walidacja-z-fluentvalidation-waspnet-core--swagger). Second one is error respone (idk what to do).

2023-04-09 20:34 UTC, pzajaczkowski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +			"*.*.xml",
I guess this change is to include records comments in swagger? To include all xml simpy *.xml. Adjust or remove comment above.

2023-04-09 20:34 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[ProducesResponseType(typeof(BudgetInfo), StatusCodes.Status200OK)]
It produces PagedList<BudgetInfo>

2023-04-09 20:34 UTC, pzajaczkowski commented on src/modules/example/api/Controllers/ExampleController.cs
> +	[ProducesResponseType(typeof(ExampleInfo), StatusCodes.Status200OK)]
Same as in GetBudgets, it returns pagedList of exampleInfo objects

2023-04-09 22:20 UTC, DawidBski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +			"*.*.xml",
It's changed because we want to enhance our swagger documentation.  I adopted the code to your instructions.

2023-04-12 13:50 UTC, pzajaczkowski requested changes

2023-04-12 13:50 UTC, pzajaczkowski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +	public static void AddFluentValidationRuleToSwagger(this IServiceCollection services)
I don't think we need this method at all. Just move AddFluentValidationRulesToSwagger to AddSwagger extension method.

2023-04-12 13:50 UTC, pzajaczkowski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +		services.AddFluentValidationAutoValidation();
Remove this line, we are validating in controllers on our own anyway. If i remeber correctly it may have some problems with async.

2023-04-12 13:50 UTC, pzajaczkowski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +		services.AddFluentValidationClientsideAdapters();
Remove

2023-04-12 13:50 UTC, pzajaczkowski commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> +		services.AddValidatorsFromAssemblyContaining<Program>();
We are adding scoped validators in Modules

2023-04-12 13:50 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// <response code="401">If the user is unauthorized.</response>
No ProduceResponseType attribute for 401 code. Make all of this as resolved if it is intended.

2023-04-12 13:50 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// <response code="401">If the user is unauthorized.</response>
same story as above

2023-04-12 13:50 UTC, pzajaczkowski commented on src/modules/example/api/Controllers/ExampleController.cs
>  	/// <response code="401">If the user is unauthorized.</response>
Here too

2023-04-12 13:50 UTC, pzajaczkowski commented on src/modules/example/api/Controllers/ExampleController.cs
>  	/// <response code="401">If the user is unauthorized.</response>
Same

2023-04-12 14:07 UTC, DawidBski commented on src/modules/example/api/Controllers/ExampleController.cs
> +		var user = this.HttpContext;
Exactly :)

2023-04-12 21:38 UTC, pzajaczkowski approved these changes

2023-04-13 17:25 UTC, Kepeczsz approved these changes

2023-04-13 17:31 UTC, merged