feature/patro23-7 sign in
intive/patronage2023-dotnet pull request #43
Opened 2023-04-09 15:56 UTC by LukaszWinowicz

https://tracker.intive.com/jira/browse/PATRO23-7

2023-04-09 20:09 UTC, pzajaczkowski requested changes
After merge with newest dev i managed to test sign in and i can say it works. I recommend to do the same before merge, and decide if we want to use public client or authenticated (with secret). In case of second option you would have to change inbudget-client settings, and then copy client secret, export new realm settings and paste secret inside. Approach with public client works either btw.

2023-04-09 20:09 UTC, pzajaczkowski commented on src/api/app/appsettings.Development.json
Changes unnecessary after merge with dev (except of credentials if we want to change client authentication in keycloak)

2023-04-10 04:53 UTC, LukaszWinowicz commented on src/api/app/Controllers/UserController.cs
> +	[ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
I changed according to the comment.

2023-04-10 05:01 UTC, LukaszWinowicz commented on src/api/app/Controllers/UserController.cs
> +			if (responseContent != null)
Done.

2023-04-10 05:12 UTC, LukaszWinowicz commented on src/api/app/User/Queries/SignInUser.cs
> +/// <param name="Username">Username which user provides.</param>
I changed in the whole code from username to email.

2023-04-10 05:16 UTC, LukaszWinowicz commented on src/api/app/Controllers/UserController.cs
> +	/// if the sign-in failed. <see cref="Task"/>Representing the asynchronous operation.
I removed.

2023-04-10 15:35 UTC, LukaszWinowicz commented on tests/unit/Intive.Patronage2023.Example.Domain.Tests/Intive.Patronage2023.Example.Domain.Tests.csproj
Fixed.

2023-04-11 00:34 UTC, DawidBski commented on src/api/app/Controllers/UserController.cs
> +namespace Intive.Patronage2023.Api;
change namespace

2023-04-11 00:34 UTC, DawidBski commented on src/api/app/User/Queries/SignInUserValidator.cs
> +	}
The email address and password must meet more requirements according to the current Keycloak configuration.

2023-04-11 19:43 UTC, LukaszWinowicz commented on src/api/app/User/Queries/SignInUserValidator.cs
> +	}
We don't need that validation for sign in, we only need it when sign up an account.

2023-04-12 14:05 UTC, pzajaczkowski requested changes

2023-04-12 14:05 UTC, pzajaczkowski commented on src/api/app/appsettings.Development.json
Merge dev before further testing. All changes in this file from remote

2023-04-12 15:13 UTC, LukaszWinowicz commented on src/api/app/appsettings.Development.json
After talk with @mateuszmuszynski we don't want credentials. I removed them.

2023-04-12 21:36 UTC, pzajaczkowski approved these changes

2023-04-13 08:42 UTC, mateuszmuszynski requested changes

2023-04-13 08:42 UTC, mateuszmuszynski commented on tests/unit/Intive.Patronage2023.Example.Domain.Tests/Intive.Patronage2023.Example.Domain.Tests.csproj
> -<Import Project="..\..\..\app.props" />
whitespace changes, please revert it. We wouldn't like to change it back and forth.

2023-04-14 07:25 UTC, LukaszWinowicz commented on src/api/app/Program.cs
> -app.UseBudgetModule();
Deleted by mistake, has been corrected.

2023-04-14 07:26 UTC, LukaszWinowicz commented on src/api/app/Configuration/SwaggerConfigurationExtensions.cs
> -	{
Unnecessary whitespace, reverted.

2023-04-14 08:45 UTC, mateuszmuszynski approved these changes

2023-04-14 08:53 UTC, merged