feature/PATRO23-33 - List of budgets
intive/patronage2023-dotnet pull request #44
Opened 2023-04-10 20:47 UTC by a-lipert

https://tracker.intive.com/jira/browse/PATRO23-33

2023-04-10 22:19 UTC, pzajaczkowski requested changes

2023-04-10 22:19 UTC, pzajaczkowski commented on src/shared/abstractions/PagedList.cs
> +	public int TotalCount { get; set; }
TotalCount is not implemented and not working.

2023-04-11 08:14 UTC, a-lipert commented on src/modules/budget/application/Budget/GettingBudgets/GetBudgets.cs
> +			budgets = budgets.Where(x => x.Name.StartsWith(query.Search!, StringComparison.OrdinalIgnoreCase));
Good point, thanks!

2023-04-11 11:02 UTC, mateuszgiedzinski requested changes

2023-04-11 11:02 UTC, mateuszgiedzinski commented on src/shared/abstractions/IPageableQuery.cs
> +	bool SortAscending { get; set; }
Also one bool didn't specify what column we will use to sort results.

2023-04-11 11:15 UTC, a-lipert commented on src/shared/abstractions/Extensions/OrderedQueryableExtension.cs
> +		return query.Skip(pageIndex * pageSize).Take(pageSize);
That is changed as Piotr suggested, I was commiting changes while you were reviewing this file I suppose.

2023-04-12 12:07 UTC, mateuszgiedzinski requested changes

2023-04-12 14:16 UTC, pzajaczkowski requested changes

2023-04-12 15:24 UTC, a-lipert commented on src/modules/budget/application/Budget/GettingBudgets/GetBudgets.cs
> +		var mappedData = budgets.Paginate(query.PageIndex, query.PageSize).Select(BudgetAggregateBudgetInfoMapper.Map).ToList();
ToListAsync() works on an IQueryable only and Select returns IEnumerable so that's why it doesn't work here.

2023-04-13 21:41 UTC, mateuszgiedzinski requested changes

2023-04-13 21:41 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgets/GetBudgets.cs
> +		var mappedData = budgets.Paginate(query.PageIndex, query.PageSize).Select(BudgetAggregateBudgetInfoMapper.Map).ToList();
Ok I see. There should be ToListAsync(). 
Probably we need to change how this method is called. 
We have to possibilities. One is to create lambda inside Select and second one is to create Expression from Map method. https://stackoverflow.com/questions/9377635/create-expression-from-func. 
This can be done as some extension method 
![image](https://user-images.githubusercontent.com/31278269/231889108-ed4dc9a8-ffe3-43ae-a6b1-ad03fcdf353a.png)

2023-04-13 21:55 UTC, mateuszgiedzinski requested changes

2023-04-13 21:55 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetQueryExtension.cs
> +			case "id": return sortableQuery.SortAscending ? query.OrderBy(x => x.Id) : query.OrderByDescending(x => x.Id);
hmm I'm thinking that sorting and paging should be done after projection. What do you think?

2023-04-13 21:55 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetQueryExtension.cs
> +			default: throw new NotSupportedException();
you can add in this exception some  message. I like adding $"{sortableQuery.ColumnName} is not supported yet"

2023-04-13 21:55 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetQueryExtension.cs
> +	private static IQueryable<BudgetAggregate> Sort(IQueryable<BudgetAggregate> query, SortDescriptor sortableQuery)
descriptor

2023-04-17 09:18 UTC, a-lipert commented on src/modules/budget/application/Extensions/BudgetQueryExtension.cs
> +			case "id": return sortableQuery.SortAscending ? query.OrderBy(x => x.Id) : query.OrderByDescending(x => x.Id);
After modifying Map method (newest commits), putting projection after sorting and paging was the only way I managed to make the code work properly.

2023-04-17 16:55 UTC, pzajaczkowski requested changes
👍

2023-04-17 18:04 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetQueryExtension.cs
> +			case "id": return sortableQuery.SortAscending ? query.OrderBy(x => x.Id) : query.OrderByDescending(x => x.Id);
Not the only 😄

2023-04-18 07:45 UTC, a-lipert commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[Route("list")]
done

2023-04-18 07:45 UTC, a-lipert commented on src/modules/budget/api/Controllers/BudgetController.cs
>  	/// <returns>Paged list of Budgets.</returns>
ok done

2023-04-18 13:54 UTC, pzajaczkowski approved these changes

2023-04-19 13:56 UTC, mateuszgiedzinski approved these changes
Please fix merge conflicts

2023-04-19 18:02 UTC, merged