feature/PATRO23-133 - User context provider
intive/patronage2023-dotnet pull request #45
Opened 2023-04-10 20:53 UTC by pzajaczkowski

https://tracker.intive.com/jira/browse/PATRO23-133

2023-04-11 10:45 UTC, mateuszgiedzinski requested changes

2023-04-11 10:45 UTC, mateuszgiedzinski commented on src/shared/infrastructure/ExecutionContextAccessor.cs
> +	/// <inheritdoc />
@DawidBski inheritdoc is fine if you want to inherit documentation from interface or base class.

2023-04-11 10:45 UTC, mateuszgiedzinski commented on src/shared/infrastructure/ExecutionContextAccessor.cs
> +/// Implementation of IExecutionContextAccessor.
Put couple of words what this class have. For example Implementation of <see cref="IExecutionContextAccessor" > that get user information based on jwt token. 

Implementation can be different and we need to have information about that specific one.

2023-04-11 19:16 UTC, mateuszmuszynski requested changes

2023-04-11 19:16 UTC, mateuszmuszynski commented on src/shared/infrastructure/ExecutionContextAccessor.cs
> +	public Guid? GetUserId(HttpContext httpContext)
Suggestion: Use IHttpContextAccesor instead of parameter - https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-7.0#access-httpcontext-from-custom-components

2023-04-12 17:26 UTC, DawidBski approved these changes

2023-04-12 21:30 UTC, mateuszgiedzinski approved these changes

2023-04-12 21:31 UTC, merged