PATRO23-123/add-database-integration-tests
intive/patronage2023-dotnet pull request #46
Opened 2023-04-12 18:30 UTC by KlaudiaGajocha

2023-04-13 07:28 UTC, mateuszmuszynski requested changes

2023-04-13 07:28 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> +if (!app.Environment.IsDevelopment())
Changes not related to integration tests

2023-04-13 07:28 UTC, mateuszmuszynski commented on src/api/app/appsettings.json
> +		"Debug": { // Debug provider.
Changes not related to integration tests

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/DatabaseFixture.cs
> +            var container = new GenericContainer(dockerClient, "mysql:8.0")
Use SQL server container

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/ExampleHelper.cs
> +        public static ExampleAggregate CreateExample()
Changes not related to integration tests

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/GetExamplesQueryHandlerTest.cs
> +            var options = new DbContextOptionsBuilder<ExampleDbContext>()
Use Docker database, not in memory db.

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/IntegrationTests.cs
> +namespace MyProject
Incorrect namespace

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/IntegrationTests.cs
> +    public class SharedDatabaseFixture : IDisposable
Why we have 2 database fixtures?

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/IntegrationTests.cs
> +    public class MyEntity
Looks like some testing data, please remove it.

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/QueryResponseTests.cs
> +namespace Intive.Patronage2023.Modules.Example.Tests
Incorrect namespace

2023-04-13 07:28 UTC, mateuszmuszynski commented on tests/integration/QueryResponseTests.cs
> +    public class GetExamplesTests
Integration tests are a goal of this ticket, but this is unit test 🤔

2023-04-13 20:02 UTC, KlaudiaGajocha commented on tests/integration/QueryResponseTests.cs
> +    public class GetExamplesTests
In the scope was "Write unit tests for GetExamples query handler". Should I delete it or keep it but for example move it to the unit tests folder?

2023-04-13 20:37 UTC, mateuszgiedzinski requested changes

2023-04-13 20:37 UTC, mateuszgiedzinski commented on tests/integration/QueryResponseTests.cs
> +    public class GetExamplesTests
Integration test means that we shouldn't mock anything. We should use real component so example repository can be done as new ExampleRepository(exampleDbContext) instead of mocking like that _exampleRepositoryMock.Setup(repo => repo.GetExamplesAsync()).ReturnsAsync(examples);

2023-04-13 20:37 UTC, mateuszgiedzinski commented on tests/integration/QueryResponseTests.cs
> +            _exampleRepositoryMock.Setup(repo => repo.GetExamplesAsync()).ReturnsAsync(examples);
we won't use _fieldName notation. we name  it as  fieldName and use it as this.fieldName

2023-04-17 16:14 UTC, KlaudiaGajocha commented
If there are further problems with this pull request, maybe I should close it and create a new one with the latest code?

2023-04-21 07:45 UTC, mateuszmuszynski requested changes

2023-04-21 07:45 UTC, mateuszmuszynski commented on tests/integration/GetExamplesQueryHandlerTest.cs
> +		dbContext.Example.Add(example);
Indentation issues

2023-04-21 07:45 UTC, mateuszmuszynski commented on tests/integration/GetExamplesQueryHandlerTest.cs
> +            Assert.Single(result.Items);
Use Fluent Assertions

2023-04-21 07:45 UTC, mateuszmuszynski commented on tests/integration/QueryResponseTests.cs
> +namespace Intive.Patronage2023.Modules.Example.Tests
still incorrect

2023-04-21 07:45 UTC, mateuszmuszynski commented on tests/integration/QueryResponseTests.cs
> +			var exampleDbContext = new ExampleDbContext();
You should use DatabaseFixture in this class too

2023-04-21 07:45 UTC, mateuszmuszynski commented on tests/integration/QueryResponseTests.cs
> +			Assert.NotNull(result);
Use Fluent Assertions

2023-04-21 07:45 UTC, mateuszmuszynski commented on tests/integration/QueryResponseTests.cs
> +			Assert.NotNull(result);
Use Fluent Assertions

2023-04-21 07:45 UTC, mateuszmuszynski commented on intive
Remove

2023-04-21 07:45 UTC, mateuszmuszynski commented on src/api/app/Intive.Patronage2023.Api.csproj
Not sure why these files are removed. Maybe something is wrong with your local environment?

2023-04-21 15:38 UTC, KlaudiaGajocha commented on src/api/app/Intive.Patronage2023.Api.csproj
I removed them because they should not be committed

2023-04-24 22:15 UTC, mateuszgiedzinski commented on src/api/app/Intive.Patronage2023.Api.csproj
I fixed that by mergeing dev into this branch.

2023-04-25 09:24 UTC, mateuszmuszynski requested changes

2023-04-25 09:24 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationsTests/DatabaseFixtures.cs
> +    public class GetExampleQueryHandlerTests : IClassFixture<DatabaseFixture>
Not used class

2023-04-25 09:24 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationsTests/GetExamplesQueryHandlerTest.cs
> +            var dbContext = new ExampleDbContext(options);
We should use DbContext from fixture.

2023-04-25 09:24 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationsTests/QueryResponseTests.cs
> +
Remove spaces

2023-04-25 09:24 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationsTests/QueryResponseTests.cs
> +		var options = new DbContextOptionsBuilder<ExampleDbContext>()
Inject & use fixture

2023-04-25 09:24 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationsTests/QueryResponseTests.cs
> +		dbContext.Example.AddRange((IEnumerable<Domain.ExampleAggregate>)examples);
Are you sure this cast works? ;)

2023-04-25 22:52 UTC, mateuszgiedzinski commented on tests/integration/DatabaseFixture.cs
> +            var container = new GenericContainer(dockerClient, "mysql:8.0")
looks like this file is overriden by future changes. I don't know.  It's really weird.

2023-04-26 19:08 UTC, DawidBski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationsTests/QueryResponseTests.cs
> +		dbContext.SaveChanges();
What is the purpose of saving changes twice? If it is on purpose then resolve conversation.

2023-04-27 19:36 UTC, closed without merging