[PATRO23-52] add ErrorHandleMiddleware and ExampleErrorService
intive/patronage2023-dotnet pull request #47
Opened 2023-04-13 21:47 UTC by Slashu

https://tracker.intive.com/jira/projects/PATRO23/issues/PATRO23-52?filter=allopenissues

2023-04-13 22:14 UTC, DawidBski requested changes
Merge to current dev.

2023-04-13 22:14 UTC, DawidBski commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +namespace Intive.Patronage2023.Shared.Infrastructure.Exceptions;
wrong namespace

2023-04-13 22:14 UTC, DawidBski commented on src/modules/example/api/Services/ExampleErrorService.cs
> +	}
Code is unreachable.

2023-04-13 22:16 UTC, mateuszgiedzinski requested changes
Ok code is more or less fine.  
One point we are creating pull request which merge changes into dev branch not main.  
This is your first PR so fine(I changed destination)  but remember to select right branch.

2023-04-13 22:16 UTC, mateuszgiedzinski commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +namespace Intive.Patronage2023.Shared.Infrastructure.Exceptions;
It should be in directory like Errors or Middlewares ( I suggest Errors). 
Also namespace must match directory structure. in this case probably it will be Intive.Patronage2023.Api.Errors

2023-04-13 22:16 UTC, mateuszgiedzinski commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (AppException error)
By default exceptions are named as ex. So use that.

2023-04-13 22:17 UTC, mateuszgiedzinski commented on src/modules/example/api/Services/ExampleErrorService.cs
> +	}
this code is fine. In task we have: "Example Error Throwing Service - an example service that shows how to throw application exceptions that will be handled by the global error handler."

2023-04-14 14:05 UTC, mateuszmuszynski requested changes

2023-04-14 14:05 UTC, mateuszmuszynski commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (FileNotFoundException error)
I don't see a use case for this exception

2023-04-14 15:17 UTC, Slashu commented on src/modules/example/api/Services/ExampleErrorService.cs
> +	}
At first I thought the same but as @mateuszgiedzinski said the task was to create non functional readme like service. Of course it would be better to have working example error service. So if we would like working one I can fix it.

2023-04-14 15:25 UTC, Slashu commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (AppException error)
Ok

2023-04-14 15:30 UTC, mateuszmuszynski commented on src/modules/example/api/Services/ExampleErrorService.cs
> +	}
Imo we should have working example or github wiki page with these examples.

2023-04-16 16:55 UTC, mateuszgiedzinski commented on src/modules/example/api/Services/ExampleErrorService.cs
> +	}
I thought that @mateuszmuszynski wanted such service. (I suggest wiki page for such cases). Ideal will be to have some kind of unit test that test us all this scenarios but in current state of our code it will be hard.

2023-04-17 15:50 UTC, Slashu commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +namespace Intive.Patronage2023.Shared.Infrastructure.Exceptions;
Done

2023-04-17 15:54 UTC, Slashu commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (FileNotFoundException error)
I could be wrong but at our last standup Damian said something about 404 error.  Of course I can just drop it

2023-04-17 15:55 UTC, Slashu commented on src/modules/example/api/Services/ExampleErrorService.cs
> +	}
So I refactored ExampleErrorService but without unit tests I'm not sure I could call it fully working example.

2023-04-18 06:52 UTC, mateuszmuszynski commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (FileNotFoundException error)
Yeah, we will return 404 for some cases but it doesn't mean it will be this specific exception. Azure Blob storage will return a different exception type. We shouldn't add a code that may be used in future. We will add it when we really need it.

2023-04-18 09:48 UTC, Slashu commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (FileNotFoundException error)
Ok, noted. I'll drop it

2023-04-19 21:07 UTC, mateuszgiedzinski requested changes

2023-04-19 21:07 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Api.Tests/Intive.Patronage2023.Example.Api.Tests.csproj
> +    <AdditionalFiles Include="..\..\..\stylecop.json" Link="stylecop.json" />
I think about importing app.props in this csproj. In that props we have specified configuration information shared across projects.

2023-04-22 22:31 UTC, mateuszgiedzinski commented on src/api/app/Helpers/ErrorHandlerMiddleware.cs
> +		catch (AppException error)
please click ResolveConversation if you fix things mentioned in comments.

2023-04-22 22:46 UTC, mateuszgiedzinski requested changes

2023-04-22 22:46 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Api.Tests/ExampleErrorServiceTests.cs
> +
new line is not needed after summary tag

2023-04-22 22:46 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Api.Tests/ExampleErrorServiceTests.cs
> +public class ExampleErrorServiceTests
Ok tests looks ok but they are not testing needed behaviour. Idealy we should have new Test project for api and we will test middleware. You can read how to do that in this article 
https://referbruv.com/blog/unit-testing-middleware-components-in-aspnet-core/?utm_content=cmp-true

2023-04-26 21:20 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Api.Tests/Intive.Patronage2023.Example.Api.Tests.csproj
> +    <AdditionalFiles Include="..\..\..\stylecop.json" Link="stylecop.json" />
app.props are still not included.

2023-04-26 21:21 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Api.Tests/ExampleErrorServiceTests.cs
> +public class ExampleErrorServiceTests
ok for now we can dismiss this. I won't block this PR.

2023-04-27 21:52 UTC, Slashu commented on tests/unit/Intive.Patronage2023.Api.Tests/Intive.Patronage2023.Example.Api.Tests.csproj
> +    <AdditionalFiles Include="..\..\..\stylecop.json" Link="stylecop.json" />
Done

2023-04-27 22:33 UTC, mateuszgiedzinski commented
Looks like merge goes wrong.

2023-05-05 17:11 UTC, closed without merging