feature/PATRO23-193 - create user in kc
intive/patronage2023-dotnet pull request #48
Opened 2023-04-16 15:40 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-193

2023-04-16 21:55 UTC, DawidBski requested changes

2023-04-16 21:55 UTC, DawidBski commented on src/api/app/Controllers/SignUpController.cs
Wrong namespace

2023-04-16 23:03 UTC, Kepeczsz approved these changes
For me it looks okay, after changing namespace like dawid suggested (I didn't change from my branch, so it's not even your fault)

2023-04-17 08:37 UTC, DawidBski approved these changes

2023-04-17 12:24 UTC, pzajaczkowski requested changes
One more thing. Could you clean up our signup/signin structure a bit?

![image](https://user-images.githubusercontent.com/82521883/232482583-85a1c064-cab4-432a-8b2c-23658cf4e5b2.png)

I think there should be similar url (/SignUp /SignIn), and userController could be renamed to SignInController etc. SignIn is already on dev so it is the best place to adjust those things :)

2023-04-17 12:24 UTC, pzajaczkowski commented on src/api/app/Controllers/SignUpController.cs
> +	private readonly IQueryBus queryBus;
I am not sure about changing it to query. We do not return any value or search for it but create new account in our system. But my thinking may be wrong.

2023-04-17 12:24 UTC, pzajaczkowski commented on src/api/app/Controllers/SignUpController.cs
> +	/// <param name="queryBus">command bus.</param>
If u decide o change to query, adjust comments

2023-04-17 12:24 UTC, pzajaczkowski commented on src/api/app/Controllers/SignUpController.cs
> +	/// <param name="query">Command.</param>
Same as above

2023-04-17 12:24 UTC, pzajaczkowski commented on src/api/app/appsettings.Development.json
>  		"public-client": true,
If we are using secret and authenticate the client, it don't has to be public anymore imo

2023-04-17 15:23 UTC, mateuszmuszynski requested changes

2023-04-17 15:23 UTC, mateuszmuszynski commented on src/api/app/Controllers/SignUpController.cs
> +			await this.queryBus.Query<CreateUser, HttpResponseMessage>(query);
We should use queries for scenarios where we would like to return data. We should use command in this case.

2023-04-17 15:23 UTC, mateuszmuszynski commented on src/api/app/Keycloak/KeycloakService.cs
> +			new KeyValuePair<string, string>("client_id", resource ?? string.Empty),
It doesn't make sense to pass empty strings to http request content.

2023-04-17 15:23 UTC, mateuszmuszynski commented on src/api/app/Keycloak/KeycloakService.cs
> +		string? resource = this.apiKeycloakSettings?.Resource;
From a business point of view it doesn't make any sense to allow nulls here. This configuration MUST exist.

2023-04-17 23:14 UTC, pzajaczkowski approved these changes
Haven't tested but it looks fine

2023-04-20 09:03 UTC, mateuszmuszynski approved these changes

2023-04-20 09:05 UTC, merged