Feature/patro23 47 add entity framework
intive/patronage2023-dotnet pull request #5
Opened 2023-03-10 12:32 UTC by a-lipert

2023-03-10 13:03 UTC, mateuszgiedzinski requested changes
How to use' instruction in README.MD is missing

2023-03-10 14:43 UTC, mateuszmuszynski requested changes

2023-03-10 14:43 UTC, mateuszmuszynski commented on src/modules/example/application/Example/GettingExamples/GetExamples.cs
> +		var examples = await this.exampleRepository.GetAll();
We shouldn't mix read and write model. Repository should be used in command handlers only. Please inject DbContext and use EF directly here.

2023-03-10 14:43 UTC, mateuszmuszynski commented on src/modules/example/domain/ExampleAggregate.cs
> +		this.CreatedOn = DateTime.Now;
We should store dates in Coordinated Universal Time. `DateTime.Now` -> `DateTime.UtcNow`

2023-03-10 14:43 UTC, mateuszmuszynski commented on src/modules/example/infrastructure/Data/AppDbContext.cs
> +	public class AppDbContext : DbContext
I would suggest to use a more specific name here (`ExampleDbContext), as we will use separate DB contexts in other modules.

2023-03-13 10:58 UTC, mateuszmuszynski requested changes

2023-03-13 10:58 UTC, mateuszmuszynski commented on src/modules/example/infrastructure/Migrations/AppDbContextModelSnapshot.cs
> +                    b.ToTable("ExampleAggregates");
Use `Example` as table name

2023-03-13 10:58 UTC, mateuszmuszynski commented on src/modules/example/infrastructure/Data/DataConfiguration/ExampleAggregateEntityConfiguration.cs
> +			builder.HasKey(x => x.Id);
Maybe we didn't stated is clearly, but the idea is that we would have separate DB context per module.

2023-03-14 00:05 UTC, mateuszgiedzinski requested changes

2023-03-14 00:05 UTC, mateuszgiedzinski commented on src/modules/example/infrastructure/Intive.Patronage2023.Modules.Example.Infrastructure.csproj
> -        <Nullable>enable</Nullable>
Ok I checked and we can ignore Nullable setting. It's by default enable in .net >=6

2023-03-15 16:08 UTC, mateuszgiedzinski requested changes

2023-03-15 19:12 UTC, a-lipert commented on Intive.Patronage2023.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{D6E10887-57DB-47DC-893B-E886DA96C51E}"
Done.

2023-03-15 19:14 UTC, a-lipert commented on README.md
> +
Done.

2023-03-15 19:15 UTC, a-lipert commented on src/api/app/Program.cs
> +builder.Services.AddExampleModule(builder.Configuration);
Done.

2023-03-16 10:45 UTC, mateuszgiedzinski approved these changes
In my opinion code review can be approved conditionally.

2023-03-16 10:45 UTC, mateuszgiedzinski commented on src/modules/example/infrastructure/Data/DataConfiguration/ExampleAggregateEntityConfiguration.cs
> +			builder.Property(x => x.CreatedOn).HasColumnName("CreatedOn");
This HasColumnName and HasMaxLength are fluent methods.  What does mean? 
Fluent method means that they returns object that called it. So if you call builder.Property(x => x.Name).HasColumnName("Name") you probably can add also call for HasMaxLength(256) like
`builder.Property(x => x.Name).HasColumnName("Name").HasMaxLength(256);`

2023-03-16 10:52 UTC, a-lipert commented on src/modules/example/infrastructure/Data/DataConfiguration/ExampleAggregateEntityConfiguration.cs
> +			builder.Property(x => x.CreatedOn).HasColumnName("CreatedOn");
Got it. You're right. Should I change that and commit again?

2023-03-16 13:06 UTC, merged