Feature/patro23-226 create budget validator
intive/patronage2023-dotnet pull request #50
Opened 2023-04-19 15:53 UTC by a-lipert

https://tracker.intive.com/jira/browse/PATRO23-226

2023-04-23 20:28 UTC, mateuszgiedzinski commented
Ok for now code review can't be performed because of too many changes between dev and this branch. We need to wait for CreateBudgetAggregate changes.

2023-04-24 15:49 UTC, mateuszmuszynski requested changes

2023-04-24 15:49 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +public record CreateBudget(Guid Id, string Name, Guid UserId, Money Limit, Period Period, string Description, string IconName, IQueryBus QueryBus) : ICommand;
We shouldn't include query bus in command body.

2023-04-24 15:49 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Domain/Rules/BudgetNameUniquenessBusinessRule.cs
> +	public BudgetNameUniquenessBusinessRule(IQueryBus queryBus, BudgetDbContext budgetDbContext, IExecutionContextAccessor executionContextAccessor, string name)
Query bus is not used.

2023-04-25 13:23 UTC, a-lipert commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +public record CreateBudget(Guid Id, string Name, Guid UserId, Money Limit, Period Period, string Description, string IconName, IQueryBus QueryBus) : ICommand;
Sorry, I misunderstood the requirements.

2023-04-25 22:52 UTC, pzajaczkowski requested changes
I remember Mateusz G, saying something about grouping usings, to keep things more readable. That's why there were empty lines probably. Idk if it is intentional that you deleted them tho.

2023-04-25 22:52 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudgetValidator.cs
> +		return !anyExistingBudget;
This negation is confusing. Method is called AnyExisitngBudget but it returns true when there aren't any matching results xD. Try to move this negation or rename method pls. Additionaly you can pass cancelation to this method and then AnyAsync.

2023-04-26 10:17 UTC, pzajaczkowski approved these changes

2023-04-26 17:28 UTC, mateuszmuszynski requested changes

2023-04-26 17:28 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudgetValidator.cs
> +		.NotEmpty()
Format code

2023-04-26 18:01 UTC, mateuszmuszynski approved these changes

2023-04-26 18:12 UTC, DawidBski approved these changes

2023-04-26 18:13 UTC, merged