feature/PATRO23-231 - create new income and expense
intive/patronage2023-dotnet pull request #51
Opened 2023-04-20 22:12 UTC by Kepeczsz

https://tracker.intive.com/jira/browse/PATRO23-229
https://tracker.intive.com/jira/browse/PATRO23-231

2023-04-20 22:14 UTC, DawidBski approved these changes

2023-04-20 23:18 UTC, mateuszgiedzinski requested changes

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/BudgetDbContext.cs
> +		var transactionIdConverter = new ValueConverter<TransactionId, Guid>(
I don't like mess in this method. Maybe we can put those value converters in some place. For example we can have some static factory for this converters or have some base class for entity configuration.

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/BudgetDbContext.cs
> +		transactionAggregate.HasKey(e => e.TransactionId);
create TransactionAggregateEntityConfiguration class.

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/BudgetDbContext.cs
> +		budgetAggregate.Property(e => e.BudgetId)
move it to budget aggregate entity configuration

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Domain/BudgetTransactionRepository.cs
> +		this.HandleEvents(budgetTransaction.UncommittedEvents);
@mateuszmuszynski  I think we should clear this list of uncommited events am I right?

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Intive.Patronage2023.Shared.Infrastructure.csproj
> +	  <Compile Remove="Nowy folder\**" />
remove this

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Helpers/TransactionTypes.cs
> +	Expense,
needs number

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Helpers/TransactionTypes.cs
> +/// Enum of Income or Expense Choice.
what will happen with description if there will be third transaction type?

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Migrations/20230417221414_BudgetTransactions.cs
> +public partial class BudgetTransactions : Migration
I don't like this name. https://zzzcode.ai/answer-question?id=3a9432da-4a82-4914-8a1c-4678994cda4f
Better: AddBudgetTransactions
The best: AddBudgetTransactionTable

2023-04-20 23:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Migrations/20230417221414_BudgetTransactions.cs
> +			name: "TransactionStore",
Table name is not consistent with aggregate name.

2023-04-21 15:21 UTC, Kepeczsz commented on src/shared/infrastructure/Helpers/TransactionTypes.cs
> +/// Enum of Income or Expense Choice.
It is temporary solution, because we don't know yet how many transaction types will be as suggested on retro, it could be even single string, for now we have enum and  validation for this enum, if user puts number or name that doesn't exist in our enum, it will be marked as error.
![image](https://user-images.githubusercontent.com/52294433/233673466-be59553f-42f5-4cde-ab63-42db597ee837.png)

2023-04-22 14:45 UTC, AlanP22 approved these changes

2023-04-22 17:20 UTC, DawidBski commented on src/modules/budget/infrastructure/Domain/BudgetTransactionRepository.cs
> +		this.HandleEvents(budgetTransaction.UncommittedEvents);
@mateuszgiedzinski  Can we resolve this conversation or wait for the @mateuszmuszynski answer?

2023-04-22 17:29 UTC, DawidBski commented on src/shared/infrastructure/Helpers/TransactionTypes.cs
> +/// Enum of Income or Expense Choice.
Should we change description to: Enum of Budget Transaction Types?

2023-04-22 23:06 UTC, mateuszgiedzinski requested changes

2023-04-22 23:06 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Domain/BudgetTransactionRepository.cs
> +		this.HandleEvents(budgetTransaction.UncommittedEvents);
I've asked him to check this.

2023-04-22 23:06 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Helpers/TransactionTypes.cs
> +/// Enum of Income or Expense Choice.
Enumeration of budget transaction types.

2023-04-22 23:06 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Commands/MediatRCommandHandlerAdapter.cs
> +		await this.inner.Handle(command, cancellationToken);
Is it necessary to await here? I don't think so.

2023-04-23 07:43 UTC, DawidBski commented on src/shared/infrastructure/Commands/MediatRCommandHandlerAdapter.cs
> +		await this.inner.Handle(command, cancellationToken);
It's my fault. I tested something and forgot to roll changes back.

2023-04-23 11:24 UTC, Kepeczsz commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.HasKey(x => x.BudgetId);
My reason for making it BudgetId, was to have one convention about naming Ids.

2023-04-24 11:30 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Domain/BudgetTransactionRepository.cs
> +		this.HandleEvents(budgetTransaction.UncommittedEvents);
It's not a problem as long as we don't call Persist on the aggregate twice.

2023-04-24 15:25 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.HasKey(x => x.BudgetId);
Imo it's a bit confusing. Id is a primary key and we know it uniquely identifies entity. We should use [Entity Name]Id for foreign keys.

2023-04-24 17:16 UTC, mateuszmuszynski requested changes

2023-04-24 19:11 UTC, Kepeczsz commented on src/modules/budget/application/Budget/CreatingBudgetTransaction/CreateBudgetTransaction.cs
> +		decimal transactionValue = command.Type == TransactionTypes.Expense ? (command.Value * -1) : command.Value;
This approach was used, so when after values woule be in database, we could use sum on column and it would be one query. They can pass only positive values, but we  handle it before saving it.

2023-04-24 19:15 UTC, Kepeczsz commented on src/modules/budget/application/Budget/CreatingBudgetTransaction/CreateBudgetTransaction.cs
> +		decimal transactionValue = command.Type == TransactionTypes.Expense ? (command.Value * -1) : command.Value;
We could remove it  add to validation that expense should be under 0 and user could write minus by himself, but it would be confusing in my opinion

2023-04-26 11:08 UTC, pzajaczkowski requested changes

2023-04-26 11:08 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +	public GetBudgetTransactionValidator()
As i can see BudgetId isn't verified until query in db, so even if we give not existing id, it will return empty list instead of error code respone. Do i understand correctly?

2023-04-26 11:19 UTC, a-lipert commented on src/modules/budget/application/Budget/CreatingBudgetTransaction/CreateBudgetTransactionValidator.cs
> +	private async Task<bool> IsBudgetExists(Guid budgetGuid, CancellationToken cancellationToken)
I agree, it looks weird because it's not even correct in English (maybe a typo? ;) )

2023-04-26 11:38 UTC, Kepeczsz commented on docker-compose.dcproj
hmm, it propably sneaked in with merge request that i have done today, i will remove it.

2023-04-26 11:49 UTC, Kepeczsz commented on src/modules/budget/application/Budget/CreatingBudgetTransaction/CreateBudgetTransactionValidator.cs
> +	private async Task<bool> IsBudgetExists(Guid budgetGuid, CancellationToken cancellationToken)
it is convention that methods and variables that returns bool, have prefix - is

2023-04-26 11:50 UTC, Kepeczsz commented on src/modules/budget/infrastructure/Migrations/20230403152847_BudgetMigration.Designer.cs
well, we need new migration that, that changes type of Id in database with old migrations existing, project would not start up.

2023-04-26 12:10 UTC, Kepeczsz commented on docker-compose.dcproj
it is from merging dev, it was added after changing paths to docker.

2023-04-26 12:11 UTC, Kepeczsz commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +	public GetBudgetTransactionValidator()
you are right, i have added validation.

2023-04-26 21:18 UTC, mateuszgiedzinski requested changes

2023-04-26 21:18 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Migrations/20230419151012_NewBudgetAggregate.cs
> -using Microsoft.EntityFrameworkCore.Migrations;
never do that. I don't know what was the reason to remove migration but this will broke our dev and prod environment. 
If you really need to recreate table you need two migrations + some script in it to copy the data.

2023-04-26 21:18 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Helpers/CategoryType.cs
> +public enum CategoryType
it's perfectly fit for budget module.

2023-04-26 21:18 UTC, mateuszgiedzinski commented on src/shared/infrastructure/Helpers/TransactionType.cs
> +namespace Intive.Patronage2023.Shared.Infrastructure.Helpers;
it's perfectly fit for budget module.

2023-04-27 09:26 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Migrations/20230403152847_BudgetMigration.Designer.cs
we cannot delete migrations that are applied on dev/staging

2023-04-27 15:33 UTC, a-lipert requested changes

2023-04-27 15:33 UTC, a-lipert commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		Guid transactionId = command.Id == default ? Guid.NewGuid() : command.Id;
Its better to use var as you use it everywhere to be consistent.

2023-04-27 15:33 UTC, a-lipert commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> CreateNewTransaction([FromRoute] Guid budgetId, [FromBody] CreateTransaction command)
Wouldn't it be easier put budgetId inside of command? Then you can make it nullable and have better validation and easier usage for frontend.

2023-04-27 15:33 UTC, a-lipert commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> GetTransactionByBudgetId([FromRoute] Guid budgetId, [FromBody] GetPageSizeAndPageIndex request)
Maybe use GetBudgetTransaction directly as a body? Less code, less stuff to maintain.

2023-04-27 15:33 UTC, a-lipert commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +		var id = new BudgetId(command.Id);
What is the added value of BudgetId instead of directly using Guid?

2023-04-27 15:33 UTC, a-lipert commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +		if (budget == null)
If statement can be replaced by `return budget != null;`

2023-04-27 15:33 UTC, a-lipert commented on src/modules/budget/contracts/ValueObjects/BudgetConverters.cs
> +	public static ValueConverter TransactionIdConverter() => new ValueConverter<TransactionId, Guid>(
If we would use Guid directly instead of different type per entity we would have only one converter. Maintenance might be a problem if we grow number of entities.

After thinking there would be no converters at all, right?

2023-04-27 15:34 UTC, mateuszmuszynski requested changes

2023-04-27 15:34 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/CreatingBudgetTransaction/BudgetTransactionInfo.cs
> +namespace Intive.Patronage2023.Modules.Budget.Application.Budget.CreatingBudgetTransaction;
This should be moved to GettingBudgetTransactions directory

2023-04-27 15:34 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransaction.cs
> +public class GetTransactionQueryHandler : IQueryHandler<GetBudgetTransaction, PagedList<BudgetTransactionInfo>>
We return list of transactions here. Plase rename to GetTransaction**s**QueryHandler, GetBudgetTransaction**s**

2023-04-27 15:34 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetPageSizeAndPageIndex.cs
> +public record GetPageSizeAndPageIndex(int PageSize, int PageIndex);
Rename to something budget transaction related or move to shared resources.

2023-04-27 15:34 UTC, mateuszmuszynski commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
Why it is removed?

2023-04-27 15:46 UTC, Kepeczsz commented on src/modules/budget/contracts/ValueObjects/BudgetConverters.cs
> +	public static ValueConverter TransactionIdConverter() => new ValueConverter<TransactionId, Guid>(
if we would stick to Guid instead of value Object, converters, would not be needed. 
Every entity, with their own Id, should have converter and value object to represent it(Id). I do not know how performance of that approach looks like, but it prevents making a mistakes, while writing a code, because u need to declare your id, as value object.

2023-04-27 15:58 UTC, Kepeczsz commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> GetTransactionByBudgetId([FromRoute] Guid budgetId, [FromBody] GetPageSizeAndPageIndex request)
It corresponds to having [HttpPost("{budgetId:guid}/transactions")], we had approach that u mentioned, but had to change it, so we can return value at this url specified in  HttpPost in line 202

2023-04-27 16:17 UTC, DawidBski commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
It is not removed just marked as unverioned when i commit changes.

2023-04-27 16:29 UTC, a-lipert commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactionValidator.cs
> +		if (budget == null)
In this case we compare budget to null which actually returns true or false - not the budget itself.

2023-04-27 16:34 UTC, a-lipert commented on src/modules/budget/contracts/ValueObjects/BudgetConverters.cs
> +	public static ValueConverter TransactionIdConverter() => new ValueConverter<TransactionId, Guid>(
@mateuszmuszynski @mateuszgiedzinski what do you think about it? In my opinion this is a bit of overengineering and such mistakes (if happen) can be easily caught during reviews.

2023-04-27 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +		var id = new BudgetId(command.Id);
@a-lipert  Lets consider that method 
`public GetBudgetTransaction (Guid budgetId, Guid budgetTransactionId)`
imagine that you have from api those values and call this as GetBudgetTransaction(budgetId, budgetTransactionId);
For now all fine. 
Then you have requirement that you can get only budget for given user ( userId is another Guid). You start coding. 
First you changed call to this 
`GetBudgetTransaction(budgetId, budgetTransactionId, userId);`
Then you change method
`public GetBudgetTransaction (Guid budgetId, Guid userId,  Guid budgetTransactionId)`
everything is fine. Code will compile. But the method call is invalid. This is just example but imagine if you will use this method couple of time or even hundreds and only one call is invalid? 
To prevent that bugs someone smart propose wrapping Guids. Changed method will look like 
`public GetBudgetTransaction (BudgetId budgetId, UserId userId,  BudgetTransactionId budgetTransactionId)`
and this call if budgetId, budgetTransactionId, userId are wrapped Guids
`GetBudgetTransaction(budgetId, budgetTransactionId, userId);`  produce compilation error. So we won't produce any bug.

2023-04-27 21:56 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +		var id = new BudgetId(command.Id);
If my explanation is clear @a-lipert  please click resolve :)

2023-04-27 22:10 UTC, mateuszgiedzinski commented on src/modules/budget/contracts/ValueObjects/BudgetConverters.cs
> +	public static ValueConverter TransactionIdConverter() => new ValueConverter<TransactionId, Guid>(
https://www.youtube.com/watch?v=LdrMdIabE1o
I think the same.  It's just to avoid mistakes. it's look like overengineering but at the end it protects from loosing money and time because of bugs.

2023-04-28 05:29 UTC, mateuszmuszynski approved these changes

2023-04-28 05:35 UTC, a-lipert commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +		var id = new BudgetId(command.Id);
Thanks for the detailed explanation :)

2023-04-28 05:38 UTC, a-lipert approved these changes
Thanks for the explanation of the aspects that were not obvious :)

2023-04-28 09:15 UTC, pzajaczkowski approved these changes

2023-04-28 15:35 UTC, mateuszgiedzinski approved these changes

2023-04-28 15:55 UTC, Kepeczsz commented on tests/unit/Intive.Patronage2023.Budget.Domain.Tests/BudgetAggregateTests.cs
>  using Bogus;
We will create tests on saturday.

2023-04-28 15:59 UTC, merged