Bug/applicationinsights - error
intive/patronage2023-dotnet pull request #53
Opened 2023-04-22 14:53 UTC by Kepeczsz

2023-04-22 17:10 UTC, DawidBski commented on src/api/app/appsettings.json
> +		"APPLICATIONINSIGHTS_CONNECTION_STRING": ""
Why did u add it here?

2023-04-22 22:09 UTC, mateuszgiedzinski requested changes

2023-04-22 22:09 UTC, mateuszgiedzinski commented on src/api/app/appsettings.json
> +		"APPLICATIONINSIGHTS_CONNECTION_STRING": ""
For now it doesn't matter if it will be on developement or appsettings only file. One setting overrides other. I think it is nice to have it here.

2023-04-22 22:09 UTC, mateuszgiedzinski commented on src/api/app/appsettings.Development.json
> +		"APPLICATIONINSIGHTS_CONNECTION_STRING": ""
only in one place it is needed.

2023-04-22 22:09 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
>  builder.Logging.AddFilter<ApplicationInsightsLoggerProvider>("category", LogLevel.Trace);
this line should also be in if scope.

2023-04-23 07:15 UTC, DawidBski commented on src/api/app/appsettings.json
> +		"APPLICATIONINSIGHTS_CONNECTION_STRING": ""
I've just meant the same, like you here.
![image](https://user-images.githubusercontent.com/127483473/233825511-4767a68c-55f3-4263-b10f-3b13707a902f.png)

2023-04-23 07:16 UTC, DawidBski approved these changes

2023-04-23 11:43 UTC, pzajaczkowski approved these changes

2023-04-23 11:49 UTC, mateuszgiedzinski approved these changes

2023-04-23 12:36 UTC, merged