feature/PATRO23-206 - add DateTimeProvider.
intive/patronage2023-dotnet pull request #54
Opened 2023-04-22 21:26 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-206

2023-04-22 22:28 UTC, mateuszgiedzinski requested changes

2023-04-22 22:28 UTC, mateuszgiedzinski commented on src/shared/abstractions/DateTimeProvider.cs
> +	public DateTime LocalNow()
Methods are fine but in C# we can specify it as getter.

2023-04-22 22:28 UTC, mateuszgiedzinski commented on src/shared/abstractions/IDateTimeProvider.cs
> +	DateTime UtcNow();
DateTime UtcNow {get;} maybe?

2023-04-22 22:28 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Example.Application.Tests/DateTimeProviderTests.cs
> +		var dateTimeProvider = new Mock<IDateTimeProvider>();
Test must be rewritten. 
First of all in test we don't want mock tested provider. Setup tested instance in test class ctor. 
If you need to test if settimezone works fine you can first get utc then get local and then convert utc to local by your own as you did. And in comparison you can use fluent assertion and this method 
.Should().BeCloseTo()

2023-04-22 22:28 UTC, mateuszgiedzinski commented on src/shared/abstractions/DateTimeProvider.cs
> +public class DateTimeProvider : IDateTimeProvider
hmm as far as I know implementation shouldn't be part of abstraction project.

2023-04-23 16:24 UTC, AlanP22 commented on src/shared/infrastructure/SharedModule.cs
> +		services.AddSingleton<IDateTimeProvider, DateTimeProvider>();
Shouldn't it be better to add it as scoped?

2023-04-23 17:26 UTC, IzabelaPalubicka commented on src/shared/infrastructure/SharedModule.cs
> +		services.AddSingleton<IDateTimeProvider, DateTimeProvider>();
Why do you think that?

2023-04-23 20:23 UTC, mateuszgiedzinski commented on src/shared/infrastructure/SharedModule.cs
> +		services.AddSingleton<IDateTimeProvider, DateTimeProvider>();
For now it could be singleton. In the future it should be Scoped to set the timezone.

2023-04-23 20:25 UTC, mateuszgiedzinski approved these changes

2023-04-24 11:40 UTC, merged