feature/PATRO23-227 - budget details basic information
intive/patronage2023-dotnet pull request #57
Opened 2023-04-24 13:15 UTC by pzajaczkowski

https://tracker.intive.com/jira/browse/PATRO23-227

Draft because of not implemented yet tests.

2023-04-24 15:18 UTC, IzabelaPalubicka commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		var validationResult = await this.getBudgetDetailsValidator.ValidateAsync(request);
You can change it to ValidateAndThrowAsync(request), then you don't have to check it was valid and throw exception.

2023-04-24 15:19 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateBudgetDetailsInfoMapper.cs
> +			Currency = entity.Limit.Currency.ToString(),
In auto mapper you can add a [method to convert value.](https://docs.automapper.org/en/stable/Value-converters.html)

2023-04-24 16:51 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetDetails/GetBudgetDetails.cs
> +		var budget = await this.budgetDbContext.Budget.FindAsync(new object?[] { query.Id }, cancellationToken: cancellationToken);
As far as i know FindAsync is more efficient when searching by primary key. It looks wild because i wanted to pass cancelationToken, and this method can take many primary keys, so i had to use `new object?[] { query.Id }`.

2023-04-25 08:47 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetDetails/GetBudgetDetails.cs
> +		return budget is null ? null : BudgetAggregateBudgetDetailsInfoMapper.Map(budget);
I'm not using extension method,  because i want our structure to be consistent i.e. all mappers in same form and place.

2023-04-25 08:49 UTC, pzajaczkowski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		var validationResult = await this.getBudgetDetailsValidator.ValidateAsync(request);
We have Validation Pipeline task, so it is going to be removed in future anyways. But good idea to keep things cleaner. But i am not going to change it for now to keep structure consistent.

2023-04-25 08:52 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateBudgetDetailsInfoMapper.cs
> +	public static BudgetDetailsInfo Map(BudgetAggregate entity) =>
As i mentioned few comments earlier, I want it to be consistent with rest of the project. Unless we decide otherwise.

2023-04-25 09:19 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateBudgetDetailsInfoMapper.cs
> +			Currency = entity.Limit.Currency.ToString(),
Explained in previous conversation.

2023-04-26 13:14 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetDetails/BudgetDetailsInfo.cs
You can read requirements channel. They use timestamp so that's what i've provided

2023-04-26 17:29 UTC, Kepeczsz approved these changes

2023-04-26 18:05 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetDetails/GetBudgetDetails.cs
> +	public async Task<BudgetDetailsInfo?> Handle(GetBudgetDetails query, CancellationToken cancellationToken)
looks good. We should use repository on write side only.

2023-04-26 18:18 UTC, IzabelaPalubicka approved these changes

2023-04-26 18:19 UTC, a-lipert approved these changes

2023-04-26 20:08 UTC, mateuszgiedzinski requested changes

2023-04-26 20:08 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/Mappers/BudgetAggregateBudgetDetailsInfoMapper.cs
> +			EndDate = entity.Period.EndDate.ToTimestamp(),
as we discussed change to DateTIme

2023-04-26 20:08 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/Intive.Patronage2023.Budget.Application.Tests.csproj
> +
Import app.props  missing.

2023-04-26 20:12 UTC, mateuszgiedzinski requested changes

2023-04-26 20:12 UTC, mateuszgiedzinski commented on src/api/app/User/Queries/SignUpHandler.cs
> -using Intive.Patronage2023.Api.Keycloak;
Change out of scope of your task. In real world projects we rather creating technical debt tasks and we do the changes  under that task. Do not revert this but remember.

2023-04-27 14:02 UTC, mateuszgiedzinski requested changes

2023-04-28 05:32 UTC, mateuszmuszynski approved these changes

2023-04-28 09:40 UTC, mateuszgiedzinski approved these changes

2023-04-28 09:41 UTC, merged