feature/PATRO23-159 - change docker csproj location and clean dockerfile
intive/patronage2023-dotnet pull request #58
Opened 2023-04-24 15:59 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-159

2023-04-24 20:59 UTC, IzabelaPalubicka commented
Looking good 👍

2023-04-24 20:59 UTC, IzabelaPalubicka approved these changes

2023-04-25 06:08 UTC, LukaszWinowicz approved these changes

2023-04-25 08:55 UTC, mateuszmuszynski approved these changes

2023-04-25 09:00 UTC, DawidBski commented
> Hope you

2023-04-25 11:04 UTC, Kepeczsz approved these changes

2023-04-25 13:06 UTC, merged

2023-04-25 13:16 UTC, pzajaczkowski requested changes
We still have problem with docker-compose being on second place in build-order. Could you fix it? And also shouldn't this folder "docker" be added as solution project so we can see it in solution view? Same as modules shared tests api. (To be clear i tested it on freshly cloned repo)

![image](https://user-images.githubusercontent.com/82521883/234288600-842a992d-5512-44df-b462-0747e2543b4b.png)

![image](https://user-images.githubusercontent.com/82521883/234287374-eb02d77e-2fba-4e1e-96c7-8b6c8fa16b32.png)

And also i tested if keycloak uses this db we create for it in sql server. And it's not using it. So maybe we can delete this script and clean docker-compose a liitle.

![image](https://user-images.githubusercontent.com/82521883/234287690-e1848fba-0053-455a-8321-8c9a32d98400.png)