Feature/patro23-240-setup-azurite-container
intive/patronage2023-dotnet pull request #60
Opened 2023-04-25 13:30 UTC by AlanP22

https://tracker.intive.com/jira/browse/PATRO23-240

2023-04-25 22:38 UTC, pzajaczkowski requested changes
If it works that's good. Just remove your ide files and check encodings or other reasons why your changes marked whole files as changed.

2023-04-25 22:38 UTC, pzajaczkowski commented on .idea/.idea.Intive.Patronage2023/.idea/.gitignore
None of this files from .idea folder should be commited and pushed. Check if git ignores this folder if not maybe add directory to .idea.

2023-04-25 22:38 UTC, pzajaczkowski commented on .idea/.idea.Intive.Patronage2023/.idea/encodings.xml
remove

2023-04-25 22:38 UTC, pzajaczkowski commented on .idea/.idea.Intive.Patronage2023/.idea/indexLayout.xml
remove

2023-04-25 22:38 UTC, pzajaczkowski commented on .idea/.idea.Intive.Patronage2023/.idea/vcs.xml
remove

2023-04-25 22:38 UTC, pzajaczkowski commented on docker-compose.override.yml
Why is there whole file marked as changed? Maybe your file encoding is different or sth.

2023-04-26 18:07 UTC, DawidBski requested changes

2023-04-26 18:07 UTC, DawidBski commented on docker-compose.override.yml
> +    image: mcr.microsoft.com/azure-storage/azurite
I think it shouldn't be in docker-compose.override.yml especially if you put it in docker-compose.yml
![image](https://user-images.githubusercontent.com/127483473/234664736-114c5173-fe41-4f85-869d-cf1e2e3f6e3e.png)

2023-04-26 20:17 UTC, mateuszgiedzinski commented on docker-compose.override.yml
> +    image: mcr.microsoft.com/azure-storage/azurite
indeed

2023-04-26 20:18 UTC, mateuszgiedzinski commented on .idea/.idea.Intive.Patronage2023/.idea/vcs.xml
please add .idea to gitignore file as in this gitignore
https://github.com/intive/patronage22-dotnet-bialystok/blob/master/.gitignore

2023-04-26 20:20 UTC, mateuszgiedzinski commented on .idea/.idea.Intive.Patronage2023/.idea/vcs.xml
But before you need remove whole idea directory.

2023-05-10 13:46 UTC, pzajaczkowski approved these changes

2023-05-10 15:08 UTC, mateuszgiedzinski requested changes

2023-05-10 15:08 UTC, mateuszgiedzinski commented on docker/docker-compose.override.yml
> +    container_name: "azurite"
I think we put container name in docker-compose.yml. Here we have only environment specific config.  So everything is fine except container_name.

2023-05-10 15:52 UTC, mateuszgiedzinski approved these changes

2023-05-10 16:02 UTC, mateuszgiedzinski requested changes

2023-05-10 16:02 UTC, mateuszgiedzinski commented on docker/docker-compose.override.yml
> +      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
fix paths

2023-05-10 16:52 UTC, DawidBski approved these changes

2023-05-12 13:51 UTC, AlanP22 commented on docker/docker-compose.override.yml
> +      - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
done

2023-05-12 14:59 UTC, mateuszgiedzinski approved these changes

2023-05-12 15:02 UTC, merged