Feature/patro23 123 add database integration testes
intive/patronage2023-dotnet pull request #63
Opened 2023-04-27 19:07 UTC by KlaudiaGajocha

Database Integration Testes

2023-04-28 10:14 UTC, mateuszmuszynski submitted a review, later dismissed

2023-04-28 10:14 UTC, mateuszmuszynski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/DatabaseFixtures.cs
> +using DotNet.Testcontainers.Builders;
Move classes to separate files

2023-05-02 11:04 UTC, mateuszgiedzinski requested changes

2023-05-02 11:04 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/MySQLTests.cs
> +public class MsSqlTests : IAsyncLifetime
The file has not the same name as class.

2023-05-02 11:04 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +		var dbContext = scope.ServiceProvider.GetService<BudgetDbContext>();
You can use GetRequiredService here?

2023-05-02 11:04 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/MySQLTests.cs
> +	public Task InitializeAsync()
missing summary tag

2023-05-02 11:04 UTC, mateuszgiedzinski commented on src/api/app/Program.partial.cs
> +/// Docs.
invalid description of Program class.

2023-05-07 11:15 UTC, KlaudiaGajocha commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +		var dbContext = scope.ServiceProvider.GetService<BudgetDbContext>();
Good clue, thanks!

2023-05-07 14:52 UTC, DawidBski approved these changes
Some descriptions still missing but you've got my approve.

2023-05-07 14:52 UTC, DawidBski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +
missing summary tag

2023-05-07 14:52 UTC, DawidBski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +		public CustomWebApplicationFactory(MsSqlTests fixture)
missing summary tag

2023-05-07 14:52 UTC, DawidBski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/MySQLTests.cs
> +
Maybe a short description here.

2023-05-07 17:57 UTC, mateuszgiedzinski requested changes

2023-05-07 17:57 UTC, mateuszgiedzinski commented on src/api/app/appsettings.json
> +
line break not necessary

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +	///
empty line not needed.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +	}
Empty line needed.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +	///
empty line not needed.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +	///<summary>
Empty line needed.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +	///<summary>
empty line needed after method declaration.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/ExampleTests.cs
> +public class IntegrationTests : IClassFixture<MsSqlTests>, IDisposable
Class not match file name.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/MySQLTests.cs
> +	public const string Database = "patronage2023";
missing summary tag for public visible consts.

2023-05-07 17:57 UTC, mateuszgiedzinski commented on app.props
> -		<!-- Enable raising errors due not clean source code -->
Of course these should not be deleted and all fixes should be done if any occurs.

2023-05-08 12:50 UTC, mateuszgiedzinski requested changes

2023-05-08 12:50 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/IntegrationTests.cs
> +
empty line not needed

2023-05-08 12:50 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/IntegrationTests.cs
> +
empty line not needed after summary tag. Please check all tags.

2023-05-08 12:50 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Modules.Example.Application.IntegrationTests/Intive.Patronage2023.Modules.Example.Application.IntegrationTests.csproj
> +
app.props Import missing as it is in other projects.

2023-05-08 12:50 UTC, mateuszgiedzinski requested changes

2023-05-08 12:50 UTC, mateuszgiedzinski commented on Intive.Patronage2023.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "integration", "integration", "{505B0B82-9C7C-4A23-8BA3-A4F49BC2C0AB}"
Please merge dev and resolve conflict.

2023-05-08 22:18 UTC, mateuszgiedzinski approved these changes

2023-05-08 22:23 UTC, merged