Bugfix/PATRO23-33 add budget icon to list of budgets
intive/patronage2023-dotnet pull request #64
Opened 2023-04-27 19:52 UTC by a-lipert

2023-04-27 20:08 UTC, IzabelaPalubicka approved these changes

2023-04-27 21:33 UTC, mateuszgiedzinski requested changes

2023-04-27 21:33 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetAggregate.cs
> -	public string? Icon { get; private set; }
Migration missing

2023-04-28 05:55 UTC, a-lipert commented on src/modules/budget/domain/BudgetAggregate.cs
> -	public string? Icon { get; private set; }
Done

2023-04-28 05:56 UTC, mateuszmuszynski approved these changes

2023-04-28 11:46 UTC, mateuszgiedzinski approved these changes

2023-04-28 11:49 UTC, merged