feature/PATRO23-106 - add base repository class
intive/patronage2023-dotnet pull request #65
Opened 2023-04-28 14:07 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-106

2023-04-30 09:56 UTC, pzajaczkowski requested changes
I think that you should also make BudgetRepository and BudgetTransactionRepository use this base repository. It is out of scope probably becouse task was written before our implementation of Budget module ;)

2023-04-30 09:56 UTC, pzajaczkowski commented on src/shared/domain/Intive.Patronage2023.Shared.Domain.csproj
Missing app props and stylecop?

2023-04-30 09:56 UTC, pzajaczkowski commented on src/shared/infrastructure/BaseRepository.cs
> +	public async Task<T> GetById(TKey id) => await this.dbContext.Set<T>().FirstAsync(x => x.Id!.Equals(id));
First will throw exception when not found. I think we should use firstordefaultasync or even more efficient findasync. Although it can be problematic when we will search for entity with 2 primary keys.

2023-05-02 11:22 UTC, mateuszgiedzinski commented on src/shared/infrastructure/BaseRepository.cs
> +	public async Task<T> GetById(TKey id) => await this.dbContext.Set<T>().FirstAsync(x => x.Id!.Equals(id));
@IzabelaPalubicka  Change it to FirstOrDefaultAsync. FindAsync internally look for two rows for given key so I'm not sure it will be as efficient as FirstOrDefaultAsync.  EF with Find looking for duplicated keys. We are using MS Sql server database  which are taking care about key uniqueness. So in this case FirstOrDefaultAsync will be faster it's not that much difference but it's nice to know that Find creates Select Top (2) query but FirstOrDefault Select Top (1).

2023-05-03 12:33 UTC, mateuszgiedzinski requested changes

2023-05-03 12:33 UTC, mateuszgiedzinski commented on src/modules/example/infrastructure/Migrations/20230503102954_ExampleId.cs
> +public partial class ExampleId : Migration
I suggest change the name of this transaction to AddStronglyTypedExampleId.

2023-05-03 12:33 UTC, mateuszgiedzinski commented on src/shared/abstractions/Domain/IRepository.cs
> +#nullable enable
Enabling nullable not needed. It is enable by default.

2023-05-03 12:33 UTC, mateuszgiedzinski commented on tests/architecture/ComponentNamingTests.cs
> +		typeof(CreateBudgetTransaction).Assembly)
this two assemblies are the same. We should use only one. 
typeof(CreateBudget).Assembly,
typeof(CreateBudgetTransaction).Assembly 
Assembly = csproj.

2023-05-03 19:18 UTC, IzabelaPalubicka commented on src/modules/example/infrastructure/Migrations/20230503102954_ExampleId.cs
> +public partial class ExampleId : Migration
This migration was empty, I removed it.

2023-05-04 08:28 UTC, mateuszgiedzinski approved these changes

2023-05-04 10:48 UTC, pzajaczkowski approved these changes

2023-05-04 10:51 UTC, merged