feature/PATRO23-231-229 - add tests
intive/patronage2023-dotnet pull request #67
Opened 2023-04-29 20:10 UTC by DawidBski

2023-04-30 09:39 UTC, pzajaczkowski requested changes

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	/// Validator should return false when all properties are valid.
`/// Validator should return false when budget with given id does not exist in database.`

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	public void Validator_WhenBudgetIdNotExistedInDatabase_ShouldReturnFalse()
WhenBudgetIdDoesNotExistInDatabase

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +		decimal value = new Faker().Random.Decimal(19, 4);
Max mistaken for min?

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +		if (type == TransactionType.Expense)
Again i'm not sure about this approach, but not as important as in previous test.  Looking at the fact that you are testing case with bad budget id, you can even hardcode transaction type to Income and leave value positive.

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +		decimal value = new Faker().Random.Decimal(19, 4);
same?

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +		decimal value = new Faker().Random.Decimal(19, 4);
same?

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +		var createdDate = new Faker().Date.Recent();
shouldn't it be called transactionDate? Also recent .Recent() returns random DateTime within the last few dates. How are you going to check error if this value will never be Older than month?

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/GetBudgetTransactionsValidatorTests.cs
> +	public void Validator_WhenBudgetIdNotExistingInDatabase_ShouldReturnFalse()
Let's keep naming similar -> WhenBudgetIdDoesNotExistInDatabase

2023-04-30 09:39 UTC, pzajaczkowski commented on tests/unit/Intive.Patronage2023.Budget.Domain.Tests/BudgetTransactionAggregateTests.cs
> +		decimal value = new Faker().Random.Decimal(19, 4);
same

2023-04-30 10:06 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionCommandHandlerTests.cs
> +		decimal value = new Faker().Random.Decimal(19, 4);
I thought it is just decimal(19, 4) not decimal(min,  max). I've just read about it. I'll change that.

2023-04-30 10:41 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionCommandHandlerTests.cs
> +		if (type == TransactionType.Expense)
I did it this way because it generates the type randomly. For income, the value has to be positive, while for expenses, it has to be negative. I check this in separate tests for income with positive values and for expenses with negative values.

2023-04-30 11:29 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	/// Validator should return false when all properties are valid.
This comment was copied, pasted and not fully checked properly.

2023-04-30 11:30 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +		var createdDate = new Faker().Date.Recent();
Good point.

2023-05-02 11:51 UTC, mateuszgiedzinski requested changes

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionCommandHandlerTests.cs
> +		decimal value = new Faker().Random.Decimal(19, 4);
Resolve it when you fix it not before.

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionCommandHandlerTests.cs
> +	public async void Handle_WhenCalled_ShouldCreateBudgetTransactionWithCorrectValues()
Test name should be like <CalledMethod>_When<Condition under which you call method_Should<Expected result>
for example
Handle_WhenValidCommandWithIncomePassed_ShouldCreateBudgetTransaction.
This give you possibility to specify more tests because one thing that you need to change is input and expected result. Also All tests created like that gives you knowledge what were requirements for those method.

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	public void Validator_WhenAllPropertiesAreValid_ShouldReturnTrue()
Validator won't return true. It returns EmptyValidationErrors list.

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	[Fact(Skip = "Test must be skipped till it can be executed using integration test context.")]
we won't skip this test. It doesn't need db context.

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	public void Validator_WhenIncomeTypeWithNegativeValue_ShouldReturnFalse()
Again problem with expected return

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionValidatorTests.cs
> +	public void Validator_WhenAllPropertiesAreValid_ShouldReturnTrue()
Also you test Validate method not Validator method. It can confuse a little bit person who look at this code

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/GetBudgetTransactionsValidatorTests.cs
> +	public void Validator_WhenPageIndexOrAndSizeIsLowerOrEqual0_ShouldReturnFalse()
OrAnd

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/GetBudgetTransactionsValidatorTests.cs
> +	public void Validator_WhenAllPropertiesAreValid_ShouldReturnTrue()
Same as for all Validator tests change Validator to Validate and ShouldNoReturnValidationErrors

2023-05-02 11:51 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/GetBudgetTransactionsValidatorTests.cs
> +	[Fact(Skip = "Test must be skipped till it can be executed using integration test context.")]
Test shouldn't be skipped if it uses repository only.

2023-05-05 22:41 UTC, mateuszgiedzinski requested changes

2023-05-05 22:41 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionCommandHandlerTests.cs
> +/// Test that checks the behavior of a query handler class "CreateBudgetTransaction".
command handler.

2023-05-05 22:41 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/CreateBudgetTransactionCommandHandlerTests.cs
> +	private readonly CreateBudgetTransactionCommandHandler handleCreateBudgetTransaction;
i suggest call it instance or sut (system under test). Personally I prefer calling my tested object "instance".

2023-05-06 06:00 UTC, pzajaczkowski approved these changes

2023-05-06 13:22 UTC, mateuszgiedzinski approved these changes

2023-05-06 13:23 UTC, merged