feature/PATRO23-41 - Remove budget
intive/patronage2023-dotnet pull request #69
Opened 2023-04-30 23:22 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-41

2023-05-02 12:28 UTC, mateuszgiedzinski requested changes

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			.Where(b => !b.IsBudgetDeleted)
should be done as global filter.

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/RemoveBudget/RemoveBudgetValidator.cs
> +			.MustAsync((x, cancellation) => this.NoExistingBudget(x.Id, executionContextAccessor, cancellation))
method that checks something and returns bool should starts with Is, Can or  Has  prefix for example IsBudgetExists.

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetTransactionAggregate.cs
> +		this.CheckRule(new SuperImportantBudgetBusinessRuleForIsDeleted(isDeleted));
The name of the rule was just example. Change it. For example BudgetTransactionCannotBeDeletedTwiceBussinessRule.

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetTransactionAggregate.cs
> +	public void UpdateIsRemoved(bool isDeleted)
Remove()

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/domain/BudgetTransactionAggregate.cs
> +	public void UpdateIsRemoved(bool isDeleted)
Or SoftRemove()

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/BudgetDbContext.cs
> +		modelBuilder.Entity<BudgetAggregate>().HasQueryFilter(b => !b.IsDeleted);
put this in EntityConfiguration

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Data/DataConfiguration/BudgetAggregateEntityConfiguration.cs
> +		builder.Property(x => x.IsDeleted).HasColumnName("IsDeleted");
This should be State.

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Domain/BudgetTransactionRepository.cs
> +	public async Task Update(BudgetTransactionAggregate budgetTransaction)
Can we use only persist method and check if entity is new or not there?

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Domain/BudgetTransactionRepository.cs
> +	public async Task Update(BudgetTransactionAggregate budgetTransaction)
We can use changeTracker for that.

2023-05-02 12:28 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Domain/EventHandlers/BudgetSoftDeleteDomainEventHandler.cs
> +		// TODO: Use logger
here you should add the code needed for calling BudgetTransaction delete command.

2023-05-03 11:31 UTC, DawidBski commented on src/modules/budget/application/Budget/RemoveBudget/RemoveBudgetValidator.cs
> +			.MustAsync((x, cancellation) => this.NoExistingBudget(x.Id, executionContextAccessor, cancellation))
We took the name of the method from CreateBudgetValidator which is on the development branch. That's why we think the name is appropriate.

2023-05-03 16:36 UTC, DawidBski commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +			isDeleted);
Our Create method is kind of weird.
![image](https://user-images.githubusercontent.com/127483473/235981989-4a641f3d-4afe-4ce8-b9b7-b15b2c07b77b.png)

2023-05-03 18:02 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	/// <summary>
I think there is no need to create example. This endpoint only required BudgetId given in route.

2023-05-03 18:41 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/CreatingBudget/CreateBudget.cs
> +			isDeleted);
I think we can set this in Entity Configuration, like below (we tested this and all works fine):
![image](https://user-images.githubusercontent.com/42235058/236012113-d21e3bdc-b758-499f-b2a6-7ae7d09db247.png)

2023-05-03 20:33 UTC, IzabelaPalubicka commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
Isn't it too long?

2023-05-03 20:33 UTC, IzabelaPalubicka commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
Same as before

2023-05-03 20:35 UTC, DawidBski commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
Good Point :)

2023-05-03 20:35 UTC, DawidBski commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
Good Point :)

2023-05-03 20:43 UTC, IzabelaPalubicka commented on src/modules/budget/domain/Rules/BudgetTransactionCannotBeDeletedTwiceBusinessRule.cs
> +public class BudgetTransactionCannotBeDeletedTwiceBusinessRule : IBusinessRule
This class is same as BudgetCannotBeDeletedTwiceBusinessRule. It would be better to create a single rule that checks if it has not already been deleted

2023-05-03 20:55 UTC, IzabelaPalubicka commented on src/modules/budget/contracts/Events/BudgetCreatedDomainEvent.cs
> +	public bool IsDeleted { get; private set; } = default;
Can it be deleted while adding?

2023-05-03 21:30 UTC, IzabelaPalubicka commented on src/modules/budget/contracts/Events/BudgetTransactionCreatedDomainEvent.cs
> +	public bool IsBudgetDeleted { get; set; } = default;
I think you should add to the CreateBudgetTransactionValidator that the budget have to be Active

2023-05-04 12:35 UTC, LukaszWinowicz commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
According to the conversation I set "varchar(10)".

2023-05-04 12:35 UTC, LukaszWinowicz commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
According to the conversation I set "varchar(10)".

2023-05-04 12:37 UTC, LukaszWinowicz commented on src/modules/budget/domain/Rules/BudgetTransactionCannotBeDeletedTwiceBusinessRule.cs
> +public class BudgetTransactionCannotBeDeletedTwiceBusinessRule : IBusinessRule
BudgetTransactionCannotBeDeletedTwiceBusinessRule and BudgetCannotBeDeletedTwiceBusinessRule changed to one class StatusDeletedCannotBeSetTwiceBusinessRule.

2023-05-04 14:11 UTC, mateuszgiedzinski requested changes

2023-05-04 14:11 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/RemoveBudget/RemoveBudgetValidator.cs
> +			.MustAsync((x, cancellation) => this.NoExistingBudget(x.Id, executionContextAccessor, cancellation))
Ok but in most of cases method name should contains verb. I suggest using that unless you build fluent interface as you have for validation rules.

2023-05-04 14:11 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/RemovingBudgetTransactions/RemoveBudgetTransactions.cs
> +			transaction.SoftRemove(status);
same problem with remove method. State change should be closed inside SoftRemove method and user shouldn't have possibility to decide about status on deleting.

2023-05-04 14:13 UTC, mateuszgiedzinski commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
Why this is string?  Enum could be stored as tinyint ( uint) this give us 255 possibilities ( it's enough for status ) and it will be only 8 bits long.

2023-05-04 15:00 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/RemoveBudget/RemoveBudgetValidator.cs
> +			.MustAsync((x, cancellation) => this.NoExistingBudget(x.Id, executionContextAccessor, cancellation))
I changed to IsExistingBudget. It's check that budget exist (by BudgetId) and return true if yes and false with the message when no.

2023-05-04 15:29 UTC, LukaszWinowicz commented on src/modules/budget/infrastructure/Migrations/BudgetDbContextModelSnapshot.cs
> +                        .HasColumnType("nvarchar(max)")
I changed this to tinyint `builder.Property(x => x.Status).HasColumnName("Status").HasConversion<byte>().HasColumnType("tinyint").HasDefaultValue(Status.Active);`

2023-05-04 22:43 UTC, mateuszgiedzinski requested changes
I realized that unit tests are missing. You could check command and validate if state is set correctly And also resolve merge conflicts.

2023-05-05 22:36 UTC, mateuszgiedzinski approved these changes
One small change but conditionally I can approve.

2023-05-05 22:36 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/RemoveBudget/RemoveBudget.cs
> +public class HandlerRemoveBudget : ICommandHandler<RemoveBudget>
HandleRemoveBudget or RemoveBudgetCommandHandler ( if test won't fail)

2023-05-06 05:57 UTC, DawidBski commented on src/modules/budget/application/Budget/RemoveBudget/RemoveBudget.cs
> +public class HandlerRemoveBudget : ICommandHandler<RemoveBudget>
![image](https://user-images.githubusercontent.com/127483473/236603062-3e9e01f8-6d87-4b8c-8078-3aadda9fb2cc.png)
As you predicted. So we will set the HandleRemoveBudget name.

2023-05-06 13:32 UTC, Kepeczsz approved these changes

2023-05-06 13:32 UTC, merged