[BE] Feature/patro23 53 request/response logging middleware
intive/patronage2023-dotnet pull request #7
Opened 2023-03-10 16:54 UTC by Kepeczsz

https://tracker.intive.com/jira/secure/RapidBoard.jspa?rapidView=1665&view=detail&selectedIssue=PATRO23-53

2023-03-11 16:26 UTC, mateuszmuszynski requested changes

2023-03-11 16:26 UTC, mateuszmuszynski commented on src/api/app/appsettings.json
> +		"LogLevel": {
Incorrect indentation

2023-03-11 16:26 UTC, mateuszmuszynski commented on src/api/app/Program.cs
>  app.Run();
Add new line at the end of file

2023-03-12 21:21 UTC, Kepeczsz commented on src/api/app/appsettings.json
> +		"LogLevel": {
i do not understand, how that's incorrect indentation, can u provide me more information?
It seems like github has in his view indentation of 4, whereas i use standard option for js formatting of 2.
and it looks like it on my pc.
![obraz_2023-03-12_222042195](https://user-images.githubusercontent.com/52294433/224574398-892b0ae1-a6f2-4176-936b-b2bf231e4003.png)

2023-03-12 21:32 UTC, Kepeczsz commented on src/api/app/appsettings.json
> +		"LogLevel": {
@mateuszmuszynski

2023-03-13 08:34 UTC, mateuszmuszynski commented on src/api/app/appsettings.json
> +		"LogLevel": {
It looks like there are spaces and tabs in this file. Please use spaces OR tabs.
![image](https://user-images.githubusercontent.com/13312305/224648189-efb94e7e-59c4-4be2-b010-8100538cca85.png)

2023-03-13 17:06 UTC, Kepeczsz commented on src/api/app/appsettings.json
> +		"LogLevel": {
@mateuszmuszynski  i've refactored file to use only tabs, also merged dev into my branch, to resolve merge conflicts.

2023-03-13 23:05 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
>  app.Run();
@mateuszmuszynski  relates to our stylecop rule ends file with new line is incorrect. But I suggest to add new line between registration like below.
app.UseExampleModule

app.UseHttpLogging

app.Run

2023-03-13 23:07 UTC, mateuszgiedzinski requested changes

2023-03-13 23:07 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> +app.UseHttpLogging();
I suggest separate UseHttpLogging() UseModule..() and Run() by empty line.

2023-03-15 12:27 UTC, mateuszgiedzinski approved these changes

2023-03-15 12:50 UTC, mateuszmuszynski approved these changes

2023-03-15 16:10 UTC, merged