Feature/patro23 299 mock budget statistic details
intive/patronage2023-dotnet pull request #71
Opened 2023-05-05 16:12 UTC by Kepeczsz

https://tracker.intive.com/jira/secure/RapidBoard.jspa?rapidView=1665&projectKey=PATRO23&view=detail&selectedIssue=PATRO23-299

2023-05-05 17:52 UTC, LukaszWinowicz commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[HttpPost("{budgetId:guid}/budgetStatistic")]
It wouldn't be better like `[HttpPost("{budgetId:guid}/statistics")]`?

2023-05-05 17:52 UTC, LukaszWinowicz commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistic.cs
> +	public Guid Id { get; set; }
Shouldn't there also be "BudgetId" as in BudgetStatisticInfo?

2023-05-05 17:52 UTC, LukaszWinowicz commented on src/modules/budget/api/Controllers/BudgetController.cs
> +			var pagedList = await this.queryBus.Query<GetBudgetStatistic, BudgetStatistics<BudgetStatisticInfo>>(getBudgetStatistic);
Why are some names with an "s" at the end and some not? Like: `GetBudgetStatistic` and `BudgetStatistics`.

2023-05-05 22:25 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[HttpPost("{budgetId:guid}/budgetStatistic")]
@Kepeczsz  I told you to do that as budgets/{budgetId}/statistics

2023-05-05 22:32 UTC, mateuszgiedzinski requested changes

2023-05-05 22:32 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	[HttpPost("{budgetId:guid}/budgetStatistic")]
It could be Get and have startdate and end date as query params

2023-05-05 22:32 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/BudgetStatisticInfo.cs
> +public record BudgetStatisticInfo()
record BudgetAmount (decimal Value, DateTime DatePoint )

2023-05-07 18:11 UTC, mateuszgiedzinski requested changes

2023-05-07 18:11 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/BudgetAmount.cs
> +/// <summary>
empty line missing after namespace

2023-05-07 18:11 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +	public async Task<IActionResult> GetBudgetStatisticsBetweenDates([FromRoute] Guid budgetId, [FromRoute] GetBudgetStatisticsDateInfo request)
@Kepeczsz  I told to have query parameters Start and end dates not FromRoute parameters and of course nullable.

2023-05-07 19:15 UTC, mateuszgiedzinski approved these changes

2023-05-07 19:16 UTC, DawidBski approved these changes

2023-05-07 19:22 UTC, merged