feature/PATRO23-41 - add remove budget test
intive/patronage2023-dotnet pull request #78
Opened 2023-05-07 14:40 UTC by DawidBski

2023-05-07 15:35 UTC, IzabelaPalubicka approved these changes

2023-05-08 09:29 UTC, pzajaczkowski approved these changes

2023-05-08 10:23 UTC, LukaszWinowicz approved these changes

2023-05-08 12:58 UTC, mateuszgiedzinski requested changes

2023-05-08 21:15 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +	public async Task Handle_WhenCalledOnExistingBudget_ShouldSetBudgetStatusToDeleted()
To clarify additional tests needed.

2023-05-09 20:18 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +	public async Task Handle_WhenCalledOnExistingBudget_ShouldSetBudgetStatusToDeleted()
Ok I'll add it asap.

2023-05-11 13:16 UTC, PiotrekkP approved these changes

2023-05-13 10:34 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +	public async Task Handle_WhenCalledOnExistingBudget_ShouldSetBudgetStatusToDeleted()
I think it's done.

2023-05-15 14:39 UTC, mateuszmuszynski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +	public async Task Handle_WhenCalledOnDeletedBudget_ShouldBusinessRuleValidationException()
Should**Throw**BusinessRuleValidationException

2023-05-15 14:39 UTC, mateuszmuszynski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +		await this.instance.Handle(removeBudget, cancellationToken);
It's a good practice to use "sut" (system under test) variable name for class that is being tested.

2023-05-15 15:18 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +		await this.instance.Handle(removeBudget, cancellationToken);
I know.
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/7b3efc11-e988-4441-850a-1fd6c8a4dc05)
Maybe we should consider establishing a convention in our project regarding the naming of "systems under test"?

2023-05-15 16:15 UTC, KlaudiaGajocha approved these changes

2023-05-15 18:35 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +		await this.instance.Handle(removeBudget, cancellationToken);
Okay we can leave it instance but please check other tests. We must be consistent,

2023-05-15 19:49 UTC, DawidBski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/RemoveBudgetCommandHandlerTests.cs
> +		await this.instance.Handle(removeBudget, cancellationToken);
I'll make another task for this.

2023-05-15 20:17 UTC, merged