Feature/patro23 46 fluent validation
intive/patronage2023-dotnet pull request #8
Opened 2023-03-10 18:27 UTC by PiotrekkP

2023-03-11 17:14 UTC, mateuszmuszynski requested changes

2023-03-11 17:14 UTC, mateuszmuszynski commented on src/modules/example/api/Controllers/ExampleController.cs
> +		string errorResponse = new ErrorResponse(" ", " ", " ", validator.Errors).ToJson();
Correct me if I'm wrong, but I think this code will never be called as you registered automatic validation in ExampleModule.

2023-03-11 17:14 UTC, mateuszmuszynski commented on src/modules/example/api/Controllers/ExampleController.cs
> +		string errorResponse = new ErrorResponse(" ", " ", " ", validator.Errors).ToJson();
Why you pass empty strings here?

2023-03-11 17:14 UTC, mateuszmuszynski commented on src/modules/example/application/Example/ErrorResponse.cs
> +			string json = JsonSerializer.Serialize(this);
I doubt it will work. It will not serialize private fields.

2023-03-13 23:01 UTC, mateuszgiedzinski requested changes

2023-03-15 14:02 UTC, PiotrekkP commented on src/modules/example/api/Controllers/ExampleController.cs
> +		string errorResponse = new ErrorResponse(" ", " ", " ", validator.Errors).ToJson();
I wasn't sure what exactly should i pass here, so i leave these "empty not empty" strings like this so we can discuss it. But as i can see even the way i am trying to create this error response isn't the best one.

2023-03-18 11:38 UTC, mateuszmuszynski approved these changes

2023-03-19 16:56 UTC, mateuszgiedzinski approved these changes

2023-03-19 19:15 UTC, merged