Feature/patro23 24 list of users in application
intive/patronage2023-dotnet pull request #80
Opened 2023-05-07 21:48 UTC by a-lipert

https://tracker.intive.com/jira/browse/PATRO23-24

Cooperation with @pzajaczkowski.

2023-05-07 22:02 UTC, pzajaczkowski commented
Keycloak API search works like sql -> LIKE 'a%'. So our endpoint search works the same.

2023-05-08 13:12 UTC, mateuszgiedzinski requested changes

2023-05-08 13:12 UTC, mateuszgiedzinski commented on src/modules/user/application/GettingUsers/GetUsers.cs
> +public class GetUsersQueryHandler : IQueryHandler<GetUsers, PagedList<UserInfo>>
So this Query Handler is independent from database so we can write unit tests for it.

2023-05-08 20:51 UTC, IzabelaPalubicka commented on src/modules/user/contracts/UserAttributes.cs
> +	public string[] Avatar { get; set; } = null!;
Why is this an array?

2023-05-08 20:57 UTC, IzabelaPalubicka commented on src/modules/user/api/UserModule.cs
> +		//// services.AddScoped<IExecutionContextAccessor, ExecutionContextAccessor>();
comment to delete?

2023-05-08 20:59 UTC, IzabelaPalubicka commented on src/modules/user/application/GettingUsers/GetUsersValidator.cs
> +		this.RuleFor(budget => budget.PageSize).GreaterThan(0);
change budget to x

2023-05-08 21:03 UTC, mateuszgiedzinski commented on src/modules/user/application/GettingUsers/GetUsersValidator.cs
> +		this.RuleFor(budget => budget.PageSize).GreaterThan(0);
someone tells me that we should use x, y, n  in this order as lambda names but I sometimes use item also. But in this case of course budget is invalid.

2023-05-09 07:15 UTC, a-lipert commented on src/modules/user/application/GettingUsers/GetUsersValidator.cs
> +		this.RuleFor(budget => budget.PageSize).GreaterThan(0);
I don't know how we overlooked that :D thanks

2023-05-09 07:40 UTC, pzajaczkowski commented on src/modules/user/contracts/UserAttributes.cs
> +	public string[] Avatar { get; set; } = null!;
Due to json deserialization. That's what we are receiving from Keycloak Rest API.

2023-05-09 07:41 UTC, pzajaczkowski commented on src/modules/user/application/GettingUsers/GetUsersValidator.cs
> +		this.RuleFor(budget => budget.PageSize).GreaterThan(0);
well known copy paste technique xD

2023-05-09 07:42 UTC, a-lipert commented on src/modules/user/api/UserModule.cs
> +		//// services.AddScoped<IExecutionContextAccessor, ExecutionContextAccessor>();
It was marked to be moved to shared module. It's done now.

2023-05-09 21:06 UTC, IzabelaPalubicka approved these changes
Works fine :smiley:

2023-05-10 05:57 UTC, a-lipert commented on src/modules/user/application/GettingUsers/GetUsers.cs
> +public class GetUsersQueryHandler : IQueryHandler<GetUsers, PagedList<UserInfo>>
Done :)

2023-05-10 11:48 UTC, mateuszgiedzinski requested changes

2023-05-10 11:48 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.User.Application.Tests/GetUsersQueryHandlerTests.cs
> +	public async Task Handle_WhenCalled_ShouldApplyPaginationForUsersList()
When + conditions under what you tests for example WhenPaginationSpecified

2023-05-10 15:34 UTC, mateuszgiedzinski approved these changes
Only one line break needs fix. But it's minor change.

2023-05-10 15:34 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.User.Application.Tests/GetUsersQueryHandlerTests.cs
> +
empty line is not needed. I suggest using CTRL+K, CTRL+E shortcut to cleanup active doc.

2023-05-10 15:56 UTC, merged