feature/PATRO23-273 - roles and permissions
intive/patronage2023-dotnet pull request #81
Opened 2023-05-07 23:37 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-273

A prototype that meets the requirements of the task, but done in a different way than suggested by the leaders.

2023-05-08 09:26 UTC, pzajaczkowski requested changes
Didn't have much time so i may have missed few things but overall looks good. One thing that bothers me is fact that we have to create permission service in every single module. Maybe there is way to make it shared or sth.

2023-05-08 09:26 UTC, pzajaczkowski commented on src/shared/infrastructure/ExecutionContextAccessor.cs
> +		if (isAdmin)
Guys pls xD. You don't have to check bool in if u can simply return it.
`return isAdmin;`

2023-05-08 09:26 UTC, pzajaczkowski commented on src/modules/budget/application/PermissionsService.cs
> +		bool isAdmin = false; //// this.contextAccessor.IsUserAdmin(); TODO: uncomment if you need to test if user is Admin.
why is this variable hard coded to false? Shouldn't admin have permissions to do everything?

2023-05-08 09:26 UTC, pzajaczkowski commented on src/modules/budget/api/ResourcePermissions/BudgetAuthorizationHandler.cs
> +		////bool isAdmin = this.contextAccessor.IsUserAdmin();
Is this commented code necessary?

2023-05-08 20:36 UTC, mateuszgiedzinski requested changes

2023-05-08 20:36 UTC, mateuszgiedzinski commented on src/api/app/Program.cs
> -builder.Services.AddHttpClient();
what's wrong with this AddHttpClient()?

2023-05-08 20:36 UTC, mateuszgiedzinski commented on src/modules/budget/api/ResourcePermissions/BudgetAuthorizationHandler.cs
> +		bool isPermissions = await this.budgetDbContext.UserBudget.AnyAsync(x => x.UserId == userId && x.BudgetId == budgetId);
isPermited or hasPermission

2023-05-08 20:36 UTC, mateuszgiedzinski commented on src/modules/budget/api/ResourcePermissions/BudgetAuthorizationHandler.cs
> +		bool isPermissions = await this.budgetDbContext.UserBudget.AnyAsync(x => x.UserId == userId && x.BudgetId == budgetId);
First of all I will use new query here.

2023-05-08 20:36 UTC, mateuszgiedzinski commented on src/modules/budget/api/ResourcePermissions/BudgetAuthorizationHandler.cs
> +					context.Fail();
If this won't throw exception then context.Succeed(requirement); will also run.

2023-05-08 20:42 UTC, LukaszWinowicz commented on src/api/app/Program.cs
> -builder.Services.AddHttpClient();
There is another one in line 49.

2023-05-08 21:53 UTC, IzabelaPalubicka commented on src/modules/budget/api/Controllers/BudgetController.cs
>  		var validationResult = await this.getBudgetsValidator.ValidateAsync(request);
you can simplify it by using ValidateAndThrowAsync

2023-05-09 18:51 UTC, DawidBski commented on src/modules/budget/application/PermissionsService.cs
> +		bool isAdmin = false; //// this.contextAccessor.IsUserAdmin(); TODO: uncomment if you need to test if user is Admin.
As I wrote in PR description before it was prototype code. And some features required manually uncomment some code xD :)

2023-05-09 18:55 UTC, DawidBski commented on src/shared/infrastructure/ExecutionContextAccessor.cs
> +	public bool IsUserAdmin()
Changed.

2023-05-09 19:47 UTC, DawidBski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +			if (this.permissionsService.IsPermission(new BudgetId(budgetId)))
I know. We just created this because we could easier understand business logic of our problem and this approach helped us with it. It was late and instead of make it draft I did PR.

2023-05-09 19:48 UTC, DawidBski commented on src/modules/budget/api/ResourcePermissions/BudgetAuthorizationHandler.cs
> +		bool isPermissions = await this.budgetDbContext.UserBudget.AnyAsync(x => x.UserId == userId && x.BudgetId == budgetId);
I think it's done now.

2023-05-09 19:50 UTC, DawidBski commented on src/modules/budget/api/ResourcePermissions/BudgetAuthorizationHandler.cs
> +					context.Fail();
Corrected.

2023-05-09 20:05 UTC, DawidBski commented on src/modules/budget/application/EventHandlers/UserBudgetAddedDomainEventHandler.cs
> +using Intive.Patronage2023.Modules.Budget.Contracts.Events;
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/ec96f802-f3c7-4021-a8af-c49d039b5469)
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/bfc6a797-b128-458a-a5dd-f4667b041a37)
Probably we could create GlobalUsing.cs file that contains frequently used namespaces.  My IDE detects those usings and send me warnings. Of course i could configure it accordingly so that it does not do it. I removed this pragma code.

2023-05-09 20:06 UTC, DawidBski commented on src/api/app/Program.cs
> -builder.Services.AddHttpClient();
If it's ok @mateuszgiedzinski resolve this conversation.

2023-05-10 11:26 UTC, mateuszgiedzinski approved these changes

2023-05-10 13:16 UTC, pzajaczkowski approved these changes

2023-05-10 20:51 UTC, merged