Feature/patro23 277 cancel income expense
intive/patronage2023-dotnet pull request #83
Opened 2023-05-08 11:13 UTC by Kepeczsz

https://tracker.intive.com/jira/browse/PATRO23-277

2023-05-08 20:10 UTC, mateuszgiedzinski requested changes

2023-05-08 20:10 UTC, mateuszgiedzinski commented on src/modules/budget/contracts/TransactionEnums/Status.cs
> +	Cancelled = 2,
delete state missing.

2023-05-08 20:10 UTC, mateuszgiedzinski commented on src/modules/budget/contracts/TransactionEnums/Status.cs
> +	Reccuring = 3,
invalid state summary

2023-05-08 20:10 UTC, mateuszgiedzinski commented on src/modules/budget/application/EventHandlers/BudgetSoftDeletedDomainEventHandler.cs
> +		var removeBudgetTransactions = new CancellBudgetTransactions(notification.Id.Value);
revert name change.

2023-05-09 14:35 UTC, DawidBski requested changes

2023-05-09 14:35 UTC, DawidBski commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransaction.cs
> +		var transaction = this.budgetDbContext.Transaction
Didn't we have in BudgetTransaction Repository a method GetById?

2023-05-09 14:35 UTC, DawidBski commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransactionValidator.cs
> +		return await this.budgetDbContext.Transaction.AnyAsync(b => b.Id.Equals(new TransactionId(id)));
Same we can use GetById from repository

2023-05-09 18:58 UTC, Kepeczsz commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransaction.cs
> +		var transaction = this.budgetDbContext.Transaction
as you said we have that in Repository, not in BudgetDbContext

2023-05-09 19:10 UTC, Kepeczsz commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransactionValidator.cs
> +		return await this.budgetDbContext.Transaction.AnyAsync(b => b.Id.Equals(new TransactionId(id)));
here i cannot use getbyId from repository, because i have only dbContext.

2023-05-09 19:10 UTC, Kepeczsz commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransaction.cs
> +		var transaction = this.budgetDbContext.Transaction
here i can use built in GetById from repository.

2023-05-09 21:36 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransactionValidator.cs
> +	private async Task<bool> IsExistingBudget(Guid id)
`IsExistingTransaction` not budget

2023-05-09 21:50 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransactionValidator.cs
> +			.MustAsync((x, cancellation) => this.IsExistingBudget(x.Id));
```suggestion
			.MustAsync(async (x, cancellation) => await this.IsExistingTransaction(x));
```

2023-05-09 21:50 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransactionValidator.cs
> +		this.RuleFor(transaction => new { transaction.Id })
```suggestion
		this.RuleFor(transaction => transaction.Id)
```

2023-05-09 22:24 UTC, IzabelaPalubicka commented
Fix all cancell typos

2023-05-09 22:34 UTC, IzabelaPalubicka commented on src/modules/budget/application/Budget/CancellBudgetTransaction/CancellBudgetTransaction.cs
> +public record CancellBudgetTransaction(Guid Id) : ICommand;
Fix all `cancell` typos in class names, files and folder

2023-05-10 09:19 UTC, mateuszgiedzinski requested changes

2023-05-10 09:19 UTC, mateuszgiedzinski commented on src/modules/budget/domain/Rules/StatusCancelledCannotBeSetTwiceBusinessRule.cs
> +public class StatusCancelledCannotBeSetTwiceBusinessRule : IBusinessRule
The name tells us that status cannot be cancelled twice but we are checking also if status is  equal Deleted. 
This check for Deleted status should be done by another rule.

2023-05-10 12:48 UTC, mateuszgiedzinski approved these changes

2023-05-10 13:07 UTC, IzabelaPalubicka approved these changes

2023-05-10 15:34 UTC, merged