[PATRO23-299] fix budget values
intive/patronage2023-dotnet pull request #84
Opened 2023-05-08 16:53 UTC by Kepeczsz

fix for 299 budgetValue
https://tracker.intive.com/jira/browse/PATRO23-299

2023-05-08 19:58 UTC, mateuszgiedzinski requested changes

2023-05-08 19:58 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/BudgetAmount.cs
> -	public decimal Value { get; init; }
record should be immutable. if you need to change record, change whole object using with keyword.

2023-05-08 19:58 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +			.Where(x => x.BudgetId == budgetId && x.BudgetTransactionDate > query.StartDate && x.BudgetTransactionDate <= query.EndDate)
It will be nice to have extension that can filter us by Budget. then code could look like await budgets.For(budgetId).Within(period). Select(BudgetStatisticsInfoMapper.Map).GroupBy(x => x.DatePoint.Date)
				.Select(x => new BudgetAmount
				{
					DatePoint = x.Key,
					Value = x.Sum(x => x.Value),
				})
				.ToListAsync(cancellationToken: cancellationToken);

2023-05-10 15:12 UTC, mateuszgiedzinski requested changes

2023-05-10 15:12 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +			.Where(x => x.BudgetTransactionDate >= query.StartDate && x.BudgetTransactionDate <= query.EndDate)
Within(startDate, endDate)

2023-05-10 15:12 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/BudgetAmount.cs
> -	public decimal Value { get; init; }
this is not not fixed still has setter.

2023-05-13 09:57 UTC, mateuszgiedzinski requested changes

2023-05-13 09:57 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtension.cs
> +	public static IQueryable<BudgetTransactionAggregate> FilterCancelledTransactions(this IQueryable<BudgetTransactionAggregate> query)
NotCancelled()

2023-05-15 16:14 UTC, pzajaczkowski approved these changes

2023-05-15 16:50 UTC, mateuszmuszynski requested changes

2023-05-15 16:50 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
>  		var budgets = this.budgetDbContext.Transaction.AsQueryable();
It's list of transactions, not budgets.

2023-05-15 16:50 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		decimal budgetValueAtStartDate = budgets
Can we split it into smaller methods?

2023-05-15 16:50 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		var result = new BudgetStatistics<BudgetAmount> { Items = budgetTransactionValues, TotalBudgetValue = totalBudgetValue, PeriodValue = periodValue, TrendValue = trendValue };
It's pretty complex logic, it would be good to write tests.

2023-05-15 18:22 UTC, Kepeczsz commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		var result = new BudgetStatistics<BudgetAmount> { Items = budgetTransactionValues, TotalBudgetValue = totalBudgetValue, PeriodValue = periodValue, TrendValue = trendValue };
i will have time propably after tommorow evening/Wednesday, maybe @pzajaczkowski could merge this branch to his, and leave Extensions folder, so he could work on his task.

2023-05-15 20:14 UTC, mateuszgiedzinski requested changes

2023-05-15 20:14 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtension.cs
> +internal static class BudgetTransactionsQueryExtension
extensions class in plural form. Extensions postfix.

2023-05-15 20:14 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtension.cs
> +	/// Checks if date of transactions is in specified date.
is beetween.

2023-05-15 20:14 UTC, mateuszgiedzinski commented on src/modules/budget/application/Extensions/BudgetTransactionsQueryExtension.cs
> +	/// <param name="query">query.</param>
What query?

2023-05-15 20:14 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +			var updatedBudget = prevBudget with {
this looks really weird. You're modyfing budgetTransactionValues[i] so you should use this as reference 
so 
budgetTransactionValues[i] = budgetTransactionValues[i] with {
Value += prevBudget.Value, 
}

looks simpler.

2023-05-19 15:05 UTC, Kepeczsz commented on src/modules/budget/application/Budget/GettingBudgetStatistics/GetBudgetStatistics.cs
> +		decimal budgetValueAtStartDate = budgets
I am not sure, if it's good idea to split it to smaller methods, but i added about 10 tests.

2023-05-20 23:41 UTC, DawidBski approved these changes

2023-05-21 10:22 UTC, KlaudiaGajocha approved these changes

2023-05-22 07:00 UTC, mateuszmuszynski approved these changes

2023-05-22 09:10 UTC, mateuszgiedzinski approved these changes

2023-05-22 11:11 UTC, merged