[PATRO23-312] Add filtering by type
intive/patronage2023-dotnet pull request #89
Opened 2023-05-11 12:51 UTC by pzajaczkowski

https://tracker.intive.com/jira/browse/PATRO23-312

Na razie draft bo testy integracyjne WIP i są z nimi małe problemy.

2023-05-12 13:47 UTC, mateuszgiedzinski requested changes

2023-05-12 13:47 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			.Where(x => x.BudgetId == query.BudgetId);
I'm not sure but I think we have extension for transactions to get budget like .For(budgetId)

2023-05-12 13:47 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			budgets = budgets.Where(x => x.TransactionType == query.TransactionType);
Maybe extension for that

2023-05-12 17:53 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			.Where(x => x.BudgetId == query.BudgetId);
Not yet on dev, but i can replace it after Michal merge his PR

2023-05-13 09:43 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			.Where(x => x.BudgetId == query.BudgetId);
Then fine.

2023-05-14 11:39 UTC, pzajaczkowski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
> +			budgets = budgets.Where(x => x.TransactionType == query.TransactionType);
Going to add if Michal manages to merge his PR first, or ask him to add in his PR in case of me being first.

2023-05-15 20:49 UTC, mateuszgiedzinski requested changes

2023-05-15 20:49 UTC, mateuszgiedzinski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/AbstractIntegrationTests.cs
> +[CollectionDefinition("Database collection")]
Collection definition should decorate new empty class that contains only connected ICollectionFixtures
![image](https://github.com/intive/patronage2023-dotnet/assets/31278269/3f0fa431-2cd8-4809-919b-494f3c2ce895)
In our case it could be something like below
![image](https://github.com/intive/patronage2023-dotnet/assets/31278269/f34c4bc6-f178-4b2d-a9d1-cba1d2626d1f)
Then if you decorate abstract class by Collection attribute and add IClassFixture everything will work without decorating normal tests classes.

2023-05-16 20:23 UTC, pzajaczkowski commented on tests/integration/Intive.Patronage2023.Shared.IntegrationTests/AbstractIntegrationTests.cs
> +[CollectionDefinition("Database collection")]
Okey, good point. Didn't bother tho with creating new attribute class for one usage but thanks for the tip.

2023-05-16 21:43 UTC, IzabelaPalubicka approved these changes

2023-05-17 03:18 UTC, mateuszgiedzinski approved these changes

2023-05-17 06:45 UTC, a-lipert approved these changes

2023-05-17 06:52 UTC, DawidBski approved these changes

2023-05-17 10:13 UTC, DawidBski approved these changes

2023-05-17 10:30 UTC, merged