Feature/patro23 58 Add domain event dispatcher
intive/patronage2023-dotnet pull request #9
Opened 2023-03-12 18:48 UTC by IzabelaPalubicka

services.AddSingleton is for verification

2023-03-13 10:25 UTC, mateuszmuszynski requested changes

2023-03-13 10:25 UTC, mateuszmuszynski commented on src/modules/example/infrastructure/Domain/EventHandlers/ExampleCreatedDomainEventHandler.cs
> +	public class ExampleCreatedDomainEventHandler : INotificationHandler<ExampleCreatedDomainEvent>
Please create and use new interface IDomainEventHandler<>. Module shouldn't know that it use MediatR library.
MediatR should only be used in Infrastructure/Abstractions projects.

2023-03-13 10:25 UTC, mateuszmuszynski commented on src/modules/example/infrastructure/Domain/ExampleRepository.cs
> +	public ExampleRepository(DomainEventDispatcher domainEventDispatcher)
Use `IEventDispatcher` interface instead of class

2023-03-13 10:25 UTC, mateuszmuszynski commented on src/api/app/Properties/launchSettings.json
> -      "launchBrowser": true,
Do we really need this changes?

2023-03-13 10:25 UTC, mateuszmuszynski commented on src/api/app/Program.cs
> +	cfg.Lifetime = ServiceLifetime.Singleton;
Use default MediatR lifetime.

2023-03-13 10:25 UTC, mateuszmuszynski commented on src/modules/example/api/ExampleModule.cs
> +		services.AddSingleton<INotificationHandler<ExampleCreatedDomainEvent>, ExampleCreatedDomainEventHandler>();
Use `services.AddMediatR`

2023-03-13 13:38 UTC, mateuszgiedzinski requested changes

2023-03-13 13:38 UTC, mateuszgiedzinski commented on src/modules/example/infrastructure/Domain/EventHandlers/ExampleNameUpdatedDomainEventHandler.cs
> +			Debug.WriteLine($"Example create domian event. {nameof(ExampleNameUpdatedDomainEventHandler)}");
Replace with // TODO: Add logging using ILogger<ExampleNameUpdatedDomainEventHandler>

2023-03-13 13:38 UTC, mateuszgiedzinski commented on src/modules/example/api/ExampleModule.cs
> +		services.AddSingleton<INotificationHandler<ExampleCreatedDomainEvent>, ExampleCreatedDomainEventHandler>();
The registration is fine. In future we will add assembly scanning to install all handlers from module.

2023-03-13 13:38 UTC, mateuszgiedzinski commented on src/modules/example/infrastructure/Domain/EventHandlers/ExampleCreatedDomainEventHandler.cs
> +			Debug.WriteLine($"Example create domian event. {nameof(ExampleCreatedDomainEventHandler)}");
Replace with comment // TODO: Use logger

2023-03-13 16:35 UTC, IzabelaPalubicka commented on src/api/app/Properties/launchSettings.json
> -      "launchBrowser": true,
Yes! It's very annoying when a browser window opens every time you reload the app.

2023-03-13 22:42 UTC, mateuszgiedzinski requested changes

2023-03-13 22:42 UTC, mateuszgiedzinski commented on src/shared/infrastructure/EventDispachers/DomainEventDispatcher.cs
> +			Debug.WriteLine($"Example create domian event. {nameof(DomainEventDispatcher)}");
Do not use Debug.Writeline.

2023-03-15 12:50 UTC, mateuszmuszynski approved these changes

2023-03-15 16:12 UTC, mateuszgiedzinski approved these changes
Resolve merge conflicts.

2023-03-15 16:44 UTC, merged