Bugfix/patro23-314-323 - fix invalid transaction cancel
intive/patronage2023-dotnet pull request #93
Opened 2023-05-12 19:45 UTC by DawidBski

### PATRO23-314 - add permission checking
https://tracker.intive.com/jira/browse/PATRO23-314

### PATRO23-323 - fix invalid transaction cancel endpoint and its validation
https://tracker.intive.com/jira/browse/PATRO23-323

**Added incidentally:**

- Add ProducesResponseType attribute to RemoveBudget and CancelBudgetTransaction actions

2023-05-13 09:41 UTC, mateuszgiedzinski requested changes

2023-05-13 09:41 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionBelongingToBudget(x.BudgetId, x.TransactionId));
Leave some error message

2023-05-13 12:09 UTC, DawidBski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionBelongingToBudget(x.BudgetId, x.TransactionId));
Error message and new rules are added.

2023-05-14 08:46 UTC, pzajaczkowski approved these changes

2023-05-14 14:56 UTC, Kepeczsz approved these changes

2023-05-15 16:57 UTC, mateuszmuszynski requested changes

2023-05-15 16:57 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionExists(x))
Some say that's a good practice to start bool returning methods with **Is** suffix, but these method names are not gramatically correct.
Imo methods that returns a boolean value should be named as a yes-no question.
Example:
IsTransactionExists -> TransactionExists / ShouldExist

2023-05-15 16:57 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionExists(x))
Please also update other rules

2023-05-15 17:07 UTC, DawidBski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionExists(x))
What do you mean other rules? Only in my validator or rather in every?

2023-05-15 18:44 UTC, DawidBski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionExists(x))
Ok Done.

2023-05-16 13:57 UTC, mateuszmuszynski approved these changes

2023-05-16 14:40 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/CancelBudgetTransaction/CancelBudgetTransactionValidator.cs
> +			.MustAsync(async (x, cancellation) => await this.IsTransactionExists(x))
For me both forms are correct. I disagree that our code should be gramatically correct. It must be consistent so if all our method which check condition has "Is", "Has" or "Can" prefixes we should follow that rule.

2023-05-16 14:40 UTC, mateuszgiedzinski approved these changes

2023-05-16 14:42 UTC, merged