feature/PATRO23-297 - change name of the business rules
intive/patronage2023-dotnet pull request #94
Opened 2023-05-13 16:27 UTC by DawidBski

https://tracker.intive.com/jira/browse/PATRO23-297

I've changed business rules names and added architecture test that checking whether Business Rule starts with "SuperImportant".

2023-05-13 18:37 UTC, LukaszWinowicz approved these changes

2023-05-14 08:41 UTC, pzajaczkowski requested changes

2023-05-14 08:41 UTC, pzajaczkowski commented on src/modules/budget/domain/Rules/BudgetCannotHaveNameStartedWithBrokenRuleBusinessRule.cs
This rule does not make sense. Why would we prevent user from naming budget "BrokenRule%"? I think that it was present in Example Module as an example. We don't have to copy it to budget. Remove the rule completely.

2023-05-14 08:41 UTC, pzajaczkowski commented on tests/architecture/ComponentNamingTests.cs
Don't replace test that checks if the class name ends with BusinessRule. It's useful comparing to the one you have added. No one will name rule "SuperImportant" anymore, because there won't be any rule with this name to copy after you merge. In otherwords i think this test is unncessary and should be removed from the scope of the task.

2023-05-14 08:43 UTC, DawidBski commented on src/modules/budget/domain/Rules/BudgetCannotHaveNameStartedWithBrokenRuleBusinessRule.cs
I agree with you.

2023-05-14 08:49 UTC, DawidBski commented on tests/architecture/ComponentNamingTests.cs
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/00785d5d-f7b4-4a46-b0ff-7e16ce2e801d)
I'm not sure if I understood correctly, but that's what the task said. What do you think about it?

2023-05-14 08:59 UTC, DawidBski commented on tests/architecture/ComponentNamingTests.cs
BTW the test checking if rule ends with BusinessRule are still there. I've only changed typo in business word. 
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/ad785cae-e319-4dd6-9e60-82368e930c8e)

2023-05-14 09:00 UTC, DawidBski commented on tests/architecture/ComponentNamingTests.cs
@pzajaczkowski

2023-05-14 09:01 UTC, pzajaczkowski commented on tests/architecture/ComponentNamingTests.cs
Task for sure does not said that you should replace exisiting test. I don't fully understand what does "test that will be checking for that names" mean, but i don't see this test you wrote as necessary. Anyway, you should restore test you have replaced, and if you want to add "SuperImportant" test, it's up to you.

2023-05-14 09:05 UTC, pzajaczkowski commented on tests/architecture/ComponentNamingTests.cs
![image](https://github.com/intive/patronage2023-dotnet/assets/82521883/b474383a-61be-44bd-9457-c9cde21eee07)
Okey then it's some github weirdness.

2023-05-14 10:06 UTC, DawidBski commented on src/modules/budget/domain/Rules/BudgetCannotHaveNameStartedWithBrokenRuleBusinessRule.cs
But It is not the scope of my task. There should be another one with:
1.Remove this rule.
2.Remove unused update method from BudgetAggregate.
3.Remove Event and EventHandler of Update method.

2023-05-15 08:57 UTC, Kepeczsz approved these changes

2023-05-15 13:16 UTC, pzajaczkowski approved these changes

2023-05-15 15:52 UTC, KlaudiaGajocha approved these changes

2023-05-15 17:06 UTC, mateuszmuszynski approved these changes

2023-05-15 17:06 UTC, mateuszmuszynski commented on src/modules/budget/domain/Rules/BudgetCannotHaveNameStartedWithBrokenRuleBusinessRule.cs
> +	public bool IsBroken() => this.name.StartsWith("brokenRule");
I know that's not your code, but I have not idea why we are preventing users from adding budget with name starting with "brokenRule" :D

2023-05-15 17:15 UTC, DawidBski commented on src/modules/budget/domain/Rules/BudgetCannotHaveNameStartedWithBrokenRuleBusinessRule.cs
> +	public bool IsBroken() => this.name.StartsWith("brokenRule");
As I wrote in the comment above we should create another task for removing it.
![image](https://github.com/intive/patronage2023-dotnet/assets/127483473/c6bef0a9-9940-4bc1-bec8-2a069ca66450)
I can create such a task and take care of it.

2023-05-15 18:22 UTC, merged