sorting and pagination fix
intive/patronage2023-dotnet pull request #95
Opened 2023-05-14 09:47 UTC by PiotrekkP

https://tracker.intive.com/jira/browse/PATRO23-327

2023-05-14 09:54 UTC, DawidBski approved these changes

2023-05-15 14:22 UTC, mateuszmuszynski requested changes

2023-05-15 14:22 UTC, mateuszmuszynski commented on src/modules/budget/application/Budget/GettingBudgetTransactions/GetBudgetTransactions.cs
>  		var mappedData = await budgets.Select(BudgetTransactionInfoMapper.Map)
Please write integration tests for this query

2023-05-15 15:51 UTC, KlaudiaGajocha approved these changes

2023-05-15 17:08 UTC, mateuszmuszynski approved these changes

2023-05-15 19:27 UTC, merged