feature/PATRO23-307 Remove redundant AppException classes
intive/patronage2023-dotnet pull request #96
Opened 2023-05-14 17:33 UTC by KlaudiaGajocha

Redundant AppException classes were removed

2023-05-15 10:34 UTC, IzabelaPalubicka commented
You should move class AppException from user module to shared module (to application project which you have to create)

2023-05-15 21:51 UTC, mateuszgiedzinski requested changes

2023-05-15 21:51 UTC, mateuszgiedzinski commented on src/modules/budget/api/Intive.Patronage2023.Modules.Budget.Api.csproj
> +    <ProjectReference Include="..\..\user\application\Intive.Patronage2023.Modules.User.Application.csproj" />
this reference is not needed

2023-05-15 21:51 UTC, mateuszgiedzinski commented on src/modules/example/api/Intive.Patronage2023.Modules.Example.Api.csproj
> +    <ProjectReference Include="..\..\user\application\Intive.Patronage2023.Modules.User.Application.csproj" />
this reference is not needed.

2023-05-16 18:43 UTC, KlaudiaGajocha commented on src/modules/example/api/Intive.Patronage2023.Modules.Example.Api.csproj
> +    <ProjectReference Include="..\..\user\application\Intive.Patronage2023.Modules.User.Application.csproj" />
removed

2023-05-16 18:43 UTC, KlaudiaGajocha commented on src/modules/budget/api/Intive.Patronage2023.Modules.Budget.Api.csproj
> +    <ProjectReference Include="..\..\user\application\Intive.Patronage2023.Modules.User.Application.csproj" />
removed

2023-05-17 03:19 UTC, mateuszgiedzinski approved these changes

2023-05-17 06:24 UTC, IzabelaPalubicka approved these changes

2023-05-17 15:39 UTC, merged