feature/PATRO23-276 - Add sharing budget
intive/patronage2023-dotnet pull request #97
Opened 2023-05-15 09:25 UTC by IzabelaPalubicka

https://tracker.intive.com/jira/browse/PATRO23-276

2023-05-15 13:34 UTC, pzajaczkowski approved these changes
Looks good

2023-05-15 13:34 UTC, pzajaczkowski commented on src/modules/budget/application/UserBudgets/AddingUserBudget/AddUsersToBudgetValidator.cs
> +				bool isAdmin = await this.IsAdmin(userId, cancellationToken);
Is there any reason why admin cannot be added to budget? I know he has all permissions but still. For example his icon won't be visible and probably few other things. Or we just assume that admin account is not being used as normal. Just pure admin tasks.

2023-05-15 15:15 UTC, IzabelaPalubicka commented on src/modules/budget/application/UserBudgets/AddingUserBudget/AddUsersToBudgetValidator.cs
> +				bool isAdmin = await this.IsAdmin(userId, cancellationToken);
In my opinion, admin account should be anonymous (ordinary users do not have access/knowledge to admin account data). If admin wants to be a member of some budget, he should create a normal user account.

2023-05-15 15:50 UTC, mateuszgiedzinski requested changes

2023-05-15 15:50 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		await this.usersIdsValidator.ValidateAndThrowAsync(addUsersToBudget);
do not throw errors from validator because exception throwed from this method is not catched in middleware.

2023-05-15 15:50 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		await this.usersIdsValidator.ValidateAndThrowAsync(addUsersToBudget);
userIdsValidator doesn't fit perfectly to validated object.

2023-05-15 15:50 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		var tasks = addUserToBudget.Select(x => this.commandBus.Send(x)).ToArray();
command could work on batch mode in my opinion. @mateuszmuszynski  What do you think?

2023-05-15 15:50 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/AddingUserBudget/AddUsersToBudgetValidator.cs
> +				bool isAdmin = await this.IsAdmin(userId, cancellationToken);
This is the question to our clients. Good point. For security reason better to have two different accounts.

2023-05-15 15:54 UTC, KlaudiaGajocha approved these changes

2023-05-15 18:27 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		var tasks = addUserToBudget.Select(x => this.commandBus.Send(x)).ToArray();
In agreement with @mateuszmuszynski  this should be one command that accepts list of users instead sending multiple commands.

2023-05-15 18:33 UTC, mateuszgiedzinski commented on src/modules/budget/api/Controllers/BudgetController.cs
> +		await this.usersIdsValidator.ValidateAndThrowAsync(addUsersToBudget);
If you want to do this that way we need extension which call Validate on validator and object and throw AppException on any errors

2023-05-18 20:52 UTC, mateuszgiedzinski requested changes

2023-05-18 20:52 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/AddingUserBudget/AddUsersToBudgetValidator.cs
> +		this.RuleFor(x => x.BudgetId).NotEmpty().NotNull().CustomAsync(async (id, validationContext, cancellationToken) =>
Why Custom instead of Must? We can use MustAsync here and specify message.

2023-05-18 20:52 UTC, mateuszgiedzinski commented on src/modules/budget/application/UserBudgets/AddingUserBudget/AddUsersToBudgetValidator.cs
> +			var budgetGuid = validationContext.InstanceToValidate.BudgetId;
move all this code to the method to simplify rule definition.

2023-05-20 10:12 UTC, mateuszgiedzinski requested changes

2023-05-20 10:12 UTC, mateuszgiedzinski commented on src/modules/budget/application/Budget/GettingBudgetDetails/GetBudgetDetails.cs
> +			throw new AppException();
Missing AppException message.

2023-05-20 10:12 UTC, mateuszgiedzinski commented on src/modules/user/application/CreatingUser/CreateUser.cs
> +		string accessToken = await this.keycloakService.ExtractAccessTokenFromClientToken(cancellationToken);
This is responsibility of keycloak service and could be closed in keycloak service. Maybe we should create task to refactor this service a little bit.

2023-05-20 10:12 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/GetBudgetDetailsQueryHandlerTests.cs
> +		this.keycloakService = keycloakService;
this won't work. You need to create mock.

2023-05-20 11:08 UTC, mateuszgiedzinski requested changes

2023-05-20 11:08 UTC, mateuszgiedzinski commented on tests/unit/Intive.Patronage2023.Budget.Application.Tests/GetBudgetDetailsQueryHandlerTests.cs
> +		var instance = new GetBudgetDetailsQueryHandler(null!, (IKeycloakService)this.keycloakServiceMock); // TODO: Use integration tests db context.
use mock.Object

2023-05-20 21:00 UTC, mateuszgiedzinski approved these changes

2023-05-20 21:30 UTC, merged